/**
 * Seam 1, from the model: the artefacts a synthetic index emits (the
 * `FourCC` overloads, the constants' declarations and Lua), and
 * `builtins:check` on a synthetic package root, which fails on a
 * hand-edited artefact and passes once it is emitted again.
 */
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { validateIndex } from "../src/check.js";
import { main } from "../src/cli/check.js";
import { emitArtefacts, rawcodeValue } from "../src/emit.js";
import {
  serializeIndex,
  serializeProvenance,
  type BuiltinsIndex,
} from "../src/model.js";
import { tempDir } from "./support/casc.js";

const INDEX: BuiltinsIndex = {
  format: 1,
  build: "3.0.0.24268",
  gameVersion: "3.0.0",
  gameDataSets: [{ id: "default", label: "Default" }],
  objects: {
    Hpal: {
      kind: "unit",
      name: "Paladin",
      race: "human",
      sets: ["default"],
      constant: "Paladin_Hpal",
    },
    hfoo: {
      kind: "unit",
      name: "Footman",
      race: "human",
      sets: ["default"],
      constant: "Footman_hfoo",
    },
    hnon: { kind: "unit", sets: ["default"], constant: "Unnamed_hnon" },
    nodd: {
      kind: "unit",
      name: "Odd <one> @ {here} */",
      sets: ["default"],
      constant: "OddOneHere_nodd",
    },
  },
};

const BANNER = [
  "Generated by reforged-builtins from the Built-in objects of Game version 3.0.0 (3.0.0/index.json).",
  "Derived identifiers only: Rawcodes, Object kinds, races and enUS names; no tooltip, number or icon.",
  "Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.",
  "Never edited by hand: `pnpm builtins:generate` writes it, and `pnpm builtins:check` fails on any difference.",
];

describe("the artefacts of an index", () => {
  const files = emitArtefacts(INDEX);

  it("are the overloads' entry, and the declarations and Lua of each kind it holds", () => {
    expect([...files.keys()]).toEqual([
      "3.0.0.d.ts",
      "3.0.0/units.d.ts",
      "3.0.0/units.lua",
    ]);
  });

  it("declare one FourCC overload per Rawcode, of its literal and kind, with its TSDoc", () => {
    expect(files.get("3.0.0.d.ts")).toBe(
      [
        "/** @noSelfInFile */",
        ...BANNER.map((line) => `// ${line}`),
        "// The string overload, which returns UnknownRawcode for a Rawcode not listed here, is",
        "// reforged-types': list `reforged-types/3.0.0` in `types` next to `reforged-builtins/3.0.0`.",
        "",
        "// Units: the 4 Built-in units.",
        "",
        "/**",
        " * Paladin (`Hpal`), a Built-in unit of Patch 3.0.0, race human.",
        " *",
        " * Its constant is `Units.Paladin_Hpal`, from `reforged-builtins/units`.",
        " */",
        'declare function FourCC(id: "Hpal"): Rawcode<"unit">;',
        "",
        "/**",
        " * Footman (`hfoo`), a Built-in unit of Patch 3.0.0, race human.",
        " *",
        " * Its constant is `Units.Footman_hfoo`, from `reforged-builtins/units`.",
        " */",
        'declare function FourCC(id: "hfoo"): Rawcode<"unit">;',
        "",
        "/**",
        " * `hnon`, with no enUS name, a Built-in unit of Patch 3.0.0.",
        " *",
        " * Its constant is `Units.Unnamed_hnon`, from `reforged-builtins/units`.",
        " */",
        'declare function FourCC(id: "hnon"): Rawcode<"unit">;',
        "",
        "/**",
        " * Odd \\<one\\> \\@ \\{here\\} *\\/ (`nodd`), a Built-in unit of Patch 3.0.0.",
        " *",
        " * Its constant is `Units.OddOneHere_nodd`, from `reforged-builtins/units`.",
        " */",
        'declare function FourCC(id: "nodd"): Rawcode<"unit">;',
        "",
      ].join("\n"),
    );
  });

  it("declare the constants as one object of readonly Rawcode<kind> members, with the overloads' TSDoc", () => {
    expect(files.get("3.0.0/units.d.ts")).toBe(
      [
        ...BANNER.map((line) => `// ${line}`),
        "",
        "/**",
        ' * The Built-in units of Patch 3.0.0, each a `Rawcode<"unit">` named by its enUS name and its Rawcode.',
        " * Each holds the integer `FourCC` returns for its Rawcode.",
        " */",
        "export declare const Units: {",
        "  /**",
        "   * Footman (`hfoo`), a Built-in unit of Patch 3.0.0, race human.",
        "   */",
        '  readonly Footman_hfoo: Rawcode<"unit">;',
        "  /**",
        "   * Odd \\<one\\> \\@ \\{here\\} *\\/ (`nodd`), a Built-in unit of Patch 3.0.0.",
        "   */",
        '  readonly OddOneHere_nodd: Rawcode<"unit">;',
        "  /**",
        "   * Paladin (`Hpal`), a Built-in unit of Patch 3.0.0, race human.",
        "   */",
        '  readonly Paladin_Hpal: Rawcode<"unit">;',
        "  /**",
        "   * `hnon`, with no enUS name, a Built-in unit of Patch 3.0.0.",
        "   */",
        '  readonly Unnamed_hnon: Rawcode<"unit">;',
        "};",
        "",
      ].join("\n"),
    );
  });

  it("return the same object from Lua, as a table of the integers FourCC gives", () => {
    expect(files.get("3.0.0/units.lua")).toBe(
      [
        ...BANNER.map((line) => `-- ${line}`),
        "",
        "local Units = {",
        "  Footman_hfoo = 1751543663,",
        "  OddOneHere_nodd = 1852793956,",
        "  Paladin_Hpal = 1215324524,",
        "  Unnamed_hnon = 1752067950,",
        "}",
        "",
        "return { Units = Units }",
        "",
      ].join("\n"),
    );
  });

  it("hold no const enum", () => {
    for (const text of files.values()) expect(text).not.toMatch(/\benum\b/);
  });

  it("give each Rawcode the big-endian value of its four bytes", () => {
    expect(rawcodeValue("hfoo")).toBe(0x68666f6f);
    expect(rawcodeValue("Hpal")).toBe(Buffer.from("Hpal").readUInt32BE());
    expect(rawcodeValue("zzzz")).toBe(Buffer.from("zzzz").readUInt32BE());
  });

  it("say which Game data sets hold an object, only when not every one does", () => {
    const index: BuiltinsIndex = {
      ...INDEX,
      gameDataSets: [
        { id: "default", label: "Default" },
        { id: "custom", label: "Custom" },
        { id: "melee", label: "Melee" },
      ],
      objects: {
        hfoo: {
          kind: "unit",
          name: "Footman",
          race: "human",
          sets: ["default", "custom", "melee"],
          constant: "Footman_hfoo",
        },
        sfoo: {
          kind: "unit",
          name: "Footman",
          race: "human",
          sets: ["default", "custom"],
          constant: "Footman_sfoo",
        },
      },
    };
    const declarations = emitArtefacts(index).get("3.0.0/units.d.ts") ?? "";

    expect(declarations).toContain(
      [
        "  /**",
        "   * Footman (`hfoo`), a Built-in unit of Patch 3.0.0, race human.",
        "   */",
      ].join("\n"),
    );
    expect(declarations).toContain(
      [
        "  /**",
        "   * Footman (`sfoo`), a Built-in unit of Patch 3.0.0, race human.",
        "   *",
        "   * In the Default and Custom Game data sets. Not in the Melee Game data set.",
        "   */",
      ].join("\n"),
    );
  });
});

/** A package root holding `index` and what it emits, with a valid manifest. */
async function packageWith(index: BuiltinsIndex = INDEX): Promise<string> {
  const root = await tempDir("check");
  await mkdir(join(root, index.gameVersion));
  await writeFile(
    join(root, index.gameVersion, "index.json"),
    serializeIndex(index),
  );
  await writeFile(
    join(root, index.gameVersion, "provenance.json"),
    serializeProvenance({
      build: index.build,
      buildConfig: "00".repeat(16),
      inputs: [
        {
          path: "War3.w3mod:Units/UnitData.slk",
          contentKey: "11".repeat(16),
          sha256: "22".repeat(32),
          size: 1,
        },
      ],
    }),
  );
  for (const [path, text] of emitArtefacts(index)) {
    await writeFile(join(root, ...path.split("/")), text);
  }
  await writeFile(
    join(root, "package.json"),
    JSON.stringify({
      name: "reforged-builtins",
      exports: {
        "./3.0.0": { types: "./3.0.0.d.ts" },
        "./3.0.0/index.json": "./3.0.0/index.json",
        "./units": {
          types: "./3.0.0/units.d.ts",
          tstl: "./3.0.0/units",
        },
        "./package.json": "./package.json",
      },
    }),
  );
  return root;
}

async function check(root: string, args: string[] = []) {
  let stdout = "";
  let stderr = "";
  const status = await main(
    [...args, "--root", root],
    { stdout: (text) => (stdout += text), stderr: (text) => (stderr += text) },
    root,
  );
  return { status, stdout, stderr };
}

describe("builtins:check", () => {
  it("passes on artefacts emitted from their index", async () => {
    const root = await packageWith();

    expect(await check(root)).toEqual({
      status: 0,
      stdout:
        "Built-in objects match: 4 files of Game version 3.0.0 are exactly what their index emits.\n",
      stderr: "",
    });
  });

  it("fails on a hand-edited artefact, naming it, and passes once it is emitted again", async () => {
    const root = await packageWith();
    const lua = join(root, "3.0.0", "units.lua");
    await writeFile(
      lua,
      (await readFile(lua, "utf8")).replace("1751543663", "1751543664"),
    );
    const declarations = join(root, "3.0.0.d.ts");
    await writeFile(
      declarations,
      (await readFile(declarations, "utf8")) + "\n",
    );

    const failed = await check(root);

    expect(failed.status).toBe(1);
    expect(failed.stdout).toBe("");
    expect(failed.stderr).toBe(
      "Built-in objects drift: 2 problems. Every artefact is emitted from its Game version's index, which pnpm builtins:generate extracts from the game's install; never edit one by hand.\n\n" +
        "- [ ] 3.0.0.d.ts: differs from the file emitted from 3.0.0/index.json\n" +
        "- [ ] 3.0.0/units.lua: differs from the file emitted from 3.0.0/index.json\n",
    );

    const rewritten = await check(root, ["--write"]);

    expect(rewritten.status).toBe(0);
    expect(rewritten.stdout).toBe(
      "Wrote 3.0.0.d.ts.\nWrote 3.0.0/units.d.ts.\nWrote 3.0.0/units.lua.\n" +
        "Built-in objects match: 4 files of Game version 3.0.0 are exactly what their index emits.\n",
    );
    expect((await check(root)).status).toBe(0);
  });

  it("fails on an artefact missing, or one no index emits", async () => {
    const root = await packageWith();
    await rm(join(root, "3.0.0", "units.d.ts"));
    await writeFile(join(root, "3.0.0", "items.lua"), "return {}\n");
    await writeFile(join(root, "2.0.0.d.ts"), "\n");

    const { status, stderr } = await check(root);

    expect(status).toBe(1);
    expect(stderr).toContain(
      "- [ ] 3.0.0/units.d.ts: emitted but not committed\n" +
        "- [ ] 3.0.0/items.lua: committed but not emitted\n" +
        "- [ ] 2.0.0.d.ts: committed but not emitted\n",
    );
  });

  it("fails on a Game version without its provenance", async () => {
    const root = await packageWith();
    await rm(join(root, "3.0.0", "provenance.json"));

    const { status, stderr } = await check(root);

    expect(status).toBe(1);
    expect(stderr).toContain(
      "- [ ] 3.0.0/provenance.json: missing; every Game version keeps the provenance of its index\n",
    );
  });

  it("fails on an index not written as the generator writes it", async () => {
    const root = await packageWith();
    await writeFile(
      join(root, "3.0.0", "index.json"),
      JSON.stringify(INDEX, null, 2),
    );

    const { status, stderr } = await check(root);

    expect(status).toBe(1);
    expect(stderr).toContain(
      "- [ ] 3.0.0/index.json: not written as the generator writes it\n",
    );
  });

  it("fails on exports that do not send the kind entry points to the newest Game version", async () => {
    const root = await packageWith();
    const manifest = join(root, "package.json");
    await writeFile(
      manifest,
      (await readFile(manifest, "utf8")).replace(
        '"tstl":"./3.0.0/units"',
        '"tstl":"./2.0.0/units"',
      ),
    );

    const { status, stderr } = await check(root);

    expect(status).toBe(1);
    expect(stderr).toContain("- [ ] package.json: its exports are ");
  });

  it("fails on a root with no Game version", async () => {
    const root = await tempDir("check");
    await writeFile(join(root, "package.json"), "{}");

    const { status, stderr } = await check(root);

    expect(status).toBe(1);
    expect(stderr).toContain(`- [ ] ${root} holds no Game version folder.\n`);
  });

  it("refuses an unknown argument", async () => {
    const { status, stderr } = await check(await packageWith(), ["--fix"]);

    expect(status).toBe(2);
    expect(stderr).toBe("Usage: builtins:check [--write] [--root <folder>]\n");
  });
});

describe("an index's shape", () => {
  it("is valid as the generator writes it", () => {
    expect(validateIndex(INDEX, "3.0.0")).toEqual([]);
  });

  it("names each field that does not hold", () => {
    expect(
      validateIndex(
        {
          format: 2,
          build: "3.0.1.1",
          gameVersion: "3.0.1",
          gameDataSets: [{ id: "default", label: "Default" }],
          extra: true,
          objects: {
            hfo: {
              kind: "hero",
              sets: ["melee"],
              constant: "Footman_hfoo",
              tooltip: "x",
            },
            hfoo: { kind: "unit", sets: ["default"], constant: "A_hfoo" },
            Hfoo: { kind: "unit", sets: ["default"], constant: "A_hfoo" },
          },
        },
        "3.0.0",
      ),
    ).toEqual([
      "the index: unknown key extra",
      "format 2 is not 1",
      "build 3.0.1.1 is not of Game version 3.0.0",
      'gameVersion "3.0.1" is not its folder\'s, 3.0.0',
      "objects.hfo: not a Rawcode of four characters of [A-Za-z0-9]",
      "objects.hfo: unknown key tooltip",
      'objects.hfo: kind "hero" is not an Object kind',
      'objects.hfo: sets ["melee"] are not ids of gameDataSets, each once',
      'objects.hfo: constant "Footman_hfoo" is not an identifier ending in _hfo',
      'objects.Hfoo: constant "A_hfoo" is not an identifier ending in _Hfoo',
    ]);
  });
});
