/**
 * The artefacts emitted from the model (#509): from the JSON index of a Game
 * version, its `FourCC` overloads' entry and, per Object kind, the constants'
 * declarations and their Lua module. Nothing here reads the game: the check
 * emits them again from the committed index and compares.
 */
import {
  byCodePoint,
  type BuiltinsIndex,
  type IndexEntry,
  type ObjectKind,
} from "./model.js";

/** The package's name, as a Map project imports it. */
export const PACKAGE_NAME = "reforged-builtins";

/** The command that writes the artefacts, named by every banner. */
export const REGENERATE_COMMAND = "pnpm builtins:generate";

/** The command that compares them with the committed index, named by every banner. */
export const CHECK_COMMAND = "pnpm builtins:check";

/** A kind's constants: the object's name and the entry point's subpath. */
interface KindConstants {
  /** The exported object, the kind's plural: `Units`. */
  object: string;
  /** The entry point's subpath and the files' base name: `units`. */
  entry: string;
}

/** The constants of each Object kind, in the order the overloads list them. */
export const KIND_CONSTANTS: Readonly<Record<ObjectKind, KindConstants>> = {
  unit: { object: "Units", entry: "units" },
  item: { object: "Items", entry: "items" },
  ability: { object: "Abilities", entry: "abilities" },
  buff: { object: "Buffs", entry: "buffs" },
  destructable: { object: "Destructables", entry: "destructables" },
  doodad: { object: "Doodads", entry: "doodads" },
  upgrade: { object: "Upgrades", entry: "upgrades" },
};

const KINDS = Object.keys(KIND_CONSTANTS) as ObjectKind[];

/** The overloads' entry of a Game version, selected in `types`: `3.0.0.d.ts`. */
export const overloadsPath = (gameVersion: string): string =>
  `${gameVersion}.d.ts`;

/** The constants' declarations of a kind: `3.0.0/units.d.ts`. */
export const constantsPath = (gameVersion: string, kind: ObjectKind): string =>
  `${gameVersion}/${KIND_CONSTANTS[kind].entry}.d.ts`;

/** The constants' Lua module of a kind, as a resolver names it: `3.0.0/units`. */
export const luaModule = (gameVersion: string, kind: ObjectKind): string =>
  `${gameVersion}/${KIND_CONSTANTS[kind].entry}`;

/** The constants' Lua module's file: `3.0.0/units.lua`. */
export const luaPath = (gameVersion: string, kind: ObjectKind): string =>
  `${luaModule(gameVersion, kind)}.lua`;

/** The kinds the index holds an object of, in the order of `KIND_CONSTANTS`. */
export function kindsOf(index: BuiltinsIndex): ObjectKind[] {
  const present = new Set(Object.values(index.objects).map((e) => e.kind));
  return KINDS.filter((kind) => present.has(kind));
}

/**
 * Every artefact of the index, by its `/`-separated path under the package
 * root: the overloads' entry, then each kind's declarations and Lua module.
 */
export function emit(index: BuiltinsIndex): Map<string, string> {
  const files = new Map<string, string>();
  files.set(overloadsPath(index.gameVersion), emitOverloads(index));
  for (const kind of kindsOf(index)) {
    files.set(
      constantsPath(index.gameVersion, kind),
      emitConstants(index, kind),
    );
    files.set(luaPath(index.gameVersion, kind), emitLua(index, kind));
  }
  return files;
}

/** The banner of every generated file, one line per entry, without the comment marker. */
function banner(index: BuiltinsIndex): string[] {
  return [
    `Generated by ${PACKAGE_NAME} from the Built-in objects of Game version ${index.gameVersion} (${index.gameVersion}/index.json).`,
    "Derived identifiers only: Rawcodes, Object kinds, races, enUS names and Game data sets.",
    "Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.",
    "The names and Rawcodes are derived from the game's data and are not licensed by this package.",
    `Never edited by hand: \`${REGENERATE_COMMAND}\` writes it and \`${CHECK_COMMAND}\` compares it.`,
  ];
}

/** The objects of one kind, by Rawcode in code-point order. */
function objectsOf(
  index: BuiltinsIndex,
  kind: ObjectKind,
): [string, IndexEntry][] {
  return Object.entries(index.objects)
    .filter(([, entry]) => entry.kind === kind)
    .sort(([a], [b]) => byCodePoint(a, b));
}

function emitOverloads(index: BuiltinsIndex): string {
  const lines = [
    "/** @noSelfInFile */",
    ...banner(index).map((line) => `// ${line}`),
    "// The string overload, which returns UnknownRawcode, is reforged-types'.",
  ];
  for (const kind of kindsOf(index)) {
    const { object } = KIND_CONSTANTS[kind];
    lines.push("", `// ${object}.`);
    for (const [rawcode, entry] of objectsOf(index, kind)) {
      lines.push(
        "",
        ...docComment("", [
          ...describeObject(index, rawcode, entry),
          "",
          `Its constant is \`${object}.${entry.constant}\`, from \`${PACKAGE_NAME}/${KIND_CONSTANTS[kind].entry}\`.`,
        ]),
        `declare function FourCC(id: ${JSON.stringify(rawcode)}): Rawcode<${JSON.stringify(kind)}>;`,
      );
    }
  }
  return lines.join("\n") + "\n";
}

function emitConstants(index: BuiltinsIndex, kind: ObjectKind): string {
  const { object } = KIND_CONSTANTS[kind];
  const lines = [
    ...banner(index).map((line) => `// ${line}`),
    "",
    ...docComment("", [
      `The Built-in ${KIND_CONSTANTS[kind].entry} of Patch ${index.gameVersion}, each named by its enUS name and Rawcode, such as \`${object}.${firstConstant(index, kind)}\`.`,
    ]),
    `export declare const ${object}: {`,
  ];
  objectsOf(index, kind).forEach(([rawcode, entry], i) => {
    if (i > 0) lines.push("");
    lines.push(
      ...docComment("  ", describeObject(index, rawcode, entry)),
      `  readonly ${entry.constant}: Rawcode<${JSON.stringify(kind)}>;`,
    );
  });
  lines.push("};");
  return lines.join("\n") + "\n";
}

function emitLua(index: BuiltinsIndex, kind: ObjectKind): string {
  const lines = [
    ...banner(index).map((line) => `-- ${line}`),
    "-- Each value is the big-endian integer of the Rawcode's four bytes, what FourCC returns.",
    "return {",
    `  ${KIND_CONSTANTS[kind].object} = {`,
    ...objectsOf(index, kind).map(
      ([rawcode, entry]) =>
        `    ${entry.constant} = ${String(rawcodeValue(rawcode))},`,
    ),
    "  },",
    "}",
  ];
  return lines.join("\n") + "\n";
}

function firstConstant(index: BuiltinsIndex, kind: ObjectKind): string {
  const first = objectsOf(index, kind).at(0);
  return first === undefined ? "" : first[1].constant;
}

/** The integer `FourCC` returns for a Rawcode: its four bytes, big-endian. */
export function rawcodeValue(rawcode: string): number {
  return Buffer.from(rawcode, "latin1").readUInt32BE(0);
}

/**
 * The TSDoc an object's overload and its constant share: its name and
 * Rawcode, the kind and Game version, the race, and the Game data sets when
 * not every one holds it. Never tooltip text.
 */
function describeObject(
  index: BuiltinsIndex,
  rawcode: string,
  entry: IndexEntry,
): string[] {
  const named =
    entry.name === undefined
      ? `\`${rawcode}\`, unnamed`
      : `${escape(entry.name)} (\`${rawcode}\`)`;
  const race = entry.race === undefined ? "" : `, race ${entry.race}`;
  const lines = [
    `${named}, a Built-in ${entry.kind} of Patch ${index.gameVersion}${race}.`,
  ];
  const holding = index.gameDataSets.filter((set) =>
    entry.sets.includes(set.id),
  );
  const missing = index.gameDataSets.filter(
    (set) => !entry.sets.includes(set.id),
  );
  if (missing.length > 0) {
    const sets = (labels: string[]) =>
      `the ${list(labels)} Game data set${labels.length === 1 ? "" : "s"}`;
    lines.push(
      "",
      (holding.length > 0
        ? `In ${sets(holding.map((set) => set.label))}. `
        : "") + `Not in ${sets(missing.map((set) => set.label))}.`,
    );
  }
  return lines;
}

/** A kind with its article: `a unit`, `an ability`. */
export function withArticle(kind: ObjectKind): string {
  return `${kind === "ability" || kind === "item" || kind === "upgrade" ? "an" : "a"} ${kind}`;
}

/** `A`, `A and B`, `A, B and C`. */
export function list(items: string[]): string {
  return items.length < 2
    ? items.join("")
    : `${items.slice(0, -1).join(", ")} and ${items.at(-1) ?? ""}`;
}

/** A name as TSDoc text: TSDoc's special characters escaped, and no comment end. */
function escape(text: string): string {
  return text.replace(/[\\@{}<>`]/g, "\\$&").replace(/\*\//g, "*\\/");
}

/** A doc comment of `lines`, indented by `indent`. */
function docComment(indent: string, lines: string[]): string[] {
  return [
    `${indent}/**`,
    ...lines.map((line) =>
      line === "" ? `${indent} *` : `${indent} * ${line}`,
    ),
    `${indent} */`,
  ];
}
