/**
 * The artefacts emitted from the model (#509): from the JSON index of one
 * Game version, the `FourCC` overloads' entry and, per Object kind, the
 * constants' declarations and Lua module. No game is needed: the index is
 * the committed model, and `builtins:check` emits these again from it.
 *
 * An object's TSDoc is shared by its overload and its constant. It names the
 * Game version and never the Build, so a new Build of the same Game version
 * changes no line that did not change in the game.
 */
import {
  byCodePoint,
  type BuiltinsIndex,
  type IndexEntry,
  type ObjectKind,
} from "./model.js";

/** What a kind's constants are emitted as. */
export interface KindArtefacts {
  kind: ObjectKind;
  /** The exported object of its constants, `Units`. */
  constants: string;
  /** The file stem under the Game version's folder and the entry point's subpath, `units`. */
  entry: string;
}

/** The Object kinds, in the order the overloads group them. */
export const KIND_ARTEFACTS: readonly KindArtefacts[] = [
  { kind: "unit", constants: "Units", entry: "units" },
  { kind: "item", constants: "Items", entry: "items" },
  { kind: "ability", constants: "Abilities", entry: "abilities" },
  { kind: "buff", constants: "Buffs", entry: "buffs" },
  { kind: "destructable", constants: "Destructables", entry: "destructables" },
  { kind: "doodad", constants: "Doodads", entry: "doodads" },
  { kind: "upgrade", constants: "Upgrades", entry: "upgrades" },
];

/** The package's name, as a Map project imports it. */
export const PACKAGE_NAME = "reforged-builtins";

/** The command that writes every artefact again, from the game's install. */
export const REGENERATE_COMMAND = "pnpm builtins:generate";

/** The paths of a Game version's artefacts under the package root, `/`-separated. */
export const artefactPaths = {
  index: (gameVersion: string) => `${gameVersion}/index.json`,
  provenance: (gameVersion: string) => `${gameVersion}/provenance.json`,
  overloads: (gameVersion: string) => `${gameVersion}.d.ts`,
  declarations: (gameVersion: string, kind: KindArtefacts) =>
    `${gameVersion}/${kind.entry}.d.ts`,
  lua: (gameVersion: string, kind: KindArtefacts) =>
    `${gameVersion}/${kind.entry}.lua`,
};

/** The entry point of a kind's constants, `reforged-builtins/units`. */
export const entryPoint = (kind: KindArtefacts): string =>
  `${PACKAGE_NAME}/${kind.entry}`;

/**
 * The emitted files of `index`, by `/`-separated path under the package
 * root: the overloads' entry, and the declarations and Lua module of each
 * kind the index holds. The index itself is not among them.
 */
export function emitArtefacts(index: BuiltinsIndex): Map<string, string> {
  const files = new Map<string, string>();
  const kinds = kindsOf(index);
  files.set(
    artefactPaths.overloads(index.gameVersion),
    overloads(index, kinds),
  );
  for (const { kind, objects } of kinds) {
    files.set(
      artefactPaths.declarations(index.gameVersion, kind),
      declarations(index, kind, objects),
    );
    files.set(
      artefactPaths.lua(index.gameVersion, kind),
      luaModule(index, kind, objects),
    );
  }
  return files;
}

/** One Built-in object: its Rawcode and its entry. */
interface BuiltinObject {
  rawcode: string;
  entry: IndexEntry;
}

/** The kinds `index` holds objects of, each with its objects by Rawcode. */
function kindsOf(
  index: BuiltinsIndex,
): { kind: KindArtefacts; objects: BuiltinObject[] }[] {
  const objects = Object.keys(index.objects)
    .sort(byCodePoint)
    .map((rawcode) => ({ rawcode, entry: index.objects[rawcode] }));
  return KIND_ARTEFACTS.map((kind) => ({
    kind,
    objects: objects.filter((object) => object.entry.kind === kind.kind),
  })).filter(({ objects }) => objects.length > 0);
}

/**
 * The banner of a generated file, one comment line per element: who
 * generated it from what, what it holds, the notice and the rule.
 */
export function banner(gameVersion: string): string[] {
  return [
    `Generated by ${PACKAGE_NAME} from the Built-in objects of Game version ${gameVersion} (${gameVersion}/index.json).`,
    "Derived identifiers only: Rawcodes, Object kinds, races and enUS names; no tooltip, number or icon.",
    "Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.",
    `Never edited by hand: \`${REGENERATE_COMMAND}\` writes it, and \`pnpm builtins:check\` fails on any difference.`,
  ];
}

/** The `FourCC` overloads' entry: one ambient overload per Rawcode, grouped by kind. */
function overloads(
  index: BuiltinsIndex,
  kinds: readonly { kind: KindArtefacts; objects: BuiltinObject[] }[],
): string {
  const lines = [
    // The overloads are functions: typescript-to-lua must call FourCC
    // without a context argument, as the Typings' string overload does.
    "/** @noSelfInFile */",
    ...banner(index.gameVersion).map((line) => `// ${line}`),
    "// The string overload, which returns UnknownRawcode for a Rawcode not listed here, is",
    `// reforged-types': list \`reforged-types/${index.gameVersion}\` in \`types\` next to \`${PACKAGE_NAME}/${index.gameVersion}\`.`,
  ];
  for (const { kind, objects } of kinds) {
    lines.push(
      "",
      `// ${kind.constants}: the ${String(objects.length)} Built-in ${plural(kind.kind)}.`,
    );
    for (const object of objects) {
      lines.push(
        "",
        ...docComment(
          [
            ...objectDoc(index, object),
            "",
            `Its constant is \`${kind.constants}.${object.entry.constant}\`, from \`${entryPoint(kind)}\`.`,
          ],
          "",
        ),
        `declare function FourCC(id: ${JSON.stringify(object.rawcode)}): Rawcode<${JSON.stringify(kind.kind)}>;`,
      );
    }
  }
  return lines.join("\n") + "\n";
}

/** A kind's constants' declarations: one exported object of readonly members. */
function declarations(
  index: BuiltinsIndex,
  kind: KindArtefacts,
  objects: readonly BuiltinObject[],
): string {
  const lines = [
    ...banner(index.gameVersion).map((line) => `// ${line}`),
    "",
    ...docComment(
      [
        `The Built-in ${plural(kind.kind)} of Patch ${index.gameVersion}, each a \`Rawcode<${JSON.stringify(kind.kind)}>\` named by its enUS name and its Rawcode.`,
        `Each holds the integer \`FourCC\` returns for its Rawcode.`,
      ],
      "",
    ),
    `export declare const ${kind.constants}: {`,
  ];
  for (const object of byConstant(objects)) {
    lines.push(
      ...docComment(objectDoc(index, object), "  "),
      `  readonly ${object.entry.constant}: Rawcode<${JSON.stringify(kind.kind)}>;`,
    );
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}

/** A kind's Lua module: the same object, as a table of integer literals. */
function luaModule(
  index: BuiltinsIndex,
  kind: KindArtefacts,
  objects: readonly BuiltinObject[],
): string {
  return [
    ...banner(index.gameVersion).map((line) => `-- ${line}`),
    "",
    `local ${kind.constants} = {`,
    ...byConstant(objects).map(
      (object) =>
        `  ${object.entry.constant} = ${String(rawcodeValue(object.rawcode))},`,
    ),
    "}",
    "",
    `return { ${kind.constants} = ${kind.constants} }`,
    "",
  ].join("\n");
}

/** The objects by constant name, in code-point order. */
function byConstant(objects: readonly BuiltinObject[]): BuiltinObject[] {
  return [...objects].sort((a, b) =>
    byCodePoint(a.entry.constant, b.entry.constant),
  );
}

/**
 * The integer `FourCC` returns for `rawcode`: the big-endian value of its
 * four bytes. A Rawcode's characters are ASCII letters and digits, so it
 * fits in 31 bits.
 */
export function rawcodeValue(rawcode: string): number {
  let value = 0;
  for (let i = 0; i < 4; i++) value = value * 256 + rawcode.charCodeAt(i);
  return value;
}

/**
 * The TSDoc paragraphs of an object, shared by its overload and its
 * constant: its name and Rawcode, its kind and Game version, its race, and
 * the Game data sets that hold it when not every one does.
 */
export function objectDoc(
  index: BuiltinsIndex,
  { rawcode, entry }: BuiltinObject,
): string[] {
  const subject =
    entry.name === undefined
      ? `\`${rawcode}\`, with no enUS name,`
      : `${escapeDoc(entry.name)} (\`${rawcode}\`),`;
  const race = entry.race === undefined ? "" : `, race ${entry.race}`;
  const lines = [
    `${subject} a Built-in ${entry.kind} of Patch ${index.gameVersion}${race}.`,
  ];
  const sets = setsLine(index, entry);
  if (sets !== undefined) lines.push("", sets);
  return lines;
}

/**
 * Nothing when every Game data set holds the object; else the sets that
 * hold it and those that do not: "In the Default and Custom Game data sets.
 * Not in the Melee Game data set."
 */
function setsLine(index: BuiltinsIndex, entry: IndexEntry): string | undefined {
  const holding = index.gameDataSets.filter((set) =>
    entry.sets.includes(set.id),
  );
  const missing = index.gameDataSets.filter(
    (set) => !entry.sets.includes(set.id),
  );
  if (missing.length === 0) return undefined;
  const phrase = (sets: readonly { label: string }[]) =>
    `the ${listOf(sets.map((set) => set.label))} Game data set${sets.length === 1 ? "" : "s"}`;
  const parts = [];
  if (holding.length > 0) parts.push(`In ${phrase(holding)}.`);
  parts.push(`Not in ${phrase(missing)}.`);
  return parts.join(" ");
}

/** "A", "A and B", "A, B and C". */
function listOf(items: readonly string[]): string {
  return items.length <= 1
    ? items.join("")
    : `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

function plural(kind: ObjectKind): string {
  return kind === "ability" ? "abilities" : `${kind}s`;
}

/** A doc comment of `paragraphs` (an empty string separates two), at `indent`. */
function docComment(paragraphs: readonly string[], indent: string): string[] {
  return [
    `${indent}/**`,
    ...paragraphs.map((line) =>
      line === "" ? `${indent} *` : `${indent} * ${line}`,
    ),
    `${indent} */`,
  ];
}

/**
 * The game's text made safe inside a TSDoc comment: the characters TSDoc
 * gives a meaning to are escaped with a backslash, and a comment's end
 * cannot appear.
 */
export function escapeDoc(text: string): string {
  return text.replace(/[\\@{}<>`]/g, "\\$&").replace(/\*\//g, "*\\/");
}
