/**
 * Rendering the compatibility matrix: the JSON file and the two Markdown
 * tables made from it, the docs site's partial and the Template's README
 * fragment. The same matrix always renders to the same bytes.
 */
import {
  canonicalRow,
  FRAGMENT_FILE,
  MATRIX_FILE,
  MATRIX_FORMAT,
  SITE_TABLE_FILE,
  type Matrix,
  type MatrixRow,
} from "./matrix-model.js";
import {
  HARNESS_PACKAGE,
  LIBRARY_PACKAGE,
  PLUGIN_PACKAGE,
  TYPINGS_PACKAGE,
} from "./packages.js";

/** Escapes what Markdown and MDX would read as markup in a table cell. */
function cell(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("|", "\\|")
    .replaceAll("<", "&lt;")
    .replaceAll("{", "&#123;")
    .replaceAll("}", "&#125;");
}

const HEADERS = [
  LIBRARY_PACKAGE,
  TYPINGS_PACKAGE,
  HARNESS_PACKAGE,
  PLUGIN_PACKAGE,
  "Patch",
  "TypeScript",
  "typescript-to-lua",
  "lua-types",
  "Node",
  "3.0.0 systems",
  "Cut",
  "Docs",
];

/** The table, newest release first; columns padded to their widest cell. */
function table(rows: readonly MatrixRow[]): string {
  const body = [...rows]
    .reverse()
    .map((row) => [
      row.library,
      row.typings,
      row.harness,
      row.plugin,
      row.patch,
      row.typescript,
      row.typescriptToLua,
      row.luaTypes,
      `${row.node} or later`,
      row.systems.length === 0 ? "none" : row.systems.join(", "),
      row.cutDate,
      `[${row.docs.slice(row.docs.lastIndexOf("/") + 1)}](${row.docs})`,
    ]);
  const lines = [HEADERS, ...body].map((cells) => cells.map(cell));
  const widths = HEADERS.map((_, column) =>
    Math.max(3, ...lines.map((cells) => (cells[column] ?? "").length)),
  );
  const line = (cells: readonly string[]) =>
    `| ${cells.map((text, column) => text + " ".repeat((widths[column] ?? 0) - text.length)).join(" | ")} |\n`;
  const [header = [], ...others] = lines;
  return (
    line(header) +
    line(widths.map((width) => "-".repeat(width))) +
    others.map(line).join("")
  );
}

const EMPTY =
  "No stable release yet. During the build phase the packages are published as `1.0.0-alpha.N` under the `next` dist-tag.\n";

const GENERATED = `Generated by \`pnpm release:matrix\` from ${MATRIX_FILE}; do not edit.`;

/** The three generated files of a matrix, by path. */
export function render(matrix: Matrix): Map<string, string> {
  const rows = matrix.rows.map(canonicalRow);
  const content = rows.length === 0 ? EMPTY : table(rows);
  return new Map([
    [
      MATRIX_FILE,
      `${JSON.stringify({ format: MATRIX_FORMAT, rows }, null, 2)}\n`,
    ],
    [FRAGMENT_FILE, `<!-- ${GENERATED} -->\n\n${content}`],
    [SITE_TABLE_FILE, `{/* ${GENERATED} */}\n\n${content}`],
  ]);
}
