import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join, posix } from "node:path";
import { fileURLToPath } from "node:url";
import {
  flattenDiagnosticMessageText,
  parseConfigFileTextToJson,
} from "typescript";
import { describe, expect, it } from "vitest";

// The repository root, two folders up from this file.
const root = fileURLToPath(new URL("../../", import.meta.url));

function read(path: string): string {
  return readFileSync(join(root, path), "utf8");
}

// The VS Code files are JSON with comments; TypeScript's parser for its own
// JSONC config files reads them.
function readJsonc(path: string): unknown {
  const result = parseConfigFileTextToJson(path, read(path));
  if (result.error) {
    const message = flattenDiagnosticMessageText(
      result.error.messageText,
      "\n",
    );
    throw new Error(`${path}: ${message}`);
  }
  return result.config as unknown;
}

describe(".vscode/extensions.json", () => {
  it("recommends exactly the ESLint, Prettier and vitest explorer extensions", () => {
    const { recommendations } = readJsonc(".vscode/extensions.json") as {
      recommendations?: string[];
    };
    expect(
      [...(recommendations ?? [])].sort(),
      "the recommended extensions in .vscode/extensions.json",
    ).toEqual([
      "dbaeumer.vscode-eslint",
      "esbenp.prettier-vscode",
      "vitest.explorer",
    ]);
  });
});

describe(".vscode/settings.json", () => {
  // The oracle, independent of the glob: a declaration file is generated when
  // it opens with the generator's header, and a data file when it is named as
  // in packages/reforged-types/src/artefacts.ts and sits next to a generated
  // declaration file. Everything else in the package is hand-written: the Lua
  // runtime declarations, the Overlay, the sources, the tests and their
  // fixtures, the package's own manifests.
  const typingsPackage = "packages/reforged-types";
  const dataFiles = new Set(["async-natives.json", "manifest.json"]);

  function generatedFiles(files: readonly string[]): Set<string> {
    const declarations = files.filter(
      (file) =>
        file.endsWith(".d.ts") &&
        /^(?:.*\n){0,3}\/\/ Generated by reforged-types\b/.test(read(file)),
    );
    const folders = new Set(declarations.map((file) => posix.dirname(file)));
    const data = files.filter(
      (file) =>
        dataFiles.has(posix.basename(file)) && folders.has(posix.dirname(file)),
    );
    return new Set([...declarations, ...data]);
  }

  it("makes read-only every generated file of reforged-types and no hand-written one", () => {
    const { "files.readonlyInclude": include = {} } = readJsonc(
      ".vscode/settings.json",
    ) as { "files.readonlyInclude"?: Record<string, boolean> };
    const globs = Object.keys(include).filter((glob) => include[glob]);

    // The package's files as the editor sees them: committed or new, never
    // ignored (build output, node_modules).
    const files = execFileSync(
      "git",
      [
        "ls-files",
        "--cached",
        "--others",
        "--exclude-standard",
        "-z",
        typingsPackage,
      ],
      { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
    )
      .split("\0")
      .filter((file) => file !== "");
    const generated = generatedFiles(files);
    expect(
      [...generated].map((file) => posix.basename(file)),
      `the generated files of ${typingsPackage}: an entry file and a data file at least`,
    ).toEqual(
      expect.arrayContaining([
        expect.stringMatching(/^\d+\.\d+\.\d+\.d\.ts$/),
        "async-natives.json",
      ]),
    );

    const problems = files.flatMap((file) => {
      const readOnly = globs.some((glob) => posix.matchesGlob(file, glob));
      if (generated.has(file) && !readOnly) {
        return [`${file} is generated and not read-only`];
      }
      if (!generated.has(file) && readOnly) {
        return [`${file} is hand-written and read-only`];
      }
      return [];
    });
    expect(
      problems,
      "the files of reforged-types against files.readonlyInclude in .vscode/settings.json",
    ).toEqual([]);
  });
});
