import { execFileSync } from "node:child_process";
import { existsSync, globSync } from "node:fs";
import { posix } from "node:path";
import {
  flattenDiagnosticMessageText,
  parseConfigFileTextToJson,
} from "typescript";
import { describe, expect, it } from "vitest";
import { parse } from "yaml";

import { read, root } from "./repository.js";

// The VS Code files are JSON with comments; TypeScript's parser for its own
// JSONC config files reads them.
function readJsonc(path: string): unknown {
  const result = parseConfigFileTextToJson(path, read(path));
  if (result.error) {
    const message = flattenDiagnosticMessageText(
      result.error.messageText,
      "\n",
    );
    throw new Error(`${path}: ${message}`);
  }
  return result.config as unknown;
}

describe(".vscode/extensions.json", () => {
  it("recommends exactly the ESLint, Prettier and vitest explorer extensions", () => {
    const { recommendations } = readJsonc(".vscode/extensions.json") as {
      recommendations?: string[];
    };
    expect(
      [...(recommendations ?? [])].sort(),
      "the recommended extensions in .vscode/extensions.json",
    ).toEqual([
      "dbaeumer.vscode-eslint",
      "esbenp.prettier-vscode",
      "vitest.explorer",
    ]);
  });
});

describe(".vscode/settings.json", () => {
  // The oracle, independent of the glob: a declaration file is generated when
  // it opens with the generator's header, and a data file when it is named as
  // in packages/reforged-types/src/artefacts.ts and sits next to a generated
  // declaration file. Everything else in the package is hand-written: the Lua
  // runtime declarations, the Overlay, the sources, the tests and their
  // fixtures, the package's own manifests.
  const typingsPackage = "packages/reforged-types";
  const dataFiles = new Set(["async-natives.json", "manifest.json"]);

  function generatedFiles(files: readonly string[]): Set<string> {
    const declarations = files.filter(
      (file) =>
        file.endsWith(".d.ts") &&
        /^(?:.*\n){0,3}\/\/ Generated by reforged-types\b/.test(read(file)),
    );
    const folders = new Set(declarations.map((file) => posix.dirname(file)));
    const data = files.filter(
      (file) =>
        dataFiles.has(posix.basename(file)) && folders.has(posix.dirname(file)),
    );
    return new Set([...declarations, ...data]);
  }

  it("makes read-only every generated file of reforged-types and no hand-written one", () => {
    const { "files.readonlyInclude": include = {} } = readJsonc(
      ".vscode/settings.json",
    ) as { "files.readonlyInclude"?: Record<string, boolean> };
    const globs = Object.keys(include).filter((glob) => include[glob]);

    // The package's files as the editor sees them: committed or new, never
    // ignored (build output, node_modules).
    const files = execFileSync(
      "git",
      [
        "ls-files",
        "--cached",
        "--others",
        "--exclude-standard",
        "-z",
        typingsPackage,
      ],
      { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
    )
      .split("\0")
      .filter((file) => file !== "");
    const generated = generatedFiles(files);
    expect(
      [...generated].map((file) => posix.basename(file)),
      `the generated files of ${typingsPackage}: an entry file and a data file at least`,
    ).toEqual(
      expect.arrayContaining([
        expect.stringMatching(/^\d+\.\d+\.\d+\.d\.ts$/),
        "async-natives.json",
      ]),
    );

    const problems = files.flatMap((file) => {
      const readOnly = globs.some((glob) => posix.matchesGlob(file, glob));
      if (generated.has(file) && !readOnly) {
        return [`${file} is generated and not read-only`];
      }
      if (!generated.has(file) && readOnly) {
        return [`${file} is hand-written and read-only`];
      }
      return [];
    });
    expect(
      problems,
      "the files of reforged-types against files.readonlyInclude in .vscode/settings.json",
    ).toEqual([]);
  });
});

describe(".vscode/tasks.json", () => {
  interface ProblemMatcher {
    owner?: string;
    source?: string;
    applyTo?: string;
    fileLocation?: string | string[];
    pattern?: { regexp?: string } & Record<string, unknown>;
  }
  interface Task {
    label: string;
    options?: { env?: Record<string, string> };
    problemMatcher?: string | (string | ProblemMatcher)[];
  }

  const { tasks } = readJsonc(".vscode/tasks.json") as { tasks: Task[] };

  function task(label: string): Task {
    const found = tasks.find((candidate) => candidate.label === label);
    if (!found) throw new Error(`.vscode/tasks.json has no ${label} task`);
    return found;
  }

  // The workspace packages, from pnpm-workspace.yaml, with their scripts.
  const workspacePackages = (() => {
    const { packages: patterns } = parse(read("pnpm-workspace.yaml")) as {
      packages: string[];
    };
    return globSync(patterns, { cwd: root })
      .map((path) => path.replaceAll("\\", "/"))
      .filter((path) => existsSync(posix.join(root, path, "package.json")))
      .map((path) => {
        const { scripts = {} } = JSON.parse(
          read(posix.join(path, "package.json")),
        ) as { scripts?: Record<string, string> };
        return { path, scripts };
      })
      .sort((a, b) => (a.path < b.path ? -1 : 1));
  })();

  // The packages that have a `build` or `typecheck` script: `pnpm
  // --recursive` prints their type errors behind a `<package path>
  // <script>: ` prefix.
  const typedPackages = workspacePackages
    .filter(({ scripts }) => "build" in scripts || "typecheck" in scripts)
    .map(({ path }) => path);

  // The packages whose `build` runs typescript-to-lua as one of its
  // commands, which prints its own diagnostics as `error TSTL: ` (#291).
  const tstlPackages = workspacePackages
    .filter(({ scripts }) =>
      /(?:^|&&|\|\||;)\s*tstl(?:\s|$)/.test(scripts.build ?? ""),
    )
    .map(({ path }) => path);

  // The matcher of tstl's own diagnostics, as each tstl package has one: the
  // prefixed `$tsc` pattern with the code `TSTL`, under its own owner and on
  // every document, since no language server reports these.
  const tstl: ProblemMatcher = {
    owner: "typescript-to-lua",
    source: "tstl",
    applyTo: "allDocuments",
  };

  // `$tsc`, as the TypeScript extension of VS Code contributes it
  // (extensions/typescript-language-features/package.json in
  // microsoft/vscode): the matcher and its pattern.
  const tsc: ProblemMatcher = {
    owner: "typescript",
    source: "ts",
    applyTo: "closedDocuments",
    fileLocation: ["relative", "${cwd}"],
    pattern: {
      regexp:
        "^([^\\s].*)[\\(:](\\d+)[,:](\\d+)(?:\\):\\s+|\\s+-\\s+)(error|warning|info)\\s+TS(\\d+)\\s*:\\s*(.*)$",
      file: 1,
      line: 2,
      column: 3,
      severity: 4,
      code: 5,
      message: 6,
    },
  };
  const tscFields = ["file", "line", "column", "severity", "code", "message"];

  // The variables a fileLocation starts with for the workspace folder: a
  // shell task's `${cwd}` is the workspace folder too.
  const workspaceFolderVariable = /^\$\{(?:workspaceFolder|cwd)\}/;

  interface TscMatcher {
    // `$tsc`, or the folder an inline matcher resolves files from.
    name: string;
    // `typescript` for `$tsc` and a package's type errors,
    // `typescript-to-lua` for its tstl diagnostics.
    owner: string;
    // The folder its fileLocation resolves files from, from the workspace
    // root; "" when it is not relative to the workspace folder.
    folder: string;
    matcher: ProblemMatcher;
  }

  // The matchers of a task that read tsc's or tstl's output, in the task's
  // order: `$tsc` and the matchers the task defines inline.
  function tscMatchers(label: string): TscMatcher[] {
    const { problemMatcher = [] } = task(label);
    return [problemMatcher].flat().flatMap((entry) => {
      if (typeof entry === "string" && entry !== "$tsc") return [];
      const matcher = typeof entry === "string" ? tsc : entry;
      const [kind, location = ""] = [matcher.fileLocation ?? []].flat();
      const folder =
        kind === "relative" && workspaceFolderVariable.test(location)
          ? posix.join(location.replace(workspaceFolderVariable, "."))
          : undefined;
      const name =
        typeof entry === "string"
          ? entry
          : (folder ?? `(fileLocation ${JSON.stringify(entry.fileLocation)})`);
      return [
        { name, owner: matcher.owner ?? "", folder: folder ?? "", matcher },
      ];
    });
  }

  // The matchers a task defines inline under `owner`, one per package.
  function packageMatchers(
    label: string,
    owner: string = tsc.owner ?? "",
  ): TscMatcher[] {
    return tscMatchers(label).filter(
      (matcher) => matcher.name !== "$tsc" && matcher.owner === owner,
    );
  }

  interface Problem {
    // The matcher that read the line: `$tsc` or a package folder.
    matcher: string;
    // That matcher's owner.
    owner: string;
    // The file from the workspace root, as the matcher's fileLocation
    // resolves it.
    path: string;
    fields: Record<string, string | undefined>;
  }

  // The problem a task reports for an output line: VS Code tries the task's
  // matchers in order and keeps the first that matches (tryMatchers in
  // src/vs/workbench/contrib/tasks/common/problemCollectors.ts).
  function problemOf(label: string, line: string): Problem | undefined {
    for (const { name, owner, folder, matcher } of tscMatchers(label)) {
      const { regexp = "", ...groups } = matcher.pattern ?? {};
      const match = new RegExp(regexp).exec(line);
      if (!match) continue;
      const fields = Object.fromEntries(
        tscFields.map((field) => [field, match[groups[field] as number]]),
      );
      return {
        matcher: name,
        owner,
        path: posix.join(folder, fields.file ?? ""),
        fields,
      };
    }
    return undefined;
  }

  it.each(["build", "check"])(
    "runs the %s task with pnpm's append-only reporter",
    (label) => {
      // A task runs in a terminal, where pnpm's TTY reporter prints a nested
      // `pnpm --recursive` in a box: no prefix, lines cut to the terminal
      // width (#357). Every nested pnpm reads the reporter from this
      // variable, so the matchers read the prefixed lines.
      expect(
        task(label).options?.env?.pnpm_config_reporter,
        `options.env.pnpm_config_reporter of the ${label} task`,
      ).toBe("append-only");
    },
  );

  it.each(["build", "check"])(
    "gives the %s task one tstl matcher per workspace package whose build runs tstl",
    (label) => {
      expect(
        tstlPackages,
        "the packages of pnpm-workspace.yaml whose build runs tstl",
      ).toEqual(
        expect.arrayContaining([
          "packages/reforged-test",
          "packages/reforged-ts",
        ]),
      );
      const matchers = packageMatchers(label, tstl.owner);
      expect(
        matchers.map(({ name }) => name).sort(),
        `the package folders of the ${label} task's tstl matchers`,
      ).toEqual(tstlPackages);
      for (const { name, matcher } of matchers) {
        expect(
          {
            owner: matcher.owner,
            source: matcher.source,
            applyTo: matcher.applyTo,
          },
          `the owner, source and applyTo of the ${name} tstl matcher`,
        ).toEqual(tstl);
      }
    },
  );

  it.each(["build", "check"])(
    "gives the %s task one matcher per workspace package that builds or type-checks",
    (label) => {
      expect(
        typedPackages,
        "the packages of pnpm-workspace.yaml that build or type-check",
      ).toEqual(
        expect.arrayContaining([
          "packages/reforged-ts",
          "packages/reforged-types",
          "website",
        ]),
      );
      expect(
        packageMatchers(label)
          .map(({ name }) => name)
          .sort(),
        `the package folders of the ${label} task's matchers`,
      ).toEqual(typedPackages);
    },
  );

  describe.each(["build", "check"])("the %s task", (label) => {
    it.each(typedPackages)(
      "reports a type error pnpm prints for %s in that package",
      (path) => {
        // The line as the root script prints it, prefixed by pnpm; the
        // script name varies (build, typecheck, a nested script).
        for (const script of ["build", "typecheck", "typings:typecheck"]) {
          const line = `${path} ${script}: src/x.ts(1,14): error TS2322: Type 'string' is not assignable to type 'number'.`;
          expect(problemOf(label, line), line).toEqual({
            matcher: path,
            owner: tsc.owner,
            path: `${path}/src/x.ts`,
            fields: {
              file: "src/x.ts",
              line: "1",
              column: "14",
              severity: "error",
              code: "2322",
              message: "Type 'string' is not assignable to type 'number'.",
            },
          });
        }
        const { matcher } =
          packageMatchers(label).find(({ name }) => name === path) ?? {};
        expect(
          {
            owner: matcher?.owner,
            source: matcher?.source,
            applyTo: matcher?.applyTo,
          },
          `the owner, source and applyTo of the ${path} matcher, as $tsc's`,
        ).toEqual({
          owner: tsc.owner,
          source: tsc.source,
          applyTo: tsc.applyTo,
        });
      },
    );

    it.each(tstlPackages)(
      "reports a typescript-to-lua diagnostic pnpm prints for %s in that package",
      (path) => {
        // The line as `pnpm build` printed it for a regular expression in
        // packages/reforged-ts/src (#291).
        const line = `${path} build: src/x.ts(1,22): error TSTL: Unsupported node kind RegularExpressionLiteral`;
        expect(problemOf(label, line), line).toEqual({
          matcher: path,
          owner: tstl.owner,
          path: `${path}/src/x.ts`,
          fields: {
            file: "src/x.ts",
            line: "1",
            column: "22",
            severity: "error",
            code: "TSTL",
            message: "Unsupported node kind RegularExpressionLiteral",
          },
        });
      },
    );

    it("reports the root's unprefixed type errors through $tsc alone", () => {
      // The root `tsc -p test/tsconfig.json`, which pnpm does not prefix.
      const line =
        "test/x.ts(1,1): error TS2322: Type 'string' is not assignable to type 'number'.";
      const problem = problemOf(label, line);
      expect(problem?.matcher, line).toBe("$tsc");
      expect(problem?.path, line).toBe("test/x.ts");
      expect(
        [...packageMatchers(label), ...packageMatchers(label, tstl.owner)]
          .filter(({ matcher: { pattern } }) =>
            new RegExp(pattern?.regexp ?? "").test(line),
          )
          .map(({ name }) => name),
        "the package matchers that match an unprefixed line",
      ).toEqual([]);
    });
  });

  // pnpm's output as a task's terminal shows it (#357), recorded from real
  // runs rather than run here: CI has no terminal to give pnpm, and on
  // Windows no `script` to fake one. Each was recorded on Linux with pnpm
  // 12.8.1 from the repository root, under `script -qec "<command>"
  // /dev/null`, its escape sequences stripped with `sed
  // 's/\x1b\[[0-9;?]*[a-zA-Z]//g'` and its carriage returns removed; the
  // summary from `Error: ERR_PNPM_...` on is cut, and the repository root
  // removed from the paths. A recursive run needs two packages that do not
  // depend on each other for pnpm to print a prefix at all.
  //
  // The typecheck recordings ran
  //   pnpm --recursive --no-bail --filter reforged-test --filter reforged-types typecheck
  // with this line in packages/reforged-test/src/zz-broken.ts and
  // packages/reforged-types/scripts/zz-broken.ts:
  //   interface ATypeWhoseNameRunsWellPastTheEightyColumnsOfATerminal { readonly n: number } export const x: ATypeWhoseNameRunsWellPastTheEightyColumnsOfATerminal = "s";
  // pnpm-tty-append-only-typecheck.txt with `pnpm_config_reporter=append-only`
  // in the environment, as the tasks set it, pnpm-tty-default-typecheck.txt
  // without it. pnpm-tty-append-only-build.txt is `pnpm build` with the
  // variable and this line in packages/reforged-ts/src/zz-broken.ts:
  //   export const zzBroken = /a regular expression whose diagnostic runs past eighty columns/;
  describe("pnpm's output in a terminal", () => {
    const typeError =
      "Type 'string' is not assignable to type 'ATypeWhoseNameRunsWellPastTheEightyColumnsOfATerminal'.";

    // The lines of a recording that carry a tsc or tstl diagnostic.
    function errorLines(fixture: string): string[] {
      return read(`test/conventions/fixtures/${fixture}`)
        .split("\n")
        .filter((line) => /\berror TS(?:\d+|TL)\b/.test(line));
    }

    function summary(problem: Problem | undefined) {
      return problem && { matcher: problem.matcher, path: problem.path };
    }

    describe.each(["build", "check"])("the %s task", (label) => {
      it("reports each type error of a recursive run with the append-only reporter at its file, in full", () => {
        const lines = errorLines("pnpm-tty-append-only-typecheck.txt");
        expect(
          lines.map((line) => problemOf(label, line)),
          "the problems of pnpm-tty-append-only-typecheck.txt",
        ).toEqual([
          {
            matcher: "packages/reforged-test",
            owner: tsc.owner,
            path: "packages/reforged-test/src/zz-broken.ts",
            fields: {
              file: "src/zz-broken.ts",
              line: "1",
              column: "101",
              severity: "error",
              code: "2322",
              message: typeError,
            },
          },
          {
            matcher: "packages/reforged-types",
            owner: tsc.owner,
            path: "packages/reforged-types/scripts/zz-broken.ts",
            fields: {
              file: "scripts/zz-broken.ts",
              line: "1",
              column: "101",
              severity: "error",
              code: "2322",
              message: typeError,
            },
          },
        ]);
      });

      it("reports a typescript-to-lua diagnostic of pnpm build with the append-only reporter at its file", () => {
        const lines = errorLines("pnpm-tty-append-only-build.txt");
        expect(
          lines.map((line) => problemOf(label, line)),
          "the problems of pnpm-tty-append-only-build.txt",
        ).toEqual([
          {
            matcher: "packages/reforged-ts",
            owner: tstl.owner,
            path: "packages/reforged-ts/src/zz-broken.ts",
            fields: {
              file: "src/zz-broken.ts",
              line: "1",
              column: "25",
              severity: "error",
              code: "TSTL",
              message: "Unsupported node kind RegularExpressionLiteral",
            },
          },
        ]);
      });

      it("misreads the boxed lines of pnpm's default reporter, which the tasks avoid", () => {
        // Without the variable: no prefix, so only `$tsc` matches, at a file
        // that does not exist, and the message is cut at the terminal width.
        const lines = errorLines("pnpm-tty-default-typecheck.txt");
        expect(
          lines.map((line) => summary(problemOf(label, line))),
          "the problems of pnpm-tty-default-typecheck.txt",
        ).toEqual([
          { matcher: "$tsc", path: "│ src/zz-broken.ts" },
          { matcher: "$tsc", path: "│ scripts/zz-broken.ts" },
        ]);
      });
    });
  });
});
