import { execFileSync } from "node:child_process";
import { existsSync, globSync } from "node:fs";
import { posix } from "node:path";
import {
  flattenDiagnosticMessageText,
  parseConfigFileTextToJson,
} from "typescript";
import { describe, expect, it } from "vitest";
import { parse } from "yaml";

import { read, root } from "./repository.js";

// The VS Code files are JSON with comments; TypeScript's parser for its own
// JSONC config files reads them.
function readJsonc(path: string): unknown {
  const result = parseConfigFileTextToJson(path, read(path));
  if (result.error) {
    const message = flattenDiagnosticMessageText(
      result.error.messageText,
      "\n",
    );
    throw new Error(`${path}: ${message}`);
  }
  return result.config as unknown;
}

describe(".vscode/extensions.json", () => {
  it("recommends exactly the ESLint, Prettier and vitest explorer extensions", () => {
    const { recommendations } = readJsonc(".vscode/extensions.json") as {
      recommendations?: string[];
    };
    expect(
      [...(recommendations ?? [])].sort(),
      "the recommended extensions in .vscode/extensions.json",
    ).toEqual([
      "dbaeumer.vscode-eslint",
      "esbenp.prettier-vscode",
      "vitest.explorer",
    ]);
  });
});

describe(".vscode/settings.json", () => {
  // The oracle, independent of the glob: a declaration file is generated when
  // it opens with the generator's header, and a data file when it is named as
  // in packages/reforged-types/src/artefacts.ts and sits next to a generated
  // declaration file. Everything else in the package is hand-written: the Lua
  // runtime declarations, the Overlay, the sources, the tests and their
  // fixtures, the package's own manifests.
  const typingsPackage = "packages/reforged-types";
  const dataFiles = new Set(["async-natives.json", "manifest.json"]);

  function generatedFiles(files: readonly string[]): Set<string> {
    const declarations = files.filter(
      (file) =>
        file.endsWith(".d.ts") &&
        /^(?:.*\n){0,3}\/\/ Generated by reforged-types\b/.test(read(file)),
    );
    const folders = new Set(declarations.map((file) => posix.dirname(file)));
    const data = files.filter(
      (file) =>
        dataFiles.has(posix.basename(file)) && folders.has(posix.dirname(file)),
    );
    return new Set([...declarations, ...data]);
  }

  it("makes read-only every generated file of reforged-types and no hand-written one", () => {
    const { "files.readonlyInclude": include = {} } = readJsonc(
      ".vscode/settings.json",
    ) as { "files.readonlyInclude"?: Record<string, boolean> };
    const globs = Object.keys(include).filter((glob) => include[glob]);

    // The package's files as the editor sees them: committed or new, never
    // ignored (build output, node_modules).
    const files = execFileSync(
      "git",
      [
        "ls-files",
        "--cached",
        "--others",
        "--exclude-standard",
        "-z",
        typingsPackage,
      ],
      { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
    )
      .split("\0")
      .filter((file) => file !== "");
    const generated = generatedFiles(files);
    expect(
      [...generated].map((file) => posix.basename(file)),
      `the generated files of ${typingsPackage}: an entry file and a data file at least`,
    ).toEqual(
      expect.arrayContaining([
        expect.stringMatching(/^\d+\.\d+\.\d+\.d\.ts$/),
        "async-natives.json",
      ]),
    );

    const problems = files.flatMap((file) => {
      const readOnly = globs.some((glob) => posix.matchesGlob(file, glob));
      if (generated.has(file) && !readOnly) {
        return [`${file} is generated and not read-only`];
      }
      if (!generated.has(file) && readOnly) {
        return [`${file} is hand-written and read-only`];
      }
      return [];
    });
    expect(
      problems,
      "the files of reforged-types against files.readonlyInclude in .vscode/settings.json",
    ).toEqual([]);
  });
});

describe(".vscode/tasks.json", () => {
  interface ProblemMatcher {
    owner?: string;
    source?: string;
    applyTo?: string;
    fileLocation?: string | string[];
    pattern?: { regexp?: string } & Record<string, unknown>;
  }
  interface Task {
    label: string;
    problemMatcher?: string | (string | ProblemMatcher)[];
  }

  const { tasks } = readJsonc(".vscode/tasks.json") as { tasks: Task[] };

  function task(label: string): Task {
    const found = tasks.find((candidate) => candidate.label === label);
    if (!found) throw new Error(`.vscode/tasks.json has no ${label} task`);
    return found;
  }

  // The workspace packages, from pnpm-workspace.yaml, whose `build` or
  // `typecheck` script runs tsc or tstl: `pnpm --recursive` prints their
  // errors behind a `<package path> <script>: ` prefix.
  const typedPackages = (() => {
    const { packages: patterns } = parse(read("pnpm-workspace.yaml")) as {
      packages: string[];
    };
    return globSync(patterns, { cwd: root })
      .map((path) => path.replaceAll("\\", "/"))
      .filter((path) => existsSync(posix.join(root, path, "package.json")))
      .filter((path) => {
        const { scripts = {} } = JSON.parse(
          read(posix.join(path, "package.json")),
        ) as { scripts?: Record<string, string> };
        return "build" in scripts || "typecheck" in scripts;
      })
      .sort();
  })();

  const workspaceFolder = "${workspaceFolder}/";

  // The matchers a task defines inline, keyed by the package folder their
  // fileLocation resolves files from.
  function packageMatchers(label: string): [string, ProblemMatcher][] {
    const { problemMatcher = [] } = task(label);
    return [problemMatcher]
      .flat()
      .filter((matcher) => typeof matcher !== "string")
      .map((matcher) => {
        const [kind, folder = ""] = [matcher.fileLocation ?? []].flat();
        const path =
          kind === "relative" && folder.startsWith(workspaceFolder)
            ? folder.slice(workspaceFolder.length)
            : `(fileLocation ${JSON.stringify(matcher.fileLocation)})`;
        return [path, matcher];
      });
  }

  // `$tsc`, as the TypeScript extension of VS Code contributes it
  // (extensions/typescript-language-features/package.json in
  // microsoft/vscode): the matcher and its pattern.
  const tsc: ProblemMatcher = {
    owner: "typescript",
    source: "ts",
    applyTo: "closedDocuments",
    fileLocation: ["relative", "${cwd}"],
    pattern: {
      regexp:
        "^([^\\s].*)[\\(:](\\d+)[,:](\\d+)(?:\\):\\s+|\\s+-\\s+)(error|warning|info)\\s+TS(\\d+)\\s*:\\s*(.*)$",
      file: 1,
      line: 2,
      column: 3,
      severity: 4,
      code: 5,
      message: 6,
    },
  };
  const tscFields = ["file", "line", "column", "severity", "code", "message"];

  interface Problem {
    // The matcher that read the line: `$tsc` or a package folder.
    matcher: string;
    // The file from the workspace root, as the matcher's fileLocation
    // resolves it (a shell task's `${cwd}` is the workspace folder).
    path: string;
    fields: Record<string, string | undefined>;
  }

  // The problem a task reports for an output line: VS Code tries the task's
  // matchers in order and keeps the first that matches (tryMatchers in
  // src/vs/workbench/contrib/tasks/common/problemCollectors.ts).
  function problemOf(label: string, line: string): Problem | undefined {
    const inline = new Map(
      packageMatchers(label).map(([path, matcher]) => [matcher, path]),
    );
    const { problemMatcher = [] } = task(label);
    for (const entry of [problemMatcher].flat()) {
      if (typeof entry === "string" && entry !== "$tsc") continue;
      const matcher = typeof entry === "string" ? tsc : entry;
      const { regexp = "", ...groups } = matcher.pattern ?? {};
      const match = new RegExp(regexp).exec(line);
      if (!match) continue;
      const fields = Object.fromEntries(
        tscFields.map((field) => [field, match[groups[field] as number]]),
      );
      const folder = [matcher.fileLocation ?? []].flat()[1] ?? "";
      return {
        matcher: typeof entry === "string" ? entry : (inline.get(entry) ?? ""),
        path: posix.join(
          folder.replace(/^\$\{(?:workspaceFolder|cwd)\}/, "."),
          fields.file ?? "",
        ),
        fields,
      };
    }
    return undefined;
  }

  it("finds the workspace packages that build or type-check", () => {
    expect(typedPackages, "the typed packages of pnpm-workspace.yaml").toEqual(
      expect.arrayContaining([
        "packages/reforged-ts",
        "packages/reforged-types",
        "website",
      ]),
    );
  });

  it.each(["build", "check"])(
    "gives the %s task one matcher per workspace package that builds or type-checks",
    (label) => {
      expect(
        packageMatchers(label)
          .map(([path]) => path)
          .sort(),
        `the package folders of the ${label} task's matchers`,
      ).toEqual(typedPackages);
    },
  );

  describe.each(["build", "check"])("the %s task", (label) => {
    it.each(typedPackages)(
      "reports a type error pnpm prints for %s in that package",
      (path) => {
        // The line as the root script prints it, prefixed by pnpm; the
        // script name varies (build, typecheck, a nested script).
        for (const script of ["build", "typecheck", "typings:typecheck"]) {
          const line = `${path} ${script}: src/x.ts(1,14): error TS2322: Type 'string' is not assignable to type 'number'.`;
          const problem = problemOf(label, line);
          expect(problem, line).toEqual({
            matcher: path,
            path: `${path}/src/x.ts`,
            fields: {
              file: "src/x.ts",
              line: "1",
              column: "14",
              severity: "error",
              code: "2322",
              message: "Type 'string' is not assignable to type 'number'.",
            },
          });
        }
        const [, matcher] =
          packageMatchers(label).find(([folder]) => folder === path) ?? [];
        expect(
          {
            owner: matcher?.owner,
            source: matcher?.source,
            applyTo: matcher?.applyTo,
          },
          `the owner, source and applyTo of the ${path} matcher, as $tsc's`,
        ).toEqual({
          owner: tsc.owner,
          source: tsc.source,
          applyTo: tsc.applyTo,
        });
      },
    );

    it("reports the root's unprefixed type errors through $tsc alone", () => {
      // The root `tsc -p test/tsconfig.json`, which pnpm does not prefix.
      const line =
        "test/x.ts(1,1): error TS2322: Type 'string' is not assignable to type 'number'.";
      expect(problemOf(label, line)?.matcher, line).toBe("$tsc");
      expect(problemOf(label, line)?.path, line).toBe("test/x.ts");
      expect(
        packageMatchers(label)
          .filter(([, { pattern }]) =>
            new RegExp(pattern?.regexp ?? "").test(line),
          )
          .map(([path]) => path),
        "the package matchers that match an unprefixed line",
      ).toEqual([]);
    });
  });
});
