import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { runLuaTestFiles } from "reforged-test";
import { afterAll, describe, expect, it } from "vitest";
import {
  DECLARATIONS_FILE,
  LUA_STUB_FILE,
  MapFolderError,
  generateEditorGlobals,
  type EditorGlobalsOutput,
} from "../src/index.js";
import {
  fixtureMap,
  makeTempDir,
  mapFolder,
  removeTemporary,
} from "./support/map-folder.js";

afterAll(removeTemporary);

const BANNER =
  "Generated by reforged-map from the map folder's war3map.lua and war3map.wtg on every install, build and watch.";

/** A 3.0-style script: header, InitGlobals, custom script, unindented trigger functions. */
const SCRIPT = [
  "udg_Score = 0",
  "udg_Rate = 0.0",
  "udg_Hex = 0x10",
  'udg_Name = ""',
  "udg_Flag = false",
  "udg_Kills = __jarray(0)",
  "udg_Speeds = __jarray(0.0)",
  'udg_Names = __jarray("")',
  "udg_Flags = __jarray(false)",
  "udg_Timers = {}",
  "udg_Spots = {}",
  "udg_Group = nil",
  "udg_Players = nil",
  "udg_Hero = nil",
  "udg_Made = CreateTimer()",
  "udg_Weird = 1 + 2",
  "gg_rct_Spawn = nil",
  "gg_cam_Intro = nil",
  "gg_snd_Hit = nil",
  'gg_snd_Theme = "Sound\\\\Music\\\\mp3Music\\\\Comradeship.mp3"',
  "gg_trg_Melee_Initialization = nil",
  "gg_unit_H002_0255 = nil",
  "gg_dest_LTlt_0012 = nil",
  "gg_item_ratf_0003 = nil",
  "gg_qst_Main = nil",
  "  gg_rct_Indented = nil",
  "local udg_Local = 0",
  "gg_rct_Spawn = CreateRegion()",
  "function InitGlobals()",
  "local i = 0",
  "udg_Group = CreateGroup()",
  "udg_Players = CreateForce()",
  "i = 0",
  "while (true) do",
  "if ((i > 1)) then break end",
  "udg_Timers[i] = CreateTimer()",
  "i = i + 1",
  "end",
  "udg_Hero = nil",
  "end",
  "",
  "-- custom script: pasted after InitGlobals, anything at column 0",
  "udg_FromCustom = 5",
  "gg_rct_FromCustom = nil",
  "udg_Hero = CreateUnit(Player(0), FourCC('hfoo'), 0, 0, 0)",
  "",
  "function InitTrig_Melee_Initialization()",
  "gg_trg_Melee_Initialization = CreateTrigger()",
  "gg_rct_Late = nil",
  "end",
].join("\r\n");

/** The generated file of that name. */
function contents(output: EditorGlobalsOutput, name: string): string {
  const file = output.files.find((candidate) => candidate.name === name);
  if (file === undefined) throw new Error(`no ${name} generated`);
  return file.contents;
}

/** The `declare let` lines of the declarations, as name to type, in order. */
function declaredTypes(output: EditorGlobalsOutput): Record<string, string> {
  return Object.fromEntries(
    contents(output, DECLARATIONS_FILE)
      .split("\n")
      .flatMap((line) => {
        const match = /^declare let (\w+): (.*);$/.exec(line);
        return match ? [[match[1], match[2]]] : [];
      }),
  );
}

/** The generated output of a map folder holding this war3map.lua. */
const generate = (script: string): EditorGlobalsOutput =>
  generateEditorGlobals(mapFolder({ "war3map.lua": script }));

describe("generateEditorGlobals", () => {
  const result = generate(SCRIPT);
  const types = declaredTypes(result);
  const declarations = contents(result, DECLARATIONS_FILE);
  const stub = contents(result, LUA_STUB_FILE);

  it("returns the declarations and the Lua stub, by bare file name", () => {
    expect(DECLARATIONS_FILE).toBe("editor-globals.d.ts");
    expect(LUA_STUB_FILE).toBe("editor-globals.lua");
    expect(result.files.map((file) => file.name)).toEqual([
      DECLARATIONS_FILE,
      LUA_STUB_FILE,
    ]);
  });

  it("maps each known gg_ prefix to its handle type", () => {
    expect(types).toMatchObject({
      gg_rct_Spawn: "rect",
      gg_cam_Intro: "camerasetup",
      gg_snd_Hit: "sound",
      gg_trg_Melee_Initialization: "trigger",
      gg_unit_H002_0255: "unit",
      gg_dest_LTlt_0012: "destructable",
      gg_item_ratf_0003: "item",
    });
  });

  it("types a music entry (a gg_snd_ string) as string", () => {
    expect(types.gg_snd_Theme).toBe("string");
  });

  it("declares an unknown gg_ prefix as the root handle type, with a warning", () => {
    expect(types.gg_qst_Main).toBe("handle");
    expect(result.warnings).toContain(
      "gg_qst_Main: unknown editor prefix gg_qst_, declared as handle.",
    );
  });

  it("types udg_ variables from their initializer", () => {
    expect(types).toMatchObject({
      udg_Score: "number",
      udg_Rate: "number",
      udg_Hex: "number",
      udg_Name: "string",
      udg_Flag: "boolean",
      udg_Kills: "Record<number, number>",
      udg_Speeds: "Record<number, number>",
      udg_Names: "Record<number, string>",
      udg_Flags: "Record<number, boolean>",
      // Handles: the Native call the editor assigns in the header or in InitGlobals.
      udg_Made: "NonNullable<ReturnType<typeof CreateTimer>>",
      udg_Group: "NonNullable<ReturnType<typeof CreateGroup>>",
      udg_Players: "NonNullable<ReturnType<typeof CreateForce>>",
      udg_Timers: "Record<number, NonNullable<ReturnType<typeof CreateTimer>>>",
      // Nothing to infer from.
      udg_Hero: "unknown",
      udg_Spots: "Record<number, unknown>",
      udg_Weird: "unknown",
    });
    expect(result.warnings).toContain(
      "udg_Weird: initializer `1 + 2` not recognized, declared as unknown.",
    );
  });

  it("warns only on the unknown prefix and the unrecognized initializer", () => {
    expect(result.warnings).toEqual([
      "udg_Weird: initializer `1 + 2` not recognized, declared as unknown.",
      "gg_qst_Main: unknown editor prefix gg_qst_, declared as handle.",
    ]);
  });

  it("ignores custom script, indented, local and in-function assignments; the first header assignment wins", () => {
    for (const name of [
      "udg_FromCustom",
      "gg_rct_FromCustom",
      "gg_rct_Indented",
      "udg_Local",
      "gg_rct_Late",
    ]) {
      expect(types).not.toHaveProperty(name);
    }
    expect(
      declarations.split("\n").filter((l) => l.includes(" gg_rct_Spawn:")),
    ).toHaveLength(1);
    // udg_Hero's CreateUnit sits in the custom script, after InitGlobals ended.
    expect(types.udg_Hero).toBe("unknown");
  });

  it("reads InitGlobals whether or not the editor indented it", () => {
    const indented = generate(
      "udg_G = nil\nfunction InitGlobals()\n    local i = 0\n    udg_G = CreateGroup()\nend\n",
    );
    expect(declaredTypes(indented).udg_G).toBe(
      "NonNullable<ReturnType<typeof CreateGroup>>",
    );
  });

  it("reads a war3map.lua that starts with a byte order mark", () => {
    expect(declaredTypes(generate("\uFEFFudg_Score = 0\n"))).toEqual({
      udg_Score: "number",
    });
  });

  it("produces both outputs from one call, one entry per global, with the banner", () => {
    const lines = declarations
      .split("\n")
      .filter((l) => l.startsWith("declare let "));
    const assignments = stub.split("\n").filter((l) => /^(gg|udg)_/.test(l));
    expect(lines).toHaveLength(Object.keys(types).length);
    expect(assignments).toHaveLength(lines.length);
    expect(declarations.startsWith(`// ${BANNER}\n`)).toBe(true);
    expect(stub.startsWith(`-- ${BANNER}\n`)).toBe(true);
    expect(lines).toContain("declare let gg_rct_Spawn: rect;");
    expect(lines).toContain("declare let udg_Kills: Record<number, number>;");
  });

  it("stubs every global with nil or its header literal, calling no Native", () => {
    expect(stub).toContain("\nudg_Score = 0\n");
    expect(stub).toContain("\nudg_Rate = 0.0\n");
    expect(stub).toContain('\nudg_Name = ""\n');
    expect(stub).toContain("\nudg_Flag = false\n");
    expect(stub).toContain("\nudg_Kills = __jarray(0)\n");
    expect(stub).toContain("\nudg_Timers = {}\n");
    expect(stub).toContain("\nudg_Group = nil\n");
    expect(stub).toContain("\nudg_Made = nil\n");
    expect(stub).toContain("\ngg_rct_Spawn = nil\n");
    expect(stub).toContain(
      '\ngg_snd_Theme = "Sound\\\\Music\\\\mp3Music\\\\Comradeship.mp3"\n',
    );
    // Stub authoring rules: none of the libraries the game lacks.
    expect(stub).not.toMatch(
      /\b(debug|require|package|io|collectgarbage|load)\b|os\.getenv/,
    );
  });

  it("reads the blank map fixture: one trigger, no warnings", () => {
    const fixture = generateEditorGlobals(fixtureMap("blank-map.w3m"));
    expect(declaredTypes(fixture)).toEqual({
      gg_trg_Melee_Initialization: "trigger",
    });
    expect(contents(fixture, LUA_STUB_FILE)).toContain(
      "\ngg_trg_Melee_Initialization = nil\n",
    );
    expect(fixture.warnings).toEqual([]);
  });
});

describe("author errors", () => {
  it("throws a MapFolderError naming a missing map folder", () => {
    const missing = path.join(makeTempDir(), "missing.w3m");
    expect(() => generateEditorGlobals(missing)).toThrow(
      new MapFolderError(
        `Map folder not found: ${missing}. Save the map as a folder from the World Editor (File > Save Map As, "Folder").`,
      ),
    );
    expect(() => generateEditorGlobals(missing)).toThrow(MapFolderError);
  });

  it("throws a MapFolderError for a map folder saved without Lua", () => {
    const folder = mapFolder({ "war3map.j": "globals\nendglobals\n" });
    expect(() => generateEditorGlobals(folder)).toThrow(
      new MapFolderError(
        "test.w3m has no war3map.lua: the map was not saved with Lua as the script language. " +
          "In the World Editor, set Scenario > Map Options > Script Language to Lua and save the map again.",
      ),
    );
    expect(() => generateEditorGlobals(folder)).toThrow(MapFolderError);
  });

  it("names its class MapFolderError", () => {
    expect(new MapFolderError("x").name).toBe("MapFolderError");
  });
});

describe("the generated Lua stub in the reforged-test harness (Lua 5.3)", () => {
  it("loads after the shipped stubs, sets the globals, and adds no call-log line", () => {
    const dir = makeTempDir();
    const stub = path.join(dir, LUA_STUB_FILE);
    fs.writeFileSync(stub, contents(generate(SCRIPT), LUA_STUB_FILE));
    const outDir = path.join(dir, "out");
    fs.mkdirSync(path.join(outDir, "lua_modules", "reforged-test", "lua"), {
      recursive: true,
    });
    fs.copyFileSync(
      createRequire(import.meta.url).resolve("reforged-test/lua/index.lua"),
      path.join(outDir, "lua_modules", "reforged-test", "lua", "index.lua"),
    );
    fs.writeFileSync(
      path.join(outDir, "stub_test.lua"),
      [
        'local t = require("lua_modules.reforged-test.lua.index")',
        't.describe("editor globals", function()',
        '  t.it("has the header values", function()',
        "    t.expect(udg_Score).toBe(0)",
        '    t.expect(udg_Name).toBe("")',
        "    t.expect(udg_Flag).toBe(false)",
        "    t.expect(gg_rct_Spawn).toBe(nil)",
        "    t.expect(udg_Group).toBe(nil)",
        "    t.expect(udg_Kills[7]).toBe(0)",
        "    t.expect(udg_Speeds[3]).toBe(0.0)",
        "    t.expect(udg_Timers[1]).toBe(nil)",
        "    udg_Kills[7] = 3",
        "    t.expect(udg_Kills[7]).toBe(3)",
        "    t.expect(#t.stubCalls()).toBe(0)",
        "  end)",
        "end)",
        "",
      ].join("\n"),
    );

    const file = runLuaTestFiles({ outDir, stubs: [stub] }).at(0);

    expect(file?.error).toBeUndefined();
    expect(file?.tests).toEqual([
      {
        suite: ["editor globals"],
        name: "has the header values",
        status: "pass",
      },
    ]);
  });
});
