// The code samples of the hand-written docs pages (#40, #187): every
// TypeScript fence of a page is a Map project snippet, type-checked against
// the library, the Typings and the test harness as the Template compiles its
// code. A fence whose meta holds `fragment` is prose only (a signature, a
// partial statement, the old API of a migration page) and is not checked.
//
// Each page is a Map project of its own: a fence with a `title` is the file
// at that path (```ts title="src/main.ts"), so the fences of one page can
// import each other; a fence without one is a module of its own under `src/`.
// Every snippet is a module (`moduleDetection: force`), so two untitled
// snippets never share a declaration. The Template's files a Map project
// always has are there too (`TEMPLATE_FILES`).
import { readdir, readFile } from "node:fs/promises";
import { join, posix, relative, sep } from "node:path";
import * as ts from "typescript";

/** One TypeScript fence of a docs page. */
export interface Snippet {
  /** The page, as a `/`-separated path under the docs tree. */
  readonly page: string;
  /** The page line of the snippet's first code line (1-based). */
  readonly line: number;
  /** The Map project path the fence's `title` gives it. */
  readonly title?: string;
  readonly code: string;
}

/** A compiler diagnostic, located on its page. */
export interface SnippetProblem {
  readonly page: string;
  readonly line: number;
  readonly column: number;
  readonly message: string;
}

/** The languages of a fence that holds a snippet. */
const LANGUAGES = new Set(["ts", "typescript"]);

/** The meta word of a fence that is prose only. */
export const FRAGMENT = "fragment";

const OPENING = /^(\s*)(`{3,}|~{3,})\s*([^\s`]*)(.*)$/;
const TITLE = /\btitle=(["'])(.*?)\1/;

/**
 * The snippets of a Markdown or MDX page: its `ts` fences, but those marked
 * `fragment`. A fence inside a list item may be indented; its indentation is
 * taken off its lines.
 */
export function extractSnippets(markdown: string, page: string): Snippet[] {
  const lines = markdown.split(/\r?\n/);
  const snippets: Snippet[] = [];
  for (let index = 0; index < lines.length; index++) {
    const opening = OPENING.exec(lines[index] ?? "");
    if (opening === null) continue;
    const [, indent = "", fence = "", language = "", meta = ""] = opening;
    const closing = new RegExp(
      `^\\s*${fence[0] ?? ""}{${String(fence.length)},}\\s*$`,
    );
    let end = index + 1;
    while (end < lines.length && !closing.test(lines[end] ?? "")) end++;
    if (LANGUAGES.has(language) && !meta.split(/\s+/).includes(FRAGMENT)) {
      const code = lines
        .slice(index + 1, end)
        .map((line) =>
          line.startsWith(indent)
            ? line.slice(indent.length)
            : line.trimStart(),
        )
        .join("\n");
      const title = TITLE.exec(meta)?.[2];
      snippets.push({
        page,
        line: index + 2,
        ...(title === undefined ? {} : { title }),
        code: `${code}\n`,
      });
    }
    index = end;
  }
  return snippets;
}

/**
 * The compiler options of a Map project, as the Template's
 * `tsconfig.base.json` sets them, and `moduleDetection: force` so every
 * snippet is a module.
 */
export const MAP_PROJECT_OPTIONS: ts.CompilerOptions = {
  target: ts.ScriptTarget.ESNext,
  lib: ["lib.esnext.d.ts"],
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  moduleDetection: ts.ModuleDetectionKind.Force,
  strict: true,
  skipLibCheck: true,
  noEmit: true,
  types: ["@typescript-to-lua/language-extensions", "reforged-types/3.0.0"],
};

/**
 * The files of the Template every page's Map project holds, by path: the
 * build mode `src/main.ts` imports (generated by the Template's install), and
 * the declarations of the test harness's firing helpers the Template's Lua
 * tests use. The helpers are global, so they are declared once, not per page.
 */
export const TEMPLATE_FILES = {
  perPage: {
    "src/generated/env.ts": "export const devMode: boolean = true;\n",
  },
  shared: {
    "tests/lua/stubs.d.ts": `/** @noSelfInFile */
type StubContext = {
  readonly [
    N in keyof typeof globalThis
  ]?: (typeof globalThis)[N] extends () => infer R ? NonNullable<R> : never;
};
declare function __stub_fire_trigger(
  whichTrigger: trigger,
  context?: StubContext,
): boolean;
declare function __stub_fire_timer(whichTimer: timer): void;
declare function __stub_format(value: unknown): string;
`,
  },
} as const;

/** The folder, under `base`, that holds the pages' virtual Map projects. */
const PROJECTS = ".snippets";

export interface CheckOptions {
  /**
   * The folder the snippets' packages resolve from, through its
   * `node_modules` (`reforged-ts`, `reforged-types`, `reforged-test`, the
   * typescript-to-lua language extensions): the website package.
   */
  readonly base: string;
}

/**
 * Type-checks `snippets` as the Map projects of their pages, in one program,
 * and returns the diagnostics located on the pages, in page and line order.
 * A snippet whose title is not a relative `.ts` path, or that two fences of a
 * page share, is a problem too.
 */
export function checkSnippets(
  snippets: readonly Snippet[],
  options: CheckOptions,
): SnippetProblem[] {
  const problems: SnippetProblem[] = [];
  const root = join(options.base, PROJECTS);
  /** The virtual files, by absolute `/`-separated path. */
  const files = new Map<string, string>();
  /** Where each snippet's file is, to locate its diagnostics. */
  const located = new Map<string, Snippet>();
  const pages = new Set(snippets.map((snippet) => snippet.page));
  const add = (path: string, text: string) =>
    files.set(posix.normalize(path.split(sep).join("/")), text);

  for (const [path, text] of Object.entries(TEMPLATE_FILES.shared))
    add(join(root, path), text);
  for (const page of pages)
    for (const [path, text] of Object.entries(TEMPLATE_FILES.perPage))
      add(join(root, page, path), text);
  for (const snippet of snippets) {
    const path = snippetPath(snippet);
    if (path === undefined) {
      problems.push({
        page: snippet.page,
        line: snippet.line - 1,
        column: 1,
        message: `the title "${snippet.title ?? ""}" is not a relative path to a .ts file of the Map project`,
      });
      continue;
    }
    const file = posix.normalize(
      join(root, snippet.page, path).split(sep).join("/"),
    );
    const previous = located.get(file);
    if (previous !== undefined) {
      problems.push({
        page: snippet.page,
        line: snippet.line - 1,
        column: 1,
        message: `the title "${path}" is also the title of the snippet at line ${String(previous.line - 1)}: give one of them another path`,
      });
      continue;
    }
    files.set(file, snippet.code);
    located.set(file, snippet);
  }

  const host = virtualHost(files, options.base);
  const program = ts.createProgram({
    rootNames: [...files.keys()],
    options: MAP_PROJECT_OPTIONS,
    host,
  });
  for (const diagnostic of ts.getPreEmitDiagnostics(program)) {
    const { file, start } = diagnostic;
    const snippet = file === undefined ? undefined : located.get(file.fileName);
    const text = ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n");
    const message = `TS${String(diagnostic.code)}: ${text}`;
    if (file === undefined || snippet === undefined || start === undefined) {
      // A diagnostic of the setup itself (a package that does not resolve):
      // every page's check is void, so it is reported on the first one.
      problems.push({
        page: snippets[0]?.page ?? "",
        line: 0,
        column: 0,
        message: file === undefined ? message : `${message} (${file.fileName})`,
      });
      continue;
    }
    const at = ts.getLineAndCharacterOfPosition(file, start);
    problems.push({
      page: snippet.page,
      line: snippet.line + at.line,
      column: at.character + 1,
      message,
    });
  }
  return problems.sort((a, b) =>
    a.page < b.page ? -1 : a.page > b.page ? 1 : a.line - b.line,
  );
}

/** The Map project path of a snippet, undefined for an invalid title. */
function snippetPath(snippet: Snippet): string | undefined {
  if (snippet.title === undefined)
    return `src/snippet-${String(snippet.line)}.ts`;
  const path = posix.normalize(snippet.title);
  if (path.startsWith("../") || posix.isAbsolute(path) || !path.endsWith(".ts"))
    return undefined;
  return path;
}

/** A compiler host that serves `files` over the real file system. */
function virtualHost(
  files: ReadonlyMap<string, string>,
  base: string,
): ts.CompilerHost {
  const host = ts.createCompilerHost(MAP_PROJECT_OPTIONS);
  const folders = new Set<string>();
  for (const file of files.keys())
    for (
      let folder = posix.dirname(file);
      !folders.has(folder);
      folder = posix.dirname(folder)
    ) {
      folders.add(folder);
      if (posix.dirname(folder) === folder) break;
    }
  const getSourceFile = host.getSourceFile.bind(host);
  const fileExists = host.fileExists.bind(host);
  const readFileText = host.readFile.bind(host);
  const directoryExists = host.directoryExists?.bind(host);
  return {
    ...host,
    getCurrentDirectory: () => base,
    fileExists: (name) => files.has(name) || fileExists(name),
    readFile: (name) => files.get(name) ?? readFileText(name),
    directoryExists: (name) =>
      folders.has(posix.normalize(name)) || (directoryExists?.(name) ?? true),
    getSourceFile: (name, language, onError, create) => {
      const text = files.get(name);
      return text === undefined
        ? getSourceFile(name, language, onError, create)
        : ts.createSourceFile(name, text, language);
    },
  };
}

/** A Markdown page of the docs tree. */
const PAGE = /\.mdx?$/;

/**
 * The hand-written pages of the docs tree `docs` whose snippets are checked,
 * as `/`-separated paths: every Markdown and MDX page but those under `skip`
 * (the collected pages and the generated API reference).
 */
export async function snippetPages(
  docs: string,
  skip: readonly string[],
): Promise<string[]> {
  const entries = await readdir(docs, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && PAGE.test(entry.name))
    .map((entry) =>
      relative(docs, join(entry.parentPath, entry.name)).split(sep).join("/"),
    )
    .filter(
      (page) =>
        !skip.some((path) => page === path || page.startsWith(`${path}/`)),
    )
    .sort();
}

/** The snippets of the pages of `docs` (see `snippetPages`). */
export async function docsSnippets(
  docs: string,
  skip: readonly string[],
): Promise<Snippet[]> {
  const snippets: Snippet[] = [];
  for (const page of await snippetPages(docs, skip))
    snippets.push(
      ...extractSnippets(await readFile(join(docs, page), "utf8"), page),
    );
  return snippets;
}

/** One problem as a line of a report: `guides/x.md:12:5 TS2304: ...`. */
export const formatProblem = (problem: SnippetProblem): string =>
  `${problem.page}:${String(problem.line)}:${String(problem.column)} ${problem.message}`;
