import { execFile } from "node:child_process";
import { mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { main, WORKSPACE } from "../scripts/collect.mts";
import { collect, CollectError, type Source } from "../scripts/collector.mts";
import { markdownFile } from "../scripts/kinds.mts";
import { SOURCES } from "../scripts/sources.mts";
import {
  fixture,
  readText,
  REPOSITORY_FILES,
  writeText,
} from "./support/workspace.mts";

const GITHUB = "https://github.com/phmilk/reforged-ts/blob/master";

/** Every file under `dir`, `/`-separated and sorted. */
async function files(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) =>
      join(entry.parentPath, entry.name)
        .slice(dir.length + 1)
        .replace(/\\/g, "/"),
    )
    .sort();
}

/** The fixture repository without the files at `paths`. */
function without(...paths: string[]): Record<string, string> {
  return Object.fromEntries(
    Object.entries(REPOSITORY_FILES).filter(([path]) => !paths.includes(path)),
  );
}

function capture() {
  const out = { stdout: "", stderr: "" };
  return {
    out,
    output: {
      stdout: (text: string) => (out.stdout += text),
      stderr: (text: string) => (out.stderr += text),
    },
  };
}

describe("collect", () => {
  it("writes the Contributing pages and the changelogs of a fixture repository", async () => {
    const workspace = await fixture();
    const report = await collect(workspace);
    expect(await files(workspace.docs)).toEqual([
      "changelog/index.md",
      "changelog/reforged-ts.md",
      "contributing/adding-a-lint-rule.md",
      "contributing/adding-a-patch.md",
      "contributing/adr/0001-typings-generated.md",
      "contributing/adr/0002-site-links.md",
      "contributing/adr/_category_.json",
      "contributing/adr/index.md",
      "contributing/agent-conventions.md",
      "contributing/glossary.md",
    ]);
    expect(report.collected.map(({ source }) => source)).toEqual([
      "the glossary",
      "the ADRs",
      "the agent conventions",
      "the lint plugin's conventions",
      "the Typings' conventions",
      "the changelog of reforged-ts",
      "the changelog index",
    ]);
  });

  it("gives a copied page its front matter and its note, without the source's title", async () => {
    const workspace = await fixture();
    await collect(workspace);
    expect(await readText(workspace.docs, "contributing/glossary.md")).toBe(
      `---
# Generated by docs:collect from CONTEXT.md: edit the source, not this file.
title: "Glossary"
sidebar_position: 2
custom_edit_url: ${GITHUB}/CONTEXT.md
format: md
---

:::note[Generated page]
This page is generated from [\`CONTEXT.md\`](${GITHUB}/CONTEXT.md) by \`docs:collect\`. Edit the source, not this page.
:::

The words of the fixture. Decisions are [ADRs](./adr/index.md); the tracker is [#20](https://github.com/phmilk/reforged-ts/issues/20).

## Language

**Native**:
A function the game exposes.
`,
    );
  });

  it("titles each ADR with its number and heading and keeps the number in its URL", async () => {
    const workspace = await fixture();
    await collect(workspace);
    const page = await readText(
      workspace.docs,
      "contributing/adr/0002-site-links.md",
    );
    expect(page).toContain(`title: "ADR 0002: The site links | its sources"
sidebar_label: "ADR 0002"
sidebar_position: 2
slug: "0002-site-links"
custom_edit_url: ${GITHUB}/docs/adr/0002-site-links.md
`);
    expect(page).not.toContain("status: proposed");
    expect(page).not.toContain("# The site links");
  });

  it("rewrites a repository link to the collected page, else to GitHub, and leaves code alone", async () => {
    const workspace = await fixture();
    await collect(workspace);
    const page = await readText(
      workspace.docs,
      "contributing/adr/0002-site-links.md",
    );
    expect(page).toContain(
      `It follows [ADR 0001](./0001-typings-generated.md#context), the [release docs](${GITHUB}/docs/release.md#the-website), the [glossary][words] and the [Typings](${GITHUB}/packages/reforged-types/).`,
    );
    expect(page).toContain("[words]: ../glossary.md\n");
    expect(page).toContain("`[not a link](0001-typings-generated.md)`");
    expect(page).toContain("[not a link either](../release.md)");
    expect(
      await readText(workspace.docs, "contributing/adding-a-lint-rule.md"),
    ).toContain(
      `See the [glossary](./glossary.md) and [a bad escape](${GITHUB}/packages/eslint-plugin-reforged/%zz.md).`,
    );
  });

  it("gives a source the repository and the docs tree", async () => {
    const seen: string[] = [];
    const probe: Source = {
      name: "a probe",
      outputs: [],
      collect: ({ root, docs }) => {
        seen.push(root, docs);
        return Promise.resolve({});
      },
    };
    const workspace = await fixture({}, [probe]);
    await collect(workspace);
    expect(seen).toEqual([workspace.root, workspace.docs]);
  });

  it("lists the ADRs with their status and date on the index", async () => {
    const workspace = await fixture();
    await collect(workspace);
    expect(await readText(workspace.docs, "contributing/adr/index.md"))
      .toContain(`| ADR | Decision | Status | Date |
| --- | --- | --- | --- |
| [0001](./0001-typings-generated.md) | Typings are generated | accepted | 2026-09-23 |
| [0002](./0002-site-links.md) | The site links \\| its sources | proposed | 2026-09-24 |
`);
    expect(
      await readText(workspace.docs, "contributing/adr/_category_.json"),
    ).toBe(`{\n  "label": "Architecture decisions",\n  "position": 3\n}\n`);
  });

  it("lists every package on the changelog index and links the releases of each changelog", async () => {
    const workspace = await fixture();
    await collect(workspace);
    const index = await readText(workspace.docs, "changelog/index.md");
    expect(index).toContain(`## [reforged-ts](./reforged-ts.md)

- [1.0.0-alpha.1](./reforged-ts.md#100-alpha1)
- [1.0.0-alpha.0](./reforged-ts.md#100-alpha0)

## reforged-types

No release yet.
`);
    expect(index).toContain(`custom_edit_url: null`);
    const changelog = await readText(
      workspace.docs,
      "changelog/reforged-ts.md",
    );
    expect(changelog).toContain(`title: "reforged-ts"\nsidebar_position: 1\n`);
    expect(changelog).toContain("- A fix for `Map<K, V>` {braces}.");
  });

  it("reports a legitimately absent source as skipped with its reason", async () => {
    const report = await collect(await fixture());
    expect(report.skipped).toEqual([
      {
        source: "the contributing guide",
        reason: "The contribution model (#193) adds CONTRIBUTING.md.",
      },
      {
        source: "the add-wrapper Agent skill",
        reason:
          "The add-wrapper Agent skill (#202) is not written yet; #41 commits .claude/skills/.",
      },
      ...["reforged-types", "reforged-test", "eslint-plugin-reforged"].map(
        (pkg) => ({
          source: `the changelog of ${pkg}`,
          reason: "Changesets writes it at the package's first release.",
        }),
      ),
    ]);
  });

  it("collects an optional source once it exists", async () => {
    const workspace = await fixture({
      ...REPOSITORY_FILES,
      "CONTRIBUTING.md":
        "# Contributing to reforged-ts\n\nThe words are in [`CONTEXT.md`](CONTEXT.md).\n",
    });
    await collect(workspace);
    const page = await readText(workspace.docs, "contributing/guide.md");
    expect(page).toContain(`title: "Contributing guide"`);
    expect(page).toContain("The words are in [`CONTEXT.md`](./glossary.md).");
  });

  it("fails naming each missing required source and leaves the docs tree as it was", async () => {
    const workspace = await fixture(without("CONTEXT.md", "AGENTS.md"));
    await writeText(workspace.docs, "contributing/glossary.md", "stale\n");
    const failure = collect(workspace);
    await expect(failure).rejects.toThrow(CollectError);
    await expect(failure).rejects.toThrow(
      "docs:collect failed:\n- [ ] the glossary: `CONTEXT.md` does not exist.\n- [ ] the agent conventions: `AGENTS.md` does not exist.",
    );
    expect(await files(workspace.docs)).toEqual(["contributing/glossary.md"]);
  });

  it("fails on an ADR folder without an ADR", async () => {
    const workspace = await fixture(
      without(
        "docs/adr/0001-typings-generated.md",
        "docs/adr/0002-site-links.md",
      ),
    );
    await expect(collect(workspace)).rejects.toThrow(
      "the ADRs: `docs/adr` holds no `NNNN-<slug>.md` file.",
    );
  });

  it("removes what the previous run wrote", async () => {
    const workspace = await fixture();
    await collect(workspace);
    await rm(join(workspace.root, "docs/adr/0002-site-links.md"));
    await rm(join(workspace.root, "packages/reforged-ts/CHANGELOG.md"));
    await collect(workspace);
    const written = await files(workspace.docs);
    expect(written).not.toContain("contributing/adr/0002-site-links.md");
    expect(written).not.toContain("changelog/reforged-ts.md");
    expect(written).toContain("changelog/index.md");
  });

  it("fails a source that writes outside its outputs", async () => {
    const stray: Source = {
      name: "a stray source",
      outputs: ["stray"],
      collect: () =>
        Promise.resolve({ files: [{ path: "elsewhere/file.json", text: "" }] }),
    };
    await expect(collect(await fixture({}, [stray]))).rejects.toThrow(
      "a stray source: `elsewhere/file.json` is not one of its outputs (stray).",
    );
  });

  it("links a page from a source added to the list", async () => {
    const extra = markdownFile({
      name: "a new source",
      from: "docs/new.md",
      to: "guides/new.md",
      title: "New",
      position: 1,
    });
    const workspace = await fixture(
      {
        ...REPOSITORY_FILES,
        "docs/new.md": "# New\n\nSee [the glossary](../CONTEXT.md#language).\n",
      },
      [...SOURCES, extra],
    );
    await collect(workspace);
    expect(await readText(workspace.docs, "guides/new.md")).toContain(
      "See [the glossary](../contributing/glossary.md#language).",
    );
  });
});

describe("main", () => {
  it("reports what it collected and skipped", async () => {
    const { out, output } = capture();
    expect(await main([], output, await fixture())).toBe(0);
    expect(out.stdout).toContain(
      "docs:collect: 7 sources collected, 5 skipped.\n  collected the glossary: contributing/glossary.md\n",
    );
    expect(out.stdout).toContain(
      "  skipped the contributing guide: The contribution model (#193) adds CONTRIBUTING.md.\n",
    );
  });

  it("exits 1 naming a missing source", async () => {
    const { out, output } = capture();
    expect(await main([], output, await fixture(without("CONTEXT.md")))).toBe(
      1,
    );
    expect(out.stderr).toBe(
      "docs:collect failed:\n- [ ] the glossary: `CONTEXT.md` does not exist.\n",
    );
  });

  it("exits 2 on an argument", async () => {
    const { out, output } = capture();
    expect(await main(["--watch"], output, await fixture())).toBe(2);
    expect(out.stderr).toContain("Usage");
  });
});

describe("the sources of this repository", () => {
  it("have no missing required source", async () => {
    const docs = await mkdtemp(join(tmpdir(), "reforged-website-docs-"));
    const report = await collect({ ...WORKSPACE, docs });
    expect(report.collected.map(({ source }) => source)).toContain(
      "the glossary",
    );
  });

  it("write only paths git ignores", async () => {
    const paths = SOURCES.flatMap((source) => source.outputs).flatMap(
      (output) => [
        `website/docs/${output}`,
        ...(/\.\w+$/.test(output) ? [] : [`website/docs/${output}/page.md`]),
      ],
    );
    const { stdout } = await promisify(execFile)(
      "git",
      ["check-ignore", "--verbose", "--non-matching", ...paths],
      { cwd: WORKSPACE.root },
      // git check-ignore exits 1 when a path is not ignored.
    ).catch((error: unknown) => {
      if (error instanceof Error && "stdout" in error) {
        return { stdout: String(error.stdout) };
      }
      throw error;
    });
    const notIgnored = stdout
      .split("\n")
      .filter((line) => line.startsWith("::"))
      .map((line) => line.slice(2).trim());
    expect(notIgnored).toEqual([]);
  });
});
