import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { collect, CollectError } from "../scripts/collector.mts";
import {
  DECLARATIONS,
  FIRST_PAGE,
  fixture,
  MIGRATION,
  MIGRATION_PAGE,
  readText,
  renameEntry,
  RENAMES,
  renamesJson,
  REPOSITORY_FILES,
} from "./support/workspace.mts";

const GITHUB = "https://github.com/phmilk/reforged-ts/blob/master";

/** Where the partials of the first version pair are written. */
const PARTIALS = "migration/_generated/w3ts-3-to-reforged-ts-1";

/** The second major of the library, as the rename map writes the pair. */
const SECOND_PAIR = { from: "reforged-ts@1", to: "reforged-ts@2" };
const SECOND_PAGE = "website/docs/migration/reforged-ts-1-to-reforged-ts-2.md";

/** The fixture repository with `changes`: a file set, or removed if null. */
function changed(
  changes: Readonly<Record<string, string | null>>,
): Record<string, string> {
  const files: Record<string, string> = {};
  for (const [path, text] of Object.entries({
    ...REPOSITORY_FILES,
    ...changes,
  })) {
    if (text !== null) files[path] = text;
  }
  return files;
}

/** The fixture repository whose rename map holds `items`. */
const withRenames = (
  items: readonly unknown[],
  changes: Readonly<Record<string, string | null>> = {},
) => changed({ [`${MIGRATION}/renames.json`]: renamesJson(items), ...changes });

describe("the migration guide", () => {
  it("writes the table of every entry of the pair (old, new or removed, kind, note) as MDX text", async () => {
    const workspace = await fixture();
    await collect(workspace);
    expect(await readText(workspace.docs, `${PARTIALS}/renames.md`)).toBe(
      `{/* Generated by docs:collect from ${MIGRATION}/renames.json: edit the source, not this file. */}

:::note[Generated section]
This section is generated from [\`${MIGRATION}/renames.json\`](${GITHUB}/${MIGRATION}/renames.json) by \`docs:collect\`. Edit the source, not this section.
:::

| Old | New | Kind | Note |
| --- | --- | --- | --- |
| \`w3ts\` | \`reforged-ts\` | package | The library is published under a new name. |
| \`new Unit(...)\` | \`Unit.create(...)\` | constructor | Creation is a factory \\| the constructor is protected, as \`Handle<T>\`'s \\{was\\} \\<T>. |
| \`new Effect(...)\` | \`Effect.create(...)\`, \`Effect.createAttachment(...)\` | constructor | The overloads split by argument shape. |
| \`Group.getEnumUnit\` | removed | member | The enumeration callback receives the unit. |
`,
    );
  });

  it("writes the behaviour changes as sections of the page: the note's sections a level down, links rewritten", async () => {
    const workspace = await fixture();
    await collect(workspace);
    expect(
      await readText(workspace.docs, `${PARTIALS}/behaviour-changes.md`),
    ).toBe(
      `{/* Generated by docs:collect from ${MIGRATION}/behaviour-changes.md: edit the source, not this file. */}

:::note[Generated section]
This section is generated from [\`${MIGRATION}/behaviour-changes.md\`](${GITHUB}/${MIGRATION}/behaviour-changes.md) by \`docs:collect\`. Edit the source, not this section.
:::

### Build step 3: errors

- **Creation throws.** See [the Guards](${GITHUB}/website/docs/guides/desync-safety-and-guards.md#dev-mode) and [the tests](${GITHUB}/packages/reforged-ts/test/README.md).

\`\`\`md
## not a heading
\`\`\`

#### A detail

Text.
`,
    );
  });

  it("links a page of the docs tree from the behaviour changes by its path from the partial", async () => {
    const outside = await fixture();
    const workspace = { ...outside, docs: join(outside.root, "website/docs") };
    await collect(workspace);
    expect(
      await readText(workspace.docs, `${PARTIALS}/behaviour-changes.md`),
    ).toContain(
      "See [the Guards](../../../guides/desync-safety-and-guards.md#dev-mode)",
    );
  });

  it("reports the partials it wrote", async () => {
    const report = await collect(await fixture());
    expect(
      report.collected.find(({ source }) => source === "the migration guide")
        ?.paths,
    ).toEqual([`${PARTIALS}/renames.md`, `${PARTIALS}/behaviour-changes.md`]);
  });

  it("accepts the page as MDX", async () => {
    const workspace = await fixture(
      changed({ [FIRST_PAGE]: null, [`${FIRST_PAGE}x`]: MIGRATION_PAGE }),
    );
    await expect(collect(workspace)).resolves.toBeDefined();
  });

  it("writes the marker's note for a pair with the no-renames marker, without a table, and passes", async () => {
    const workspace = await fixture(
      withRenames(
        [
          ...RENAMES,
          {
            kind: "noRenames",
            versions: SECOND_PAIR,
            note: "The second major changes the defaults only.",
          },
        ],
        { [SECOND_PAGE]: "# reforged-ts 1 to 2\n" },
      ),
    );
    await collect(workspace);
    const partial = await readText(
      workspace.docs,
      "migration/_generated/reforged-ts-1-to-reforged-ts-2/renames.md",
    );
    expect(partial).toContain(
      "\n:::\n\nNo public symbol is removed or renamed from `reforged-ts@1` to `reforged-ts@2`. The second major changes the defaults only.\n",
    );
    expect(partial).not.toContain("| Old |");
  });

  it("fails naming an entry whose replacement the built declarations do not export", async () => {
    const workspace = await fixture(
      withRenames([
        ...RENAMES,
        renameEntry(
          "new Timer(...)",
          "Timer.create(...)",
          "constructor",
          "A factory.",
        ),
        renameEntry(
          "Unit.fromEvent",
          ["Unit.fromEvent", "Unit.triggering"],
          "member",
          "Split.",
        ),
      ]),
    );
    const failure = collect(workspace);
    await expect(failure).rejects.toThrow(CollectError);
    await expect(failure).rejects.toThrow(
      `- [ ] the migration guide: the replacement \`Timer.create(...)\` of \`new Timer(...)\` (w3ts@3 to reforged-ts@1) is not exported by \`${DECLARATIONS}\`.
- [ ] the migration guide: the replacement \`Unit.fromEvent\` of \`Unit.fromEvent\` (w3ts@3 to reforged-ts@1) is not exported by \`${DECLARATIONS}\`.
- [ ] the migration guide: the replacement \`Unit.triggering\` of \`Unit.fromEvent\` (w3ts@3 to reforged-ts@1) is not exported by \`${DECLARATIONS}\`.`,
    );
  });

  it("fails naming a version pair without a page", async () => {
    const workspace = await fixture(
      withRenames([
        ...RENAMES,
        renameEntry(
          "Unit.create",
          "Unit.create",
          "member",
          "Kept.",
          SECOND_PAIR,
        ),
      ]),
    );
    await expect(collect(workspace)).rejects.toThrow(
      `- [ ] the migration guide: reforged-ts@1 to reforged-ts@2 has no migration page: write \`${SECOND_PAGE}\`.`,
    );
  });

  it("fails naming a page without entries in the map or the pair's marker", async () => {
    const workspace = await fixture(
      changed({ [SECOND_PAGE]: "# reforged-ts 1 to 2\n" }),
    );
    await expect(collect(workspace)).rejects.toThrow(
      `- [ ] the migration guide: \`${SECOND_PAGE}\` is the page of no version pair of \`${MIGRATION}/renames.json\`: add the pair's entries or its no-renames marker to the map, or delete the page.`,
    );
  });

  it("fails naming the items of a map that does not match the schema next to it", async () => {
    const [first, ...rest] = RENAMES;
    const workspace = await fixture(
      withRenames([{ ...first, note: undefined }, ...rest]),
    );
    await expect(collect(workspace)).rejects.toThrow(
      `- [ ] the migration guide: \`${MIGRATION}/renames.json\`: The rename map does not match its schema:\n/0 must have required property 'note'`,
    );
  });

  it("fails when the library is not built, naming its declaration entry", async () => {
    const workspace = await fixture(changed({ [DECLARATIONS]: null }));
    await expect(collect(workspace)).rejects.toThrow(
      `- [ ] the migration guide: \`${DECLARATIONS}\` does not exist: build the library first (\`pnpm build\`), the replacements of the map are checked against its declarations.`,
    );
  });

  it("leaves the docs tree as it was when it fails", async () => {
    const workspace = await fixture(
      changed({ [SECOND_PAGE]: "# reforged-ts 1 to 2\n" }),
    );
    await expect(collect(workspace)).rejects.toThrow(CollectError);
    await expect(
      readText(workspace.docs, `${PARTIALS}/renames.md`),
    ).rejects.toThrow();
  });
});
