/**
 * Seam 1: the files a generation writes besides the three declaration files,
 * namely the entry of the game version, `async-natives.json` and the
 * manifest of the Patch.
 */
import { describe, expect, it } from "vitest";
import { generate } from "../src/index.js";
import { entry, globalEntry, writeFixture } from "./support/fixture.js";

async function generateOk(...args: Parameters<typeof writeFixture>) {
  const result = await generate(await writeFixture(...args));
  if (!result.ok) {
    throw new Error(
      "generation failed:\n" +
        result.diagnostics.map((d) => d.message).join("\n")
    );
  }
  return result;
}

describe("generate: output paths", () => {
  it("writes the declarations, the manifest, the entry and async-natives.json", async () => {
    const result = await generateOk({});

    expect([...result.files.keys()]).toEqual([
      "3.0.0/common.j.d.ts",
      "3.0.0/blizzard.j.d.ts",
      "3.0.0/common.ai.d.ts",
      "3.0.0/manifest.json",
      "3.0.0.d.ts",
      "async-natives.json",
    ]);
  });
});

describe("generate: the entry of the game version", () => {
  it("references lua-types, the Lua runtime and the common.j and blizzard.j outputs, never common.ai", async () => {
    const result = await generateOk({});

    expect(result.files.get("3.0.0.d.ts")).toBe(
      [
        "/** @noSelfInFile */",
        "// Generated by reforged-types: the entry of game version 3.0.0, Patch 3.0.0.24268.",
        "// Source: jass-history tag Reforged-v3.0.0.24268-w3-3a9d8f2, commit a392fc3d5e6c37980accbfc560b28387fc7d01bc.",
        "// Do not edit: curate the Overlay, then run `pnpm --filter reforged-types typings:generate`.",
        "// common.ai is not referenced here: add `reforged-types/3.0.0/common.ai` to `types` to use it.",
        '/// <reference types="lua-types/5.3" resolution-mode="require" />',
        '/// <reference path="./lua-runtime.d.ts" />',
        '/// <reference path="./3.0.0/common.j.d.ts" />',
        '/// <reference path="./3.0.0/blizzard.j.d.ts" />',
        "",
      ].join("\n")
    );
  });
});

describe("generate: async-natives.json", () => {
  it("lists the async functions of every source by name in code-point order", async () => {
    const result = await generateOk(
      {
        "common.j": [
          "native GetLocalPlayer takes nothing returns player",
          "native CreateUnit takes nothing returns unit",
          "native BlzGetLocalUnitZ takes nothing returns real",
          "native GetCameraTargetPositionX takes nothing returns real",
        ].join("\n"),
        "blizzard.j":
          "function GetCurrentCameraBoundsMapRectBJ takes nothing returns rect\nendfunction\n",
      },
      [
        { ...entry("common.j", "GetLocalPlayer"), async: true },
        { ...entry("common.j", "CreateUnit"), async: false },
        { ...entry("common.j", "BlzGetLocalUnitZ"), async: true },
        entry("common.j", "GetCameraTargetPositionX"),
        { ...entry("blizzard.j", "GetCurrentCameraBoundsMapRectBJ"), async: true },
      ]
    );

    expect(result.files.get("async-natives.json")).toBe(
      [
        "[",
        '  "BlzGetLocalUnitZ",',
        '  "GetCurrentCameraBoundsMapRectBJ",',
        '  "GetLocalPlayer"',
        "]",
        "",
      ].join("\n")
    );
  });

  it("is an empty array when no function is async", async () => {
    const result = await generateOk({});

    expect(result.files.get("async-natives.json")).toBe("[]\n");
  });
});

describe("generate: the manifest of the Patch", () => {
  it("lists every function and global, one per line in source order, with its Jass types and Overlay facts", async () => {
    const result = await generateOk(
      {
        "common.j": [
          "type agent extends handle",
          "type unit extends agent",
          "globals",
          "    constant integer MAX = 24",
          "endglobals",
          "constant native ConvertRace takes integer i returns race",
          "native CreateUnit takes player id, integer unitid returns unit",
          "native GetLocalPlayer takes nothing returns player",
        ].join("\n"),
        "blizzard.j": [
          "globals",
          "    force array bj_FORCE_PLAYER",
          "    unit bj_lastCreatedUnit = null",
          "endglobals",
          "function Noop takes nothing returns nothing",
          "endfunction",
        ].join("\n"),
      },
      [
        globalEntry("common.j", "MAX", false, { since: "3.0.0.24268" }),
        entry("common.j", "ConvertRace", ["i"]),
        {
          ...entry("common.j", "CreateUnit", ["id", "unitid?"], true),
          deprecated: "Use CreateUnitEx.",
          since: "3.0.0.24268",
        },
        { ...entry("common.j", "GetLocalPlayer"), async: true },
        globalEntry("blizzard.j", "bj_FORCE_PLAYER", true),
        globalEntry("blizzard.j", "bj_lastCreatedUnit", true, {
          deprecated: "GUI only.",
        }),
        entry("blizzard.j", "Noop"),
      ]
    );

    expect(result.files.get("3.0.0/manifest.json")).toBe(
      [
        "{",
        '  "patch": "3.0.0.24268",',
        '  "entries": [',
        '    {"name":"MAX","source":"common.j","kind":"global","constant":true,"array":false,"type":"integer","nullable":false,"since":"3.0.0.24268","deprecated":null},',
        '    {"name":"ConvertRace","source":"common.j","kind":"native","constant":true,"params":[{"name":"i","type":"integer","nullable":false}],"returns":{"type":"race","nullable":false},"async":false,"since":null,"deprecated":null},',
        '    {"name":"CreateUnit","source":"common.j","kind":"native","constant":false,"params":[{"name":"id","type":"player","nullable":false},{"name":"unitid","type":"integer","nullable":true}],"returns":{"type":"unit","nullable":true},"async":false,"since":"3.0.0.24268","deprecated":"Use CreateUnitEx."},',
        '    {"name":"GetLocalPlayer","source":"common.j","kind":"native","constant":false,"params":[],"returns":{"type":"player","nullable":false},"async":true,"since":null,"deprecated":null},',
        '    {"name":"bj_FORCE_PLAYER","source":"blizzard.j","kind":"global","constant":false,"array":true,"type":"force","nullable":true,"since":null,"deprecated":null},',
        '    {"name":"bj_lastCreatedUnit","source":"blizzard.j","kind":"global","constant":false,"array":false,"type":"unit","nullable":true,"since":null,"deprecated":"GUI only."},',
        '    {"name":"Noop","source":"blizzard.j","kind":"function","constant":false,"params":[],"returns":{"type":"nothing","nullable":false},"async":false,"since":null,"deprecated":null}',
        "  ]",
        "}",
        "",
      ].join("\n")
    );
  });

  it("is valid JSON with an empty list when the Patch declares no function or global", async () => {
    const result = await generateOk({ "common.j": "type agent extends handle\n" });
    const text = result.files.get("3.0.0/manifest.json")!;

    expect(JSON.parse(text)).toEqual({ patch: "3.0.0.24268", entries: [] });
    expect(text).toBe('{\n  "patch": "3.0.0.24268",\n  "entries": []\n}\n');
  });
});
