import { describe, expect, it } from "vitest";
import { generate } from "../src/index.js";
import { entry, writeFixture } from "./support/fixture.js";

const banner = (source: string) =>
  [
    "/** @noSelfInFile */",
    `// Generated by reforged-types from ${source} of Patch 3.0.0.24268.`,
    "// Source: jass-history tag Reforged-v3.0.0.24268-w3-3a9d8f2, commit a392fc3d5e6c37980accbfc560b28387fc7d01bc.",
    "// Do not edit: curate the Overlay, then run `pnpm --filter reforged-types typings:generate`.",
  ].join("\n");

async function generateOk(...args: Parameters<typeof writeFixture>) {
  const result = await generate(await writeFixture(...args));
  if (!result.ok) {
    throw new Error(
      "generation failed:\n" +
        result.diagnostics.map((d) => d.message).join("\n")
    );
  }
  return result;
}

describe("generate: declaration file shape", () => {
  it("emits types and natives of common.j as the editor shows them", async () => {
    const commonJ = [
      "//============================================================================",
      "// Native types.",
      "//",
      "type agent\t\t\t    extends     handle  // all reference counted objects",
      "type unit               extends     agent",
      "",
      "constant native ConvertRace                 takes integer i returns race",
      "native GetLocalPlayer takes nothing returns player",
      "native CreateUnit takes player id, integer unitid, real x, real y, real face returns unit // trailing",
    ].join("\n");

    const result = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "ConvertRace", ["i"]),
      entry("common.j", "GetLocalPlayer"),
      entry("common.j", "CreateUnit", ["id", "unitid", "x", "y", "face"], true),
    ]);

    expect(result.files.get("3.0.0/common.j.d.ts")).toBe(
      [
        banner("common.j"),
        "",
        "declare interface handle { __handle: never }",
        "type code = (this: void) => void;",
        "type boolcode = (this: void) => boolean;",
        "",
        "declare interface agent extends handle { __agent: never }",
        "declare interface unit extends agent { __unit: never }",
        "",
        "/**",
        " * @param i - integer (32-bit)",
        " * @returns race",
        " * @see {@link https://lep.duckdns.org/jassbot/doc/ConvertRace}",
        " */",
        "declare function ConvertRace(i: number): race;",
        "",
        "/**",
        " * @returns player",
        " * @see {@link https://lep.duckdns.org/jassbot/doc/GetLocalPlayer}",
        " */",
        "declare function GetLocalPlayer(): player;",
        "",
        "/**",
        " * @param id - player",
        " * @param unitid - integer (32-bit)",
        " * @param x - real",
        " * @param y - real",
        " * @param face - real",
        " * @returns unit",
        " * @see {@link https://lep.duckdns.org/jassbot/doc/CreateUnit}",
        " */",
        "declare function CreateUnit(id: player, unitid: number, x: number, y: number, face: number): unit | undefined;",
        "",
      ].join("\n")
    );
    expect(result.diagnostics).toEqual([]);
  });

  it("emits one file per source, each with the banner, in the game-version folder", async () => {
    const result = await generateOk({
      "common.j": "type agent extends handle\n",
    });

    expect([...result.files.keys()]).toEqual([
      "3.0.0/common.j.d.ts",
      "3.0.0/blizzard.j.d.ts",
      "3.0.0/common.ai.d.ts",
    ]);
    expect(result.files.get("3.0.0/blizzard.j.d.ts")).toBe(
      banner("blizzard.j") + "\n"
    );
    expect(result.files.get("3.0.0/common.ai.d.ts")).toBe(
      banner("common.ai") + "\n"
    );
  });

  it("declares the code alias only in the common.j output", async () => {
    const result = await generateOk(
      {
        "blizzard.j":
          "function Noop takes nothing returns nothing\nendfunction\n",
      },
      [entry("blizzard.j", "Noop")]
    );

    expect(result.files.get("3.0.0/common.j.d.ts")).toContain(
      "type code = (this: void) => void;"
    );
    expect(result.files.get("3.0.0/blizzard.j.d.ts")).not.toContain(
      "type code"
    );
  });

  it("skips function bodies up to endfunction and keeps source order across kinds", async () => {
    const blizzardJ = [
      "function First takes nothing returns nothing",
      "    local integer i = 0 // a body line the parser never reads",
      '    call Second(i, "function Fake takes nothing returns nothing")',
      "endfunction",
      "",
      "\tfunction Second takes integer count, string label returns boolean",
      "    return true",
      "  endfunction  // trailing comment",
    ].join("\n");

    const result = await generateOk({ "blizzard.j": blizzardJ }, [
      entry("blizzard.j", "First"),
      entry("blizzard.j", "Second", ["count", "label"]),
    ]);

    const text = result.files.get("3.0.0/blizzard.j.d.ts")!;
    expect(text).toContain("declare function First(): void;");
    expect(text).toContain(
      "declare function Second(count: number, label: string): boolean;"
    );
    expect(text).not.toContain("Fake");
    expect(text.indexOf("First(")).toBeLessThan(text.indexOf("Second("));
  });

  it("maps Jass types: integer and real to number, code to the alias, handles by name", async () => {
    const commonJ = [
      "type timer extends handle",
      "native TimerStart takes timer whichTimer, real timeout, boolean periodic, code handlerFunc returns nothing",
      "native Handle takes handle h, string s returns integer",
    ].join("\n");

    const result = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "TimerStart", [
        "whichTimer",
        "timeout",
        "periodic",
        "handlerFunc",
      ]),
      entry("common.j", "Handle", ["h", "s"]),
    ]);

    const text = result.files.get("3.0.0/common.j.d.ts")!;
    expect(text).toContain(
      "declare function TimerStart(whichTimer: timer, timeout: number, periodic: boolean, handlerFunc: code): void;"
    );
    expect(text).toContain(
      " * @param handlerFunc - code\n * @returns nothing\n"
    );
    expect(text).toContain(
      "declare function Handle(h: handle, s: string): number;"
    );
    expect(text).toContain(" * @returns integer (32-bit)\n");
  });

  it("accepts a last line without a final newline", async () => {
    const result = await generateOk(
      {
        "common.j":
          "type agent extends handle\nnative Last takes nothing returns nothing",
      },
      [entry("common.j", "Last")]
    );

    expect(result.files.get("3.0.0/common.j.d.ts")).toContain(
      "declare function Last(): void;\n"
    );
  });

  it("emits LF only and identical bytes on two generations", async () => {
    const fixture = await writeFixture(
      {
        "common.j":
          "type agent extends handle\r\nnative A takes agent a returns agent\r\n",
        "blizzard.j": "function B takes nothing returns nothing\nendfunction\n",
      },
      [entry("common.j", "A", ["a?"], true), entry("blizzard.j", "B")]
    );

    const first = await generate(fixture);
    const second = await generate(fixture);

    expect(first).toEqual(second);
    expect(first.ok).toBe(true);
    for (const text of first.ok ? first.files.values() : []) {
      expect(text).not.toContain("\r");
      expect(text.endsWith("\n")).toBe(true);
    }
  });
});

describe("generate: Overlay nullability", () => {
  const commonJ = [
    "type unit extends handle",
    "type boolexpr extends handle",
    "native Pick takes unit a, boolexpr filter, integer n returns unit",
  ].join("\n");

  it("appends | undefined to a nullable return only", async () => {
    const nullable = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "Pick", ["a", "filter", "n"], true),
    ]);
    const plain = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "Pick", ["a", "filter", "n"], false),
    ]);

    expect(nullable.files.get("3.0.0/common.j.d.ts")).toContain(
      "declare function Pick(a: unit, filter: boolexpr, n: number): unit | undefined;"
    );
    expect(plain.files.get("3.0.0/common.j.d.ts")).toContain(
      "declare function Pick(a: unit, filter: boolexpr, n: number): unit;"
    );
  });

  it("makes nullable trailing parameters optional", async () => {
    const result = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "Pick", ["a", "filter?", "n?"]),
    ]);

    expect(result.files.get("3.0.0/common.j.d.ts")).toContain(
      "declare function Pick(a: unit, filter?: boolexpr, n?: number): unit;"
    );
  });

  it("types a nullable parameter before a non-nullable one as T | undefined", async () => {
    const result = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "Pick", ["a?", "filter?", "n"]),
    ]);

    expect(result.files.get("3.0.0/common.j.d.ts")).toContain(
      "declare function Pick(a: unit | undefined, filter: boolexpr | undefined, n: number): unit;"
    );
  });

  it("keeps the Jass type in the header of a nullable parameter", async () => {
    const result = await generateOk({ "common.j": commonJ }, [
      entry("common.j", "Pick", ["a", "filter?", "n?"], true),
    ]);

    expect(result.files.get("3.0.0/common.j.d.ts")).toContain(
      [
        " * @param a - unit",
        " * @param filter - boolexpr",
        " * @param n - integer (32-bit)",
        " * @returns unit",
      ].join("\n")
    );
  });
});
