// Generated by reforged-builtins from the Built-in objects of Game version 3.0.0 (3.0.0/index.json).
// Derived identifiers only: Rawcodes, Object kinds, races, enUS names and Game data sets.
// Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.
// The names and Rawcodes are derived from the game's data and are not licensed by this package.
// Never edited by hand: `pnpm builtins:generate` writes it and `pnpm builtins:check` compares it.

/**
 * The Built-in buffs of Patch 3.0.0, each named by its enUS name and Rawcode, such as `Buffs.StarfallTarget_AEsd`.
 */
export declare const Buffs: {
  /**
   * Starfall (Target) (`AEsd`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly StarfallTarget_AEsd: Rawcode<"buff">;

  /**
   * Tranquility (Target) (`AEtr`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly TranquilityTarget_AEtr: Rawcode<"buff">;

  /**
   * Monsoon (`ANmd`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Monsoon_ANmd: Rawcode<"buff">;

  /**
   * Poisoned Arrows (`BApa`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly PoisonedArrows_BApa: Rawcode<"buff">;

  /**
   * Chronomancy (`BCGb`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Chronomancy_BCGb: Rawcode<"buff">;

  /**
   * Breath of Frost (`BCbf`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly BreathOfFrost_BCbf: Rawcode<"buff">;

  /**
   * Slam (`BCtc`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Slam_BCtc: Rawcode<"buff">;

  /**
   * Dark Commander's Presence (`BDCa`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly DarkCommandersPresence_BDCa: Rawcode<"buff">;

  /**
   * Dark Mistress' Presence (`BDMa`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly DarkMistressPresence_BDMa: Rawcode<"buff">;

  /**
   * Thorns Aura (`BEah`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly ThornsAura_BEah: Rawcode<"buff">;

  /**
   * Trueshot Aura (`BEar`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly TrueshotAura_BEar: Rawcode<"buff">;

  /**
   * Entangling Roots (`BEer`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly EntanglingRoots_BEer: Rawcode<"buff">;

  /**
   * Force of Nature (`BEfn`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly ForceOfNature_BEfn: Rawcode<"buff">;

  /**
   * Immolation (Caster) (`BEia`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly ImmolationCaster_BEia: Rawcode<"buff">;

  /**
   * Immolation (`BEim`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Immolation_BEim: Rawcode<"buff">;

  /**
   * Metamorphosis (`BEme`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Metamorphosis_BEme: Rawcode<"buff">;

  /**
   * Shadow Strike (`BEsh`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly ShadowStrike_BEsh: Rawcode<"buff">;

  /**
   * Scout (`BEst`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Scout_BEst: Rawcode<"buff">;

  /**
   * Vengeance (`BEsv`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Vengeance_BEsv: Rawcode<"buff">;

  /**
   * Summoned Unit (`BFig`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SummonedUnit_BFig: Rawcode<"buff">;

  /**
   * Templar's Flame (`BHTf`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly TemplarsFlame_BHTf: Rawcode<"buff">;

  /**
   * Apprehend (`BHaa`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Apprehend_BHaa: Rawcode<"buff">;

  /**
   * Brilliance Aura (`BHab`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly BrillianceAura_BHab: Rawcode<"buff">;

  /**
   * Devotion Aura (`BHad`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DevotionAura_BHad: Rawcode<"buff">;

  /**
   * Apprehend (`BHag`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Apprehend_BHag: Rawcode<"buff">;

  /**
   * Avatar Of Light (`BHal`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly AvatarOfLight_BHal: Rawcode<"buff">;

  /**
   * Apprehend (`BHap`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Apprehend_BHap: Rawcode<"buff">;

  /**
   * Sacred Aura (`BHas`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SacredAura_BHas: Rawcode<"buff">;

  /**
   * Avatar (`BHav`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Avatar_BHav: Rawcode<"buff">;

  /**
   * Blizzard (`BHbd`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Blizzard_BHbd: Rawcode<"buff">;

  /**
   * Banish (`BHbn`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Banish_BHbn: Rawcode<"buff">;

  /**
   * Unyielding Guard Bonus (`BHbo`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly UnyieldingGuardBonus_BHbo: Rawcode<"buff">;

  /**
   * Unyielding Guard (`BHbt`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly UnyieldingGuard_BHbt: Rawcode<"buff">;

  /**
   * Blizzard (Caster) (`BHbz`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly BlizzardCaster_BHbz: Rawcode<"buff">;

  /**
   * Cold Arrows (`BHca`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ColdArrows_BHca: Rawcode<"buff">;

  /**
   * Consecration (`BHce`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Consecration_BHce: Rawcode<"buff">;

  /**
   * Consecration (`BHcf`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Consecration_BHcf: Rawcode<"buff">;

  /**
   * Valiant Charge (`BHch`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly ValiantCharge_BHch: Rawcode<"buff">;

  /**
   * Cleansing Fire (`BHcl`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly CleansingFire_BHcl: Rawcode<"buff">;

  /**
   * Divine Shield (`BHds`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DivineShield_BHds: Rawcode<"buff">;

  /**
   * Flame Strike (`BHfs`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly FlameStrike_BHfs: Rawcode<"buff">;

  /**
   * Guiding Hand (`BHgh`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly GuidingHand_BHgh: Rawcode<"buff">;

  /**
   * Grit (`BHgr`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Grit_BHgr: Rawcode<"buff">;

  /**
   * Guiding Hand (`BHgu`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly GuidingHand_BHgu: Rawcode<"buff">;

  /**
   * Provoke (`BHhc`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Provoke_BHhc: Rawcode<"buff">;

  /**
   * Headsplitter (`BHhh`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Headsplitter_BHhh: Rawcode<"buff">;

  /**
   * Headsplitter (`BHhr`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Headsplitter_BHhr: Rawcode<"buff">;

  /**
   * Provoke (`BHht`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Provoke_BHht: Rawcode<"buff">;

  /**
   * Inspire Courage (`BHic`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly InspireCourage_BHic: Rawcode<"buff">;

  /**
   * Mind Control (`BHmc`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly MindControl_BHmc: Rawcode<"buff">;

  /**
   * Holy Wrath (`BHpb`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly HolyWrath_BHpb: Rawcode<"buff">;

  /**
   * Surge of Light (`BHsa`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SurgeOfLight_BHsa: Rawcode<"buff">;

  /**
   * Light's Mercy (`BHsf`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly LightsMercy_BHsf: Rawcode<"buff">;

  /**
   * Surge of Light (`BHss`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SurgeOfLight_BHss: Rawcode<"buff">;

  /**
   * Bleed (`BHsw`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Bleed_BHsw: Rawcode<"buff">;

  /**
   * Thunder Clap (`BHtc`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly ThunderClap_BHtc: Rawcode<"buff">;

  /**
   * Warcry (`BHw1`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Warcry_BHw1: Rawcode<"buff">;

  /**
   * Warcry (`BHw2`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Warcry_BHw2: Rawcode<"buff">;

  /**
   * Warcry (`BHw3`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Warcry_BHw3: Rawcode<"buff">;

  /**
   * Warcry (`BHwc`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Warcry_BHwc: Rawcode<"buff">;

  /**
   * Water Elemental (`BHwe`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly WaterElemental_BHwe: Rawcode<"buff">;

  /**
   * Corruption (`BIc2`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Corruption_BIc2: Rawcode<"buff">;

  /**
   * Corruption (`BIc3`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Corruption_BIc3: Rawcode<"buff">;

  /**
   * Corruption (`BIc5`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Corruption_BIc5: Rawcode<"buff">;

  /**
   * Corruption (`BIcb`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Corruption_BIcb: Rawcode<"buff">;

  /**
   * Cloak of Flames (`BIcf`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly CloakOfFlames_BIcf: Rawcode<"buff">;

  /**
   * Terrified! (`BIee`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Terrified_BIee: Rawcode<"buff">;

  /**
   * Heal Reduction (`BIhm`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default and Custom Game data sets. Not in the Melee Game data set.
   */
  readonly HealReduction_BIhm: Rawcode<"buff">;

  /**
   * Illusion (`BIil`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Illusion_BIil: Rawcode<"buff">;

  /**
   * Smashed! (`BImc`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Smashed_BImc: Rawcode<"buff">;

  /**
   * Monster Lure (`BImo`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly MonsterLure_BImo: Rawcode<"buff">;

  /**
   * Vampiric Potion (`BIpv`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly VampiricPotion_BIpv: Rawcode<"buff">;

  /**
   * Queen's Hunger (`BIqh`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly QueensHunger_BIqh: Rawcode<"buff">;

  /**
   * Reborn (`BIrb`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Reborn_BIrb: Rawcode<"buff">;

  /**
   * Rejuvenation (`BIrg`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Rejuvenation_BIrg: Rawcode<"buff">;

  /**
   * Regeneration (`BIrl`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Regeneration_BIrl: Rawcode<"buff">;

  /**
   * Clarity Potion (`BIrm`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ClarityPotion_BIrm: Rawcode<"buff">;

  /**
   * Aura of Decay (`BIsd`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly AuraOfDecay_BIsd: Rawcode<"buff">;

  /**
   * Headhunter Spirit (`BIsh`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly HeadhunterSpirit_BIsh: Rawcode<"buff">;

  /**
   * Summoned Unit (`BIsu`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SummonedUnit_BIsu: Rawcode<"buff">;

  /**
   * Soul Theft (`BIsv`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SoulTheft_BIsv: Rawcode<"buff">;

  /**
   * Item Web (`BIwb`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ItemWeb_BIwb: Rawcode<"buff">;

  /**
   * Acid Bomb (`BNab`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly AcidBomb_BNab: Rawcode<"buff">;

  /**
   * Black Arrow (`BNba`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly BlackArrow_BNba: Rawcode<"buff">;

  /**
   * Breath of Fire (`BNbf`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly BreathOfFire_BNbf: Rawcode<"buff">;

  /**
   * Battle Roar (`BNbr`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly BattleRoar_BNbr: Rawcode<"buff">;

  /**
   * Clockwerk Goblin (`BNcg`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ClockwerkGoblin_BNcg: Rawcode<"buff">;

  /**
   * Chemical Rage (`BNcr`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ChemicalRage_BNcr: Rawcode<"buff">;

  /**
   * Cluster Rockets (`BNcs`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ClusterRockets_BNcs: Rawcode<"buff">;

  /**
   * Dark Conversion (`BNdc`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly DarkConversion_BNdc: Rawcode<"buff">;

  /**
   * Drunken Haze (`BNdh`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly DrunkenHaze_BNdh: Rawcode<"buff">;

  /**
   * Doom (`BNdi`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Doom_BNdi: Rawcode<"buff">;

  /**
   * Dark Minion (`BNdm`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly DarkMinion_BNdm: Rawcode<"buff">;

  /**
   * Doom (`BNdo`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Doom_BNdo: Rawcode<"buff">;

  /**
   * Pandaren Elemental (`BNef`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly PandarenElemental_BNef: Rawcode<"buff">;

  /**
   * Engineering Upgrade (`BNeg`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly EngineeringUpgrade_BNeg: Rawcode<"buff">;

  /**
   * Pocket Factory (`BNfy`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly PocketFactory_BNfy: Rawcode<"buff">;

  /**
   * Healing Spray (`BNhs`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly HealingSpray_BNhs: Rawcode<"buff">;

  /**
   * Howl of Terror (`BNht`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly HowlOfTerror_BNht: Rawcode<"buff">;

  /**
   * Incinerate (`BNic`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Incinerate_BNic: Rawcode<"buff">;

  /**
   * Infernal (`BNin`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Infernal_BNin: Rawcode<"buff">;

  /**
   * Lava Spawn (`BNlm`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly LavaSpawn_BNlm: Rawcode<"buff">;

  /**
   * Mind Rot (`BNmr`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly MindRot_BNmr: Rawcode<"buff">;

  /**
   * Mana Shield (`BNms`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ManaShield_BNms: Rawcode<"buff">;

  /**
   * Parasite (`BNpa`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Parasite_BNpa: Rawcode<"buff">;

  /**
   * Permanent Immolation (`BNpi`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly PermanentImmolation_BNpi: Rawcode<"buff">;

  /**
   * Parasite (`BNpm`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Parasite_BNpm: Rawcode<"buff">;

  /**
   * Rain of Fire (`BNrd`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly RainOfFire_BNrd: Rawcode<"buff">;

  /**
   * Rain of Fire (Area) (`BNrf`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly RainOfFireArea_BNrf: Rawcode<"buff">;

  /**
   * Righteous Fury (`BNrs`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly RighteousFury_BNrs: Rawcode<"buff">;

  /**
   * Sanctuary (`BNsa`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Sanctuary_BNsa: Rawcode<"buff">;

  /**
   * Bear (`BNsg`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Bear_BNsg: Rawcode<"buff">;

  /**
   * Silence (`BNsi`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Silence_BNsi: Rawcode<"buff">;

  /**
   * Soul Preservation (`BNsl`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SoulPreservation_BNsl: Rawcode<"buff">;

  /**
   * Soul Burn (`BNso`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SoulBurn_BNso: Rawcode<"buff">;

  /**
   * Quilbeast (`BNsq`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Quilbeast_BNsq: Rawcode<"buff">;

  /**
   * Spell Shield (`BNss`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SpellShield_BNss: Rawcode<"buff">;

  /**
   * Stampede (`BNst`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Stampede_BNst: Rawcode<"buff">;

  /**
   * Hawk (`BNsw`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Hawk_BNsw: Rawcode<"buff">;

  /**
   * Transmute (`BNtm`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Transmute_BNtm: Rawcode<"buff">;

  /**
   * Tornado (`BNto`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Tornado_BNto: Rawcode<"buff">;

  /**
   * Volcano (Area) (`BNva`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly VolcanoArea_BNva: Rawcode<"buff">;

  /**
   * Volcano (`BNvc`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Volcano_BNvc: Rawcode<"buff">;

  /**
   * Watery Minion (`BNwm`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly WateryMinion_BNwm: Rawcode<"buff">;

  /**
   * `BOac`, unnamed, a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Unnamed_BOac: Rawcode<"buff">;

  /**
   * Endurance Aura (`BOae`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly EnduranceAura_BOae: Rawcode<"buff">;

  /**
   * Earthquake (Caster) (`BOea`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly EarthquakeCaster_BOea: Rawcode<"buff">;

  /**
   * Earthquake (`BOeq`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Earthquake_BOeq: Rawcode<"buff">;

  /**
   * Hex (`BOhx`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Hex_BOhx: Rawcode<"buff">;

  /**
   * Mirror Image (`BOmi`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly MirrorImage_BOmi: Rawcode<"buff">;

  /**
   * Feral Spirit (`BOsf`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly FeralSpirit_BOsf: Rawcode<"buff">;

  /**
   * Shockwave (Caster) (`BOsh`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly ShockwaveCaster_BOsh: Rawcode<"buff">;

  /**
   * Big Bad Voodoo (Caster) (`BOvc`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BigBadVoodooCaster_BOvc: Rawcode<"buff">;

  /**
   * Big Bad Voodoo (`BOvd`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BigBadVoodoo_BOvd: Rawcode<"buff">;

  /**
   * Ward (`BOwd`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Ward_BOwd: Rawcode<"buff">;

  /**
   * Wind Walk (`BOwk`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly WindWalk_BOwk: Rawcode<"buff">;

  /**
   * Bladestorm (Caster) (`BOww`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BladestormCaster_BOww: Rawcode<"buff">;

  /**
   * Stunned (`BPSE`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Stunned_BPSE: Rawcode<"buff">;

  /**
   * Stunned (`BSTN`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Stunned_BSTN: Rawcode<"buff">;

  /**
   * Animate Dead (Extra) (`BUad`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly AnimateDeadExtra_BUad: Rawcode<"buff">;

  /**
   * Animate Dead (`BUan`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly AnimateDead_BUan: Rawcode<"buff">;

  /**
   * Unholy Aura (`BUau`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly UnholyAura_BUau: Rawcode<"buff">;

  /**
   * Vampiric Aura (`BUav`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly VampiricAura_BUav: Rawcode<"buff">;

  /**
   * Undying Defiance Bonus (`BUbo`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly UndyingDefianceBonus_BUbo: Rawcode<"buff">;

  /**
   * Battering Ram (`BUbr`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly BatteringRam_BUbr: Rawcode<"buff">;

  /**
   * Undying Defiance (`BUbt`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly UndyingDefiance_BUbt: Rawcode<"buff">;

  /**
   * Carrion Beetles (`BUcb`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly CarrionBeetles_BUcb: Rawcode<"buff">;

  /**
   * Carrion Swarm (Caster) (`BUcs`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly CarrionSwarmCaster_BUcs: Rawcode<"buff">;

  /**
   * Deathseeker Arrows (`BUdb`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly DeathseekerArrows_BUdb: Rawcode<"buff">;

  /**
   * Death and Decay (`BUdd`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly DeathAndDecay_BUdd: Rawcode<"buff">;

  /**
   * Frost Armor (`BUfa`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly FrostArmor_BUfa: Rawcode<"buff">;

  /**
   * Impale (`BUim`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Impale_BUim: Rawcode<"buff">;

  /**
   * Soul Lantern (`BUla`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SoulLantern_BUla: Rawcode<"buff">;

  /**
   * Soul Lantern (`BUlc`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SoulLantern_BUlc: Rawcode<"buff">;

  /**
   * Soul Lantern (`BUle`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly SoulLantern_BUle: Rawcode<"buff">;

  /**
   * Sleep (`BUsl`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Sleep_BUsl: Rawcode<"buff">;

  /**
   * Sleep (Pause) (`BUsp`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly SleepPause_BUsp: Rawcode<"buff">;

  /**
   * Sleep (Stun) (`BUst`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly SleepStun_BUst: Rawcode<"buff">;

  /**
   * Spiked Carapace (`BUts`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly SpikedCarapace_BUts: Rawcode<"buff">;

  /**
   * `BUtt`, unnamed, a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Unnamed_BUtt: Rawcode<"buff">;

  /**
   * Grim Conviction (`BUvg`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly GrimConviction_BUvg: Rawcode<"buff">;

  /**
   * Withering Fire (`BUwf`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly WitheringFire_BUwf: Rawcode<"buff">;

  /**
   * Aura of Blight (`Babr`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly AuraOfBlight_Babr: Rawcode<"buff">;

  /**
   * Raise the Banner (`Baca`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly RaiseTheBanner_Baca: Rawcode<"buff">;

  /**
   * Enveloping Darkness (`Badx`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly EnvelopingDarkness_Badx: Rawcode<"buff">;

  /**
   * War Drums (`Bakb`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly WarDrums_Bakb: Rawcode<"buff">;

  /**
   * Anti-magic Shell (`Bam2`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly AntiMagicShell_Bam2: Rawcode<"buff">;

  /**
   * Anti-magic Shell (`Bams`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly AntiMagicShell_Bams: Rawcode<"buff">;

  /**
   * Disease (`Bapl`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Disease_Bapl: Rawcode<"buff">;

  /**
   * Mana Regeneration Aura (`Barm`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly ManaRegenerationAura_Barm: Rawcode<"buff">;

  /**
   * Tornado (`Basl`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Tornado_Basl: Rawcode<"buff">;

  /**
   * Barkskin (`Bbar`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Barkskin_Bbar: Rawcode<"buff">;

  /**
   * Twisted Bones (`Bbcs`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly TwistedBones_Bbcs: Rawcode<"buff">;

  /**
   * Bloodlust (`Bblo`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Bloodlust_Bblo: Rawcode<"buff">;

  /**
   * Burning Oil (`Bbof`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BurningOil_Bbof: Rawcode<"buff">;

  /**
   * Berserk (`Bbsk`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Berserk_Bbsk: Rawcode<"buff">;

  /**
   * Dizziness (`Bchd`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Dizziness_Bchd: Rawcode<"buff">;

  /**
   * Cloud (`Bclf`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Cloud_Bclf: Rawcode<"buff">;

  /**
   * Control Magic (`Bcmg`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly ControlMagic_Bcmg: Rawcode<"buff">;

  /**
   * Corrosive Breath (`Bcor`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly CorrosiveBreath_Bcor: Rawcode<"buff">;

  /**
   * Cripple (`Bcri`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Cripple_Bcri: Rawcode<"buff">;

  /**
   * Curse (`Bcrs`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Curse_Bcrs: Rawcode<"buff">;

  /**
   * Cold Arrows (`Bcsd`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ColdArrows_Bcsd: Rawcode<"buff">;

  /**
   * Cold Arrows (`Bcsi`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ColdArrows_Bcsi: Rawcode<"buff">;

  /**
   * Cyclone (`Bcy2`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Cyclone_Bcy2: Rawcode<"buff">;

  /**
   * Cyclone (`Bcyc`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Cyclone_Bcyc: Rawcode<"buff">;

  /**
   * Plague (`Bdb1`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Plague_Bdb1: Rawcode<"buff">;

  /**
   * Drain Life & Mana (Caster) (`Bdcb`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DrainLifeManaCaster_Bdcb: Rawcode<"buff">;

  /**
   * Drain Life (Caster) (`Bdcl`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DrainLifeCaster_Bdcl: Rawcode<"buff">;

  /**
   * Drain Mana (Caster) (`Bdcm`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DrainManaCaster_Bdcm: Rawcode<"buff">;

  /**
   * Scroll of Protection (`Bdef`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ScrollOfProtection_Bdef: Rawcode<"buff">;

  /**
   * Armor Reduction (`Bder`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly ArmorReduction_Bder: Rawcode<"buff">;

  /**
   * Dust of Appearance (`Bdet`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly DustOfAppearance_Bdet: Rawcode<"buff">;

  /**
   * Devour (Caster) (`Bdig`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly DevourCaster_Bdig: Rawcode<"buff">;

  /**
   * Drain Life & Mana (Target) (`Bdtb`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DrainLifeManaTarget_Bdtb: Rawcode<"buff">;

  /**
   * Drain Life (Target) (`Bdtl`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DrainLifeTarget_Bdtl: Rawcode<"buff">;

  /**
   * Drain Mana (Target) (`Bdtm`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly DrainManaTarget_Bdtm: Rawcode<"buff">;

  /**
   * Devour (`Bdvv`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Devour_Bdvv: Rawcode<"buff">;

  /**
   * Eat Tree (`Beat`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly EatTree_Beat: Rawcode<"buff">;

  /**
   * Ensnare (`Bena`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Ensnare_Bena: Rawcode<"buff">;

  /**
   * Ensnare (`Beng`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Ensnare_Beng: Rawcode<"buff">;

  /**
   * Ensnare (General) (`Bens`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly EnsnareGeneral_Bens: Rawcode<"buff">;

  /**
   * Sentry Ward (`Beye`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly SentryWard_Beye: Rawcode<"buff">;

  /**
   * Faerie Fire (`Bfae`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly FaerieFire_Bfae: Rawcode<"buff">;

  /**
   * Chemical Frenzy (`Bfcf`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly ChemicalFrenzy_Bfcf: Rawcode<"buff">;

  /**
   * Freeze (`Bfre`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Freeze_Bfre: Rawcode<"buff">;

  /**
   * Slowed (`Bfro`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Slowed_Bfro: Rawcode<"buff">;

  /**
   * Freezing Breath (`Bfrz`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly FreezingBreath_Bfrz: Rawcode<"buff">;

  /**
   * Frenzy (`Bfzy`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Frenzy_Bfzy: Rawcode<"buff">;

  /**
   * Curse of Sloth (`Bggs`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly CurseOfSloth_Bggs: Rawcode<"buff">;

  /**
   * Unfathomable Rage (`Bggw`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly UnfathomableRage_Bggw: Rawcode<"buff">;

  /**
   * Pride's Downfall (`Bggx`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly PridesDownfall_Bggx: Rawcode<"buff">;

  /**
   * Echoing Flame (`Bgr1`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly EchoingFlame_Bgr1: Rawcode<"buff">;

  /**
   * Echoing Flame (`Bgr2`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly EchoingFlame_Bgr2: Rawcode<"buff">;

  /**
   * War Club (`Bgra`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly WarClub_Bgra: Rawcode<"buff">;

  /**
   * Heal (`Bhea`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Heal_Bhea: Rawcode<"buff">;

  /**
   * Consecration Aura (`Bhhi`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly ConsecrationAura_Bhhi: Rawcode<"buff">;

  /**
   * Slowed (`Bhrz`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Slowed_Bhrz: Rawcode<"buff">;

  /**
   * Healing Ward (`Bhwd`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly HealingWard_Bhwd: Rawcode<"buff">;

  /**
   * Inner Fire (`Binf`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly InnerFire_Binf: Rawcode<"buff">;

  /**
   * Invisibility (`Binv`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Invisibility_Binv: Rawcode<"buff">;

  /**
   * Invisibility (Extra) (`Bivs`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly InvisibilityExtra_Bivs: Rawcode<"buff">;

  /**
   * Liquid Fire (`Bliq`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly LiquidFire_Bliq: Rawcode<"buff">;

  /**
   * Lightning Shield (Caster) (`Blsa`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly LightningShieldCaster_Blsa: Rawcode<"buff">;

  /**
   * Lightning Shield (`Blsh`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly LightningShield_Blsh: Rawcode<"buff">;

  /**
   * Banshee's Wail (`Bmda`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly BansheesWail_Bmda: Rawcode<"buff">;

  /**
   * Mechanical Critter (`Bmec`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly MechanicalCritter_Bmec: Rawcode<"buff">;

  /**
   * Mana Flare (`Bmfa`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly ManaFlare_Bmfa: Rawcode<"buff">;

  /**
   * Mana Flare (`Bmfl`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly ManaFlare_Bmfl: Rawcode<"buff">;

  /**
   * Militia (`Bmil`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Militia_Bmil: Rawcode<"buff">;

  /**
   * Aerial Shackles (Caster) (`Bmlc`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly AerialShacklesCaster_Bmlc: Rawcode<"buff">;

  /**
   * Aerial Shackles (`Bmlt`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly AerialShackles_Bmlt: Rawcode<"buff">;

  /**
   * Blinded (`Bmss`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Blinded_Bmss: Rawcode<"buff">;

  /**
   * Healing Ward Aura (`Boar`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly HealingWardAura_Boar: Rawcode<"buff">;

  /**
   * Phoenix (`Bphx`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Phoenix_Bphx: Rawcode<"buff">;

  /**
   * Permanent Immolation (`Bpig`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly PermanentImmolation_Bpig: Rawcode<"buff">;

  /**
   * Disease Cloud (`Bplg`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly DiseaseCloud_Bplg: Rawcode<"buff">;

  /**
   * Polymorph (`Bply`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Polymorph_Bply: Rawcode<"buff">;

  /**
   * Possession (Caster) (`Bpoc`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly PossessionCaster_Bpoc: Rawcode<"buff">;

  /**
   * Poison (`Bpoi`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Poison_Bpoi: Rawcode<"buff">;

  /**
   * Possession (`Bpos`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Possession_Bpos: Rawcode<"buff">;

  /**
   * Purge (`Bprg`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly Purge_Bprg: Rawcode<"buff">;

  /**
   * `Bps1`, unnamed, a Built-in buff of Patch 3.0.0, race nightelf.
   *
   * In the Default and Custom Game data sets. Not in the Melee Game data set.
   */
  readonly Unnamed_Bps1: Rawcode<"buff">;

  /**
   * Poison (`Bpsd`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Poison_Bpsd: Rawcode<"buff">;

  /**
   * Phase Shift (`Bpsh`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly PhaseShift_Bpsh: Rawcode<"buff">;

  /**
   * Poison (Info) (`Bpsi`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly PoisonInfo_Bpsi: Rawcode<"buff">;

  /**
   * Phoenix Fire (`Bpxf`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly PhoenixFire_Bpxf: Rawcode<"buff">;

  /**
   * Skeletal Minion (`Brai`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly SkeletalMinion_Brai: Rawcode<"buff">;

  /**
   * Rejuvenation (`Brej`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Rejuvenation_Brej: Rawcode<"buff">;

  /**
   * Brimstone (`Brim`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Brimstone_Brim: Rawcode<"buff">;

  /**
   * Roar (`Broa`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Roar_Broa: Rawcode<"buff">;

  /**
   * Replenish (`Brpb`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Replenish_Brpb: Rawcode<"buff">;

  /**
   * Essence of Blight (`Brpl`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly EssenceOfBlight_Brpl: Rawcode<"buff">;

  /**
   * Spirit Touch (`Brpm`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly SpiritTouch_Brpm: Rawcode<"buff">;

  /**
   * Holy Fire (`Bsci`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly HolyFire_Bsci: Rawcode<"buff">;

  /**
   * Light Struck (`Bsg1`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly LightStruck_Bsg1: Rawcode<"buff">;

  /**
   * Shared Vision (`Bsha`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SharedVision_Bsha: Rawcode<"buff">;

  /**
   * Wand of Shadowsight (`Bshs`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly WandOfShadowsight_Bshs: Rawcode<"buff">;

  /**
   * Slow (`Bslo`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly Slow_Bslo: Rawcode<"buff">;

  /**
   * Freezing Presence (`Bsof`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly FreezingPresence_Bsof: Rawcode<"buff">;

  /**
   * Orb of Slow (`Bson`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly OrbOfSlow_Bson: Rawcode<"buff">;

  /**
   * Spiderling (`Bspa`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Spiderling_Bspa: Rawcode<"buff">;

  /**
   * Speed Bonus (`Bspe`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly SpeedBonus_Bspe: Rawcode<"buff">;

  /**
   * Spirit Link (`Bspl`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly SpiritLink_Bspl: Rawcode<"buff">;

  /**
   * Slow Poison (`Bspo`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly SlowPoison_Bspo: Rawcode<"buff">;

  /**
   * Slow Poison (`Bssd`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly SlowPoison_Bssd: Rawcode<"buff">;

  /**
   * Slow Poison (Info) (`Bssi`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly SlowPoisonInfo_Bssi: Rawcode<"buff">;

  /**
   * Stasis Trap (`Bstt`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly StasisTrap_Bstt: Rawcode<"buff">;

  /**
   * Taunt (`Btab`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Taunt_Btab: Rawcode<"buff">;

  /**
   * Taunt (`Btad`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Taunt_Btad: Rawcode<"buff">;

  /**
   * Taunt (`Btau`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Taunt_Btau: Rawcode<"buff">;

  /**
   * Blinded (`Btbd`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Blinded_Btbd: Rawcode<"buff">;

  /**
   * Tornado Damage (`Btdg`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly TornadoDamage_Btdg: Rawcode<"buff">;

  /**
   * Magic Missile (`Btkt`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly MagicMissile_Btkt: Rawcode<"buff">;

  /**
   * Teleport Reveal (`Btrv`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly TeleportReveal_Btrv: Rawcode<"buff">;

  /**
   * Tornado Spin (Area) (`Btsa`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly TornadoSpinArea_Btsa: Rawcode<"buff">;

  /**
   * Tornado Spin (`Btsp`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly TornadoSpin_Btsp: Rawcode<"buff">;

  /**
   * Unholy Frenzy (`Buhf`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly UnholyFrenzy_Buhf: Rawcode<"buff">;

  /**
   * Infected (`Buic`), a Built-in buff of Patch 3.0.0, race other.
   *
   * In the Default Game data set. Not in the Custom and Melee Game data sets.
   */
  readonly Infected_Buic: Rawcode<"buff">;

  /**
   * Ultravision (`Bult`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Ultravision_Bult: Rawcode<"buff">;

  /**
   * Unsummon (`Buns`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Unsummon_Buns: Rawcode<"buff">;

  /**
   * Spirit of Vengeance (`Bvng`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly SpiritOfVengeance_Bvng: Rawcode<"buff">;

  /**
   * Invulnerable (`Bvul`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly Invulnerable_Bvul: Rawcode<"buff">;

  /**
   * Web (`Bwea`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Web_Bwea: Rawcode<"buff">;

  /**
   * Web (`Bweb`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly Web_Bweb: Rawcode<"buff">;

  /**
   * Rain of Chaos (Effect) (`XErc`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly RainOfChaosEffect_XErc: Rawcode<"buff">;

  /**
   * Rain of Fire (Effect) (`XErf`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly RainOfFireEffect_XErf: Rawcode<"buff">;

  /**
   * Starfall (Effect) (`XEsf`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly StarfallEffect_XEsf: Rawcode<"buff">;

  /**
   * Tranquility (Effect) (`XEtq`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly TranquilityEffect_XEtq: Rawcode<"buff">;

  /**
   * Blizzard (Effect) (`XHbz`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly BlizzardEffect_XHbz: Rawcode<"buff">;

  /**
   * Flame Strike (Effect) (`XHfs`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly FlameStrikeEffect_XHfs: Rawcode<"buff">;

  /**
   * Item Change Time of Day (`XIct`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ItemChangeTimeOfDay_XIct: Rawcode<"buff">;

  /**
   * Cluster Rockets (Effect) (`XNcs`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly ClusterRocketsEffect_XNcs: Rawcode<"buff">;

  /**
   * Healing Spray (Effect) (`XNhs`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly HealingSprayEffect_XNhs: Rawcode<"buff">;

  /**
   * Monsoon (Effect) (`XNmo`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly MonsoonEffect_XNmo: Rawcode<"buff">;

  /**
   * Volcano (Effect) (`XNvc`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly VolcanoEffect_XNvc: Rawcode<"buff">;

  /**
   * Earthquake (Effect) (`XOeq`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly EarthquakeEffect_XOeq: Rawcode<"buff">;

  /**
   * Reincarnation (Effect) (`XOre`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly ReincarnationEffect_XOre: Rawcode<"buff">;

  /**
   * Death And Decay (Effect) (`XUdd`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly DeathAndDecayEffect_XUdd: Rawcode<"buff">;

  /**
   * Reveal (Effect) (`Xbdt`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly RevealEffect_Xbdt: Rawcode<"buff">;

  /**
   * Blight (Effect) (`Xbli`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly BlightEffect_Xbli: Rawcode<"buff">;

  /**
   * Burning Oil (Effect) (`Xbof`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BurningOilEffect_Xbof: Rawcode<"buff">;

  /**
   * Cloud (Effect) (`Xclf`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly CloudEffect_Xclf: Rawcode<"buff">;

  /**
   * Hero Dissipate (Effect) (`Xdis`), a Built-in buff of Patch 3.0.0, race other.
   */
  readonly HeroDissipateEffect_Xdis: Rawcode<"buff">;

  /**
   * `Xesn`, unnamed, a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly Unnamed_Xesn: Rawcode<"buff">;

  /**
   * Building Damage - Human Large (`Xfhl`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly BuildingDamageHumanLarge_Xfhl: Rawcode<"buff">;

  /**
   * Building Damage - Human Medium (`Xfhm`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly BuildingDamageHumanMedium_Xfhm: Rawcode<"buff">;

  /**
   * Building Damage - Human Small (`Xfhs`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly BuildingDamageHumanSmall_Xfhs: Rawcode<"buff">;

  /**
   * Flare (Effect) (`Xfla`), a Built-in buff of Patch 3.0.0, race human.
   */
  readonly FlareEffect_Xfla: Rawcode<"buff">;

  /**
   * Building Damage - Night Elf Large (`Xfnl`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly BuildingDamageNightElfLarge_Xfnl: Rawcode<"buff">;

  /**
   * Building Damage - Night Elf Medium (`Xfnm`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly BuildingDamageNightElfMedium_Xfnm: Rawcode<"buff">;

  /**
   * Building Damage - Night Elf Small (`Xfns`), a Built-in buff of Patch 3.0.0, race nightelf.
   */
  readonly BuildingDamageNightElfSmall_Xfns: Rawcode<"buff">;

  /**
   * Building Damage - Orc Large (`Xfol`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BuildingDamageOrcLarge_Xfol: Rawcode<"buff">;

  /**
   * Building Damage - Orc Medium (`Xfom`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BuildingDamageOrcMedium_Xfom: Rawcode<"buff">;

  /**
   * Building Damage - Orc Small (`Xfos`), a Built-in buff of Patch 3.0.0, race orc.
   */
  readonly BuildingDamageOrcSmall_Xfos: Rawcode<"buff">;

  /**
   * Building Damage - Undead Large (`Xful`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly BuildingDamageUndeadLarge_Xful: Rawcode<"buff">;

  /**
   * Building Damage - Undead Medium (`Xfum`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly BuildingDamageUndeadMedium_Xfum: Rawcode<"buff">;

  /**
   * Building Damage - Undead Small (`Xfus`), a Built-in buff of Patch 3.0.0, race undead.
   */
  readonly BuildingDamageUndeadSmall_Xfus: Rawcode<"buff">;
};
