// Generated by reforged-builtins from the Built-in objects of Game version 3.0.0 (3.0.0/index.json).
// Derived identifiers only: Rawcodes, Object kinds, races, enUS names and Game data sets.
// Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.
// The names and Rawcodes are derived from the game's data and are not licensed by this package.
// Never edited by hand: `pnpm builtins:generate` writes it and `pnpm builtins:check` compares it.

/**
 * The Built-in destructables of Patch 3.0.0, each named by its enUS name and Rawcode, such as `Destructables.DemonicGate_ATg1`.
 */
export declare const Destructables: {
  /**
   * Demonic Gate (`ATg1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DemonicGate_ATg1: Rawcode<"destructable">;

  /**
   * Demonic Gate (`ATg2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DemonicGate_ATg2: Rawcode<"destructable">;

  /**
   * Demonic Gate (`ATg3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DemonicGate_ATg3: Rawcode<"destructable">;

  /**
   * Demonic Gate (`ATg4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DemonicGate_ATg4: Rawcode<"destructable">;

  /**
   * Tree Bridge (`ATt0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_ATt0: Rawcode<"destructable">;

  /**
   * Tree Bridge (`ATt1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_ATt1: Rawcode<"destructable">;

  /**
   * Ashenvale Canopy Tree (`ATtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly AshenvaleCanopyTree_ATtc: Rawcode<"destructable">;

  /**
   * Ashenvale Tree Wall (`ATtr`), a Built-in destructable of Patch 3.0.0.
   */
  readonly AshenvaleTreeWall_ATtr: Rawcode<"destructable">;

  /**
   * Wharf (`ATwf`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Wharf_ATwf: Rawcode<"destructable">;

  /**
   * Resurrection Stone (`BTrs`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ResurrectionStone_BTrs: Rawcode<"destructable">;

  /**
   * Resurrection Stone (`BTrx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ResurrectionStone_BTrx: Rawcode<"destructable">;

  /**
   * Lordaeron City Main Gate Column Destroyed (`BTs1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityMainGateColumnDestroyed_BTs1: Rawcode<"destructable">;

  /**
   * Lion Statue (`BTs2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LionStatue_BTs2: Rawcode<"destructable">;

  /**
   * Lion Statue Destroyed (`BTs3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LionStatueDestroyed_BTs3: Rawcode<"destructable">;

  /**
   * Lordaeron City Spire (`BTs4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCitySpire_BTs4: Rawcode<"destructable">;

  /**
   * Lordaeron City Spire Destroyed (`BTs5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCitySpireDestroyed_BTs5: Rawcode<"destructable">;

  /**
   * Support Column (`BTsc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly SupportColumn_BTsc: Rawcode<"destructable">;

  /**
   * Lordaeron City Main Gate Column (`BTsk`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityMainGateColumn_BTsk: Rawcode<"destructable">;

  /**
   * Barrens Canopy Tree (`BTtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly BarrensCanopyTree_BTtc: Rawcode<"destructable">;

  /**
   * Barrens Tree Wall (`BTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly BarrensTreeWall_BTtw: Rawcode<"destructable">;

  /**
   * Felwood Canopy Tree (`CTtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly FelwoodCanopyTree_CTtc: Rawcode<"destructable">;

  /**
   * Felwood Tree Wall (`CTtr`), a Built-in destructable of Patch 3.0.0.
   */
  readonly FelwoodTreeWall_CTtr: Rawcode<"destructable">;

  /**
   * Cliff Cave Gate (`DTc1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CliffCaveGate_DTc1: Rawcode<"destructable">;

  /**
   * Cliff Cave Gate (`DTc2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CliffCaveGate_DTc2: Rawcode<"destructable">;

  /**
   * Elevator Wall (`DTep`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ElevatorWall_DTep: Rawcode<"destructable">;

  /**
   * Egg Sack (`DTes`), a Built-in destructable of Patch 3.0.0.
   */
  readonly EggSack_DTes: Rawcode<"destructable">;

  /**
   * Foot Switch (`DTfp`), a Built-in destructable of Patch 3.0.0.
   */
  readonly FootSwitch_DTfp: Rawcode<"destructable">;

  /**
   * Foot Switch (`DTfx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly FootSwitch_DTfx: Rawcode<"destructable">;

  /**
   * Dungeon Gate (`DTg1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DungeonGate_DTg1: Rawcode<"destructable">;

  /**
   * Dungeon Gate (`DTg2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DungeonGate_DTg2: Rawcode<"destructable">;

  /**
   * Dungeon Gate (`DTg3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DungeonGate_DTg3: Rawcode<"destructable">;

  /**
   * Dungeon Gate (`DTg4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DungeonGate_DTg4: Rawcode<"destructable">;

  /**
   * Iron Gate (`DTg5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IronGate_DTg5: Rawcode<"destructable">;

  /**
   * Iron Gate (`DTg6`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IronGate_DTg6: Rawcode<"destructable">;

  /**
   * Iron Gate (`DTg7`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IronGate_DTg7: Rawcode<"destructable">;

  /**
   * Iron Gate (`DTg8`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IronGate_DTg8: Rawcode<"destructable">;

  /**
   * Lever (`DTlv`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Lever_DTlv: Rawcode<"destructable">;

  /**
   * Rock Chunks (`DTrc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RockChunks_DTrc: Rawcode<"destructable">;

  /**
   * Elevator (`DTrf`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Elevator_DTrf: Rawcode<"destructable">;

  /**
   * Elevator (`DTrx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Elevator_DTrx: Rawcode<"destructable">;

  /**
   * Force Bridge (`DTs0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ForceBridge_DTs0: Rawcode<"destructable">;

  /**
   * Force Bridge (`DTs1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ForceBridge_DTs1: Rawcode<"destructable">;

  /**
   * Force Bridge (`DTs2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ForceBridge_DTs2: Rawcode<"destructable">;

  /**
   * Force Bridge (`DTs3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ForceBridge_DTs3: Rawcode<"destructable">;

  /**
   * Dungeon Tree Wall (`DTsh`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DungeonTreeWall_DTsh: Rawcode<"destructable">;

  /**
   * Dungeon Spikes (`DTsp`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DungeonSpikes_DTsp: Rawcode<"destructable">;

  /**
   * ForceWall (`Dofv`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ForceWall_Dofv: Rawcode<"destructable">;

  /**
   * ForceWall (`Dofw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ForceWall_Dofw: Rawcode<"destructable">;

  /**
   * Green Force Wall (`Dogv`), a Built-in destructable of Patch 3.0.0.
   */
  readonly GreenForceWall_Dogv: Rawcode<"destructable">;

  /**
   * Green Force Wall (`Dogw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly GreenForceWall_Dogw: Rawcode<"destructable">;

  /**
   * Short Elven Bridge (`EB00`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortElvenBridge_EB00: Rawcode<"destructable">;

  /**
   * Short Elven Bridge (`EB01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortElvenBridge_EB01: Rawcode<"destructable">;

  /**
   * Short Elven Bridge (`EB02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortElvenBridge_EB02: Rawcode<"destructable">;

  /**
   * Short Elven Bridge (`EB03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortElvenBridge_EB03: Rawcode<"destructable">;

  /**
   * Long Elven Bridge (`EB04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongElvenBridge_EB04: Rawcode<"destructable">;

  /**
   * Long Elven Bridge (`EB05`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongElvenBridge_EB05: Rawcode<"destructable">;

  /**
   * Long Elven Bridge (`EB06`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongElvenBridge_EB06: Rawcode<"destructable">;

  /**
   * Long Elven Bridge (`EB07`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongElvenBridge_EB07: Rawcode<"destructable">;

  /**
   * Wide Elven Bridge (`EB08`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideElvenBridge_EB08: Rawcode<"destructable">;

  /**
   * Wide Elven Bridge (`EB09`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideElvenBridge_EB09: Rawcode<"destructable">;

  /**
   * Wide Elven Bridge (`EB10`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideElvenBridge_EB10: Rawcode<"destructable">;

  /**
   * Wide Elven Bridge (`EB11`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideElvenBridge_EB11: Rawcode<"destructable">;

  /**
   * Fall Tree Wall (`FTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly FallTreeWall_FTtw: Rawcode<"destructable">;

  /**
   * Underground Tree Wall (`GTsh`), a Built-in destructable of Patch 3.0.0.
   */
  readonly UndergroundTreeWall_GTsh: Rawcode<"destructable">;

  /**
   * Icecrown Throne (`IOt0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcecrownThrone_IOt0: Rawcode<"destructable">;

  /**
   * Icecrown Throne (Diagonal 1) (`IOt1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcecrownThroneDiagonal1_IOt1: Rawcode<"destructable">;

  /**
   * Icecrown Throne (Diagonal 1) (`IOt2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcecrownThroneDiagonal1_IOt2: Rawcode<"destructable">;

  /**
   * Rockin Arthas (`ITag`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RockinArthas_ITag: Rawcode<"destructable">;

  /**
   * Icey Rock (`ITcr`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceyRock_ITcr: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ITd1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ITd1: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ITd2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ITd2: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ITd3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ITd3: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ITd4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ITd4: Rawcode<"destructable">;

  /**
   * Ice Floe (`ITf1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceFloe_ITf1: Rawcode<"destructable">;

  /**
   * Ice Floe (`ITf2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceFloe_ITf2: Rawcode<"destructable">;

  /**
   * Ice Floe (`ITf3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceFloe_ITf3: Rawcode<"destructable">;

  /**
   * Ice Floe (`ITf4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceFloe_ITf4: Rawcode<"destructable">;

  /**
   * Icy Gate (`ITg1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcyGate_ITg1: Rawcode<"destructable">;

  /**
   * Icy Gate (`ITg2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcyGate_ITg2: Rawcode<"destructable">;

  /**
   * Icy Gate (`ITg3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcyGate_ITg3: Rawcode<"destructable">;

  /**
   * Icy Gate (`ITg4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcyGate_ITg4: Rawcode<"destructable">;

  /**
   * Ice Bridge (`ITi2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceBridge_ITi2: Rawcode<"destructable">;

  /**
   * Ice Bridge (`ITi3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceBridge_ITi3: Rawcode<"destructable">;

  /**
   * Ice Bridge (`ITi4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceBridge_ITi4: Rawcode<"destructable">;

  /**
   * Ice Bridge (`ITib`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceBridge_ITib: Rawcode<"destructable">;

  /**
   * Igloo (`ITig`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Igloo_ITig: Rawcode<"destructable">;

  /**
   * Icecrown Canopy Tree (`ITtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcecrownCanopyTree_ITtc: Rawcode<"destructable">;

  /**
   * Frozen Throne Gate (`ITtg`), a Built-in destructable of Patch 3.0.0.
   */
  readonly FrozenThroneGate_ITtg: Rawcode<"destructable">;

  /**
   * Icecrown Tree Wall (`ITtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcecrownTreeWall_ITtw: Rawcode<"destructable">;

  /**
   * Stone Wall (`ITw0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ITw0: Rawcode<"destructable">;

  /**
   * Stone Wall (`ITw1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ITw1: Rawcode<"destructable">;

  /**
   * Stone Wall (`ITw2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ITw2: Rawcode<"destructable">;

  /**
   * Stone Wall (`ITw3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ITw3: Rawcode<"destructable">;

  /**
   * Ice Rock Gate (`ITx1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceRockGate_ITx1: Rawcode<"destructable">;

  /**
   * Ice Rock Gate (`ITx2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceRockGate_ITx2: Rawcode<"destructable">;

  /**
   * Ice Rock Gate (`ITx3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceRockGate_ITx3: Rawcode<"destructable">;

  /**
   * Ice Rock Gate (`ITx4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IceRockGate_ITx4: Rawcode<"destructable">;

  /**
   * Cityscape Ruined Tree Wall (`JTct`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityscapeRuinedTreeWall_JTct: Rawcode<"destructable">;

  /**
   * Dalaran Ruins Tree Wall (`JTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DalaranRuinsTreeWall_JTtw: Rawcode<"destructable">;

  /**
   * Black Citadel Tree Wall (`KTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly BlackCitadelTreeWall_KTtw: Rawcode<"destructable">;

  /**
   * Cage (`LOcg`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Cage_LOcg: Rawcode<"destructable">;

  /**
   * Short Wooden Bridge (`LT00`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortWoodenBridge_LT00: Rawcode<"destructable">;

  /**
   * Short Wooden Bridge (`LT01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortWoodenBridge_LT01: Rawcode<"destructable">;

  /**
   * Short Wooden Bridge (`LT02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortWoodenBridge_LT02: Rawcode<"destructable">;

  /**
   * Short Wooden Bridge (`LT03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortWoodenBridge_LT03: Rawcode<"destructable">;

  /**
   * Long Wooden Bridge (`LT04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongWoodenBridge_LT04: Rawcode<"destructable">;

  /**
   * Long Wooden Bridge (`LT05`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongWoodenBridge_LT05: Rawcode<"destructable">;

  /**
   * Long Wooden Bridge (`LT06`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongWoodenBridge_LT06: Rawcode<"destructable">;

  /**
   * Long Wooden Bridge (`LT07`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongWoodenBridge_LT07: Rawcode<"destructable">;

  /**
   * Wide Wooden Bridge (`LT08`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideWoodenBridge_LT08: Rawcode<"destructable">;

  /**
   * Wide Wooden Bridge (`LT09`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideWoodenBridge_LT09: Rawcode<"destructable">;

  /**
   * Wide Wooden Bridge (`LT10`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideWoodenBridge_LT10: Rawcode<"destructable">;

  /**
   * Wide Wooden Bridge (`LT11`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideWoodenBridge_LT11: Rawcode<"destructable">;

  /**
   * Barricade (`LTba`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Barricade_LTba: Rawcode<"destructable">;

  /**
   * Barrel (`LTbr`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Barrel_LTbr: Rawcode<"destructable">;

  /**
   * Barrel (`LTbs`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Barrel_LTbs: Rawcode<"destructable">;

  /**
   * Barrel (`LTbx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Barrel_LTbx: Rawcode<"destructable">;

  /**
   * Crates (`LTcr`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Crates_LTcr: Rawcode<"destructable">;

  /**
   * Elven Gate (`LTe1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ElvenGate_LTe1: Rawcode<"destructable">;

  /**
   * Elven Gate (`LTe2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ElvenGate_LTe2: Rawcode<"destructable">;

  /**
   * Elven Gate (`LTe3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ElvenGate_LTe3: Rawcode<"destructable">;

  /**
   * Elven Gate (`LTe4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ElvenGate_LTe4: Rawcode<"destructable">;

  /**
   * Barrel of Explosives (`LTex`), a Built-in destructable of Patch 3.0.0.
   */
  readonly BarrelOfExplosives_LTex: Rawcode<"destructable">;

  /**
   * Gate (`LTg1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Gate_LTg1: Rawcode<"destructable">;

  /**
   * Gate (`LTg2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Gate_LTg2: Rawcode<"destructable">;

  /**
   * Gate (`LTg3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Gate_LTg3: Rawcode<"destructable">;

  /**
   * Gate (`LTg4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Gate_LTg4: Rawcode<"destructable">;

  /**
   * Summer Tree Wall (`LTlt`), a Built-in destructable of Patch 3.0.0.
   */
  readonly SummerTreeWall_LTlt: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr1: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr2: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr3: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr4: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr5: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr6`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr6: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr7`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr7: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTr8`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTr8: Rawcode<"destructable">;

  /**
   * Rock Chunks (`LTrc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RockChunks_LTrc: Rawcode<"destructable">;

  /**
   * Rock Chunks (`LTrt`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RockChunks_LTrt: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs1: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs2: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs3: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs4: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs5: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs6`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs6: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs7`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs7: Rawcode<"destructable">;

  /**
   * Stone Ramp (`LTs8`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneRamp_LTs8: Rawcode<"destructable">;

  /**
   * Tree Bridge (`LTt0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_LTt0: Rawcode<"destructable">;

  /**
   * Tree Bridge (`LTt1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_LTt1: Rawcode<"destructable">;

  /**
   * Tree Bridge (`LTt2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_LTt2: Rawcode<"destructable">;

  /**
   * Tree Bridge (`LTt3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_LTt3: Rawcode<"destructable">;

  /**
   * Tree Bridge (`LTt4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_LTt4: Rawcode<"destructable">;

  /**
   * Tree Bridge (`LTt5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly TreeBridge_LTt5: Rawcode<"destructable">;

  /**
   * Last Hope Bridge (`LTtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LastHopeBridge_LTtc: Rawcode<"destructable">;

  /**
   * Last Hope Bridge (`LTtx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LastHopeBridge_LTtx: Rawcode<"destructable">;

  /**
   * Stone Wall (`LTw0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_LTw0: Rawcode<"destructable">;

  /**
   * Stone Wall (`LTw1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_LTw1: Rawcode<"destructable">;

  /**
   * Stone Wall (`LTw2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_LTw2: Rawcode<"destructable">;

  /**
   * Stone Wall (`LTw3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_LTw3: Rawcode<"destructable">;

  /**
   * Short Night Elven Wooden Bridge (`NB00`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNightElvenWoodenBridge_NB00: Rawcode<"destructable">;

  /**
   * Short Night Elven Wooden Bridge (`NB01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNightElvenWoodenBridge_NB01: Rawcode<"destructable">;

  /**
   * Short Night Elven Wooden Bridge (`NB02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNightElvenWoodenBridge_NB02: Rawcode<"destructable">;

  /**
   * Short Night Elven Wooden Bridge (`NB03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNightElvenWoodenBridge_NB03: Rawcode<"destructable">;

  /**
   * Long Night Elven Wooden Bridge (`NB04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNightElvenWoodenBridge_NB04: Rawcode<"destructable">;

  /**
   * Long Night Elven Wooden Bridge (`NB05`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNightElvenWoodenBridge_NB05: Rawcode<"destructable">;

  /**
   * Long Night Elven Wooden Bridge (`NB06`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNightElvenWoodenBridge_NB06: Rawcode<"destructable">;

  /**
   * Long Night Elven Wooden Bridge (`NB07`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNightElvenWoodenBridge_NB07: Rawcode<"destructable">;

  /**
   * Wide Night Elven Wooden Bridge (`NB08`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNightElvenWoodenBridge_NB08: Rawcode<"destructable">;

  /**
   * Wide Night Elven Wooden Bridge (`NB09`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNightElvenWoodenBridge_NB09: Rawcode<"destructable">;

  /**
   * Wide Night Elven Wooden Bridge (`NB10`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNightElvenWoodenBridge_NB10: Rawcode<"destructable">;

  /**
   * Wide Night Elven Wooden Bridge (`NB11`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNightElvenWoodenBridge_NB11: Rawcode<"destructable">;

  /**
   * Ship (`NTbd`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Ship_NTbd: Rawcode<"destructable">;

  /**
   * Northrend Icy Tree Wall (`NTiw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly NorthrendIcyTreeWall_NTiw: Rawcode<"destructable">;

  /**
   * Northrend Canopy Tree (`NTtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly NorthrendCanopyTree_NTtc: Rawcode<"destructable">;

  /**
   * Northrend Tree Wall (`NTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly NorthrendTreeWall_NTtw: Rawcode<"destructable">;

  /**
   * Short Overgrown Bridge (`OG00`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortOvergrownBridge_OG00: Rawcode<"destructable">;

  /**
   * Short Overgrown Bridge (`OG01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortOvergrownBridge_OG01: Rawcode<"destructable">;

  /**
   * Short Overgrown Bridge (`OG02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortOvergrownBridge_OG02: Rawcode<"destructable">;

  /**
   * Short Overgrown Bridge (`OG03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortOvergrownBridge_OG03: Rawcode<"destructable">;

  /**
   * Long Overgrown Bridge (`OG04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongOvergrownBridge_OG04: Rawcode<"destructable">;

  /**
   * Long Overgrown Bridge (`OG05`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongOvergrownBridge_OG05: Rawcode<"destructable">;

  /**
   * Long Overgrown Bridge (`OG06`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongOvergrownBridge_OG06: Rawcode<"destructable">;

  /**
   * Long Overgrown Bridge (`OG07`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongOvergrownBridge_OG07: Rawcode<"destructable">;

  /**
   * Wide Overgrown Bridge (`OG08`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideOvergrownBridge_OG08: Rawcode<"destructable">;

  /**
   * Wide Overgrown Bridge (`OG09`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideOvergrownBridge_OG09: Rawcode<"destructable">;

  /**
   * Wide Overgrown Bridge (`OG10`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideOvergrownBridge_OG10: Rawcode<"destructable">;

  /**
   * Wide Overgrown Bridge (`OG11`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideOvergrownBridge_OG11: Rawcode<"destructable">;

  /**
   * Demon Storm (`OTds`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DemonStorm_OTds: Rawcode<"destructable">;

  /**
   * Invisible Platform (`OTip`), a Built-in destructable of Patch 3.0.0.
   */
  readonly InvisiblePlatform_OTip: Rawcode<"destructable">;

  /**
   * Invisible Platform (small) (`OTis`), a Built-in destructable of Patch 3.0.0.
   */
  readonly InvisiblePlatformSmall_OTis: Rawcode<"destructable">;

  /**
   * Shimmering Portal (`OTsp`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShimmeringPortal_OTsp: Rawcode<"destructable">;

  /**
   * Outland Tree Wall (`OTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly OutlandTreeWall_OTtw: Rawcode<"destructable">;

  /**
   * Short Rickety Wooden Bridge (`RW00`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortRicketyWoodenBridge_RW00: Rawcode<"destructable">;

  /**
   * Short Rickety Wooden Bridge (`RW01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortRicketyWoodenBridge_RW01: Rawcode<"destructable">;

  /**
   * Short Rickety Wooden Bridge (`RW02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortRicketyWoodenBridge_RW02: Rawcode<"destructable">;

  /**
   * Short Rickety Wooden Bridge (`RW03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortRicketyWoodenBridge_RW03: Rawcode<"destructable">;

  /**
   * Long Rickety Wooden Bridge (`RW04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongRicketyWoodenBridge_RW04: Rawcode<"destructable">;

  /**
   * Long Rickety Wooden Bridge (`RW05`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongRicketyWoodenBridge_RW05: Rawcode<"destructable">;

  /**
   * Long Rickety Wooden Bridge (`RW06`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongRicketyWoodenBridge_RW06: Rawcode<"destructable">;

  /**
   * Long Rickety Wooden Bridge (`RW07`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongRicketyWoodenBridge_RW07: Rawcode<"destructable">;

  /**
   * Wide Rickety Wooden Bridge (`RW08`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideRicketyWoodenBridge_RW08: Rawcode<"destructable">;

  /**
   * Wide Rickety Wooden Bridge (`RW09`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideRicketyWoodenBridge_RW09: Rawcode<"destructable">;

  /**
   * Wide Rickety Wooden Bridge (`RW10`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideRicketyWoodenBridge_RW10: Rawcode<"destructable">;

  /**
   * Wide Rickety Wooden Bridge (`RW11`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideRicketyWoodenBridge_RW11: Rawcode<"destructable">;

  /**
   * Long Undercity Bridge (`UB01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongUndercityBridge_UB01: Rawcode<"destructable">;

  /**
   * Long Undercity Bridge (`UB02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongUndercityBridge_UB02: Rawcode<"destructable">;

  /**
   * Long Undercity Bridge (`UB03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongUndercityBridge_UB03: Rawcode<"destructable">;

  /**
   * Long Undercity Bridge (`UB04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongUndercityBridge_UB04: Rawcode<"destructable">;

  /**
   * Village Tree Wall (`VTlt`), a Built-in destructable of Patch 3.0.0.
   */
  readonly VillageTreeWall_VTlt: Rawcode<"destructable">;

  /**
   * Volcano (`Volc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly Volcano_Volc: Rawcode<"destructable">;

  /**
   * Waygate Ramp (`WGTR`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WaygateRamp_WGTR: Rawcode<"destructable">;

  /**
   * Snowy Tree Wall (`WTst`), a Built-in destructable of Patch 3.0.0.
   */
  readonly SnowyTreeWall_WTst: Rawcode<"destructable">;

  /**
   * Winter Tree Wall (`WTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WinterTreeWall_WTtw: Rawcode<"destructable">;

  /**
   * King's Throne (Diagonal 1) (`XOk1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly KingsThroneDiagonal1_XOk1: Rawcode<"destructable">;

  /**
   * King's Throne (Diagonal 1) (`XOk2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly KingsThroneDiagonal1_XOk2: Rawcode<"destructable">;

  /**
   * King's Throne (`XOkt`), a Built-in destructable of Patch 3.0.0.
   */
  readonly KingsThrone_XOkt: Rawcode<"destructable">;

  /**
   * Dalaran Building (`XTbd`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DalaranBuilding_XTbd: Rawcode<"destructable">;

  /**
   * Magical Pen (`XTm5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly MagicalPen_XTm5: Rawcode<"destructable">;

  /**
   * Magical Pen (`XTmp`), a Built-in destructable of Patch 3.0.0.
   */
  readonly MagicalPen_XTmp: Rawcode<"destructable">;

  /**
   * Magical Pen Wall (`XTmx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly MagicalPenWall_XTmx: Rawcode<"destructable">;

  /**
   * Lordaeron City Dome (`XTv1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityDome_XTv1: Rawcode<"destructable">;

  /**
   * Lordaeron City Dome Destroyed (`XTv2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityDomeDestroyed_XTv2: Rawcode<"destructable">;

  /**
   * Lordaeron City Main Building (`XTv3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityMainBuilding_XTv3: Rawcode<"destructable">;

  /**
   * Lordaeron City Main Building Destroyed (`XTv4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityMainBuildingDestroyed_XTv4: Rawcode<"destructable">;

  /**
   * Orgrimmar Wall Segment Under Construction (`XTv5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly OrgrimmarWallSegmentUnderConstruction_XTv5: Rawcode<"destructable">;

  /**
   * Orgrimmar Wall Segment Completed (`XTv6`), a Built-in destructable of Patch 3.0.0.
   */
  readonly OrgrimmarWallSegmentCompleted_XTv6: Rawcode<"destructable">;

  /**
   * Orgrimmar Tower Under Construction (`XTv7`), a Built-in destructable of Patch 3.0.0.
   */
  readonly OrgrimmarTowerUnderConstruction_XTv7: Rawcode<"destructable">;

  /**
   * Orgrimmar Tower Completed (`XTv8`), a Built-in destructable of Patch 3.0.0.
   */
  readonly OrgrimmarTowerCompleted_XTv8: Rawcode<"destructable">;

  /**
   * Dalaran Violet Citadel (`XTvt`), a Built-in destructable of Patch 3.0.0.
   */
  readonly DalaranVioletCitadel_XTvt: Rawcode<"destructable">;

  /**
   * Magical Pen Wall (`XTx5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly MagicalPenWall_XTx5: Rawcode<"destructable">;

  /**
   * Bridge Destroyed (`YSdb`), a Built-in destructable of Patch 3.0.0.
   */
  readonly BridgeDestroyed_YSdb: Rawcode<"destructable">;

  /**
   * Bridge Destroyed (`YSdc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly BridgeDestroyed_YSdc: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT00`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT00: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT01`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT01: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT02`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT02: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT03`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT03: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT04`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT04: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT05`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT05: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT06`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT06: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT07`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT07: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT08`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT08: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT09`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT09: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT10`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT10: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT11`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT11: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT12`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT12: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT13`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT13: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT14`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT14: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT15`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT15: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT16`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT16: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT17`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT17: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT18`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT18: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT19`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT19: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT20`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT20: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT21`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT21: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT22`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT22: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT23`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT23: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT24`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT24: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT25`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT25: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT26`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT26: Rawcode<"destructable">;

  /**
   * Short Natural Bridge (`YT27`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortNaturalBridge_YT27: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT28`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT28: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT29`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT29: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT30`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT30: Rawcode<"destructable">;

  /**
   * Long Natural Bridge (`YT31`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongNaturalBridge_YT31: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT32`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT32: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT33`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT33: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT34`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT34: Rawcode<"destructable">;

  /**
   * Wide Natural Bridge (`YT35`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideNaturalBridge_YT35: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT36`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT36: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT37`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT37: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT38`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT38: Rawcode<"destructable">;

  /**
   * Short Stone Bridge (`YT39`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStoneBridge_YT39: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT40`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT40: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT41`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT41: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT42`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT42: Rawcode<"destructable">;

  /**
   * Long Stone Bridge (`YT43`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStoneBridge_YT43: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT44`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT44: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT45`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT45: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT46`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT46: Rawcode<"destructable">;

  /**
   * Wide Stone Bridge (`YT47`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStoneBridge_YT47: Rawcode<"destructable">;

  /**
   * Extra Wide Natural Bridge (`YT48`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ExtraWideNaturalBridge_YT48: Rawcode<"destructable">;

  /**
   * Extra Wide Natural Bridge (`YT49`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ExtraWideNaturalBridge_YT49: Rawcode<"destructable">;

  /**
   * Extra Wide Natural Bridge (`YT50`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ExtraWideNaturalBridge_YT50: Rawcode<"destructable">;

  /**
   * Extra Wide Natural Bridge (`YT51`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ExtraWideNaturalBridge_YT51: Rawcode<"destructable">;

  /**
   * Special Ice Bridge (`YT66`), a Built-in destructable of Patch 3.0.0.
   */
  readonly SpecialIceBridge_YT66: Rawcode<"destructable">;

  /**
   * Elven Bridge (`YT67`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ElvenBridge_YT67: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Air) (`YTab`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerAir_YTab: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Air) (Large) (`YTac`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerAirLarge_YTac: Rawcode<"destructable">;

  /**
   * Icecrown Citadel Entrance (`YTc1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly IcecrownCitadelEntrance_YTc1: Rawcode<"destructable">;

  /**
   * Lordaeron City Main Gate (`YTc2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityMainGate_YTc2: Rawcode<"destructable">;

  /**
   * Lordaeron City Main Gate Destroyed (`YTc4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LordaeronCityMainGateDestroyed_YTc4: Rawcode<"destructable">;

  /**
   * City Entrance (`YTce`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityEntrance_YTce: Rawcode<"destructable">;

  /**
   * Orgrimmar Gate (`YTcn`), a Built-in destructable of Patch 3.0.0.
   */
  readonly OrgrimmarGate_YTcn: Rawcode<"destructable">;

  /**
   * Cityscape Summer Tree Wall (`YTct`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityscapeSummerTreeWall_YTct: Rawcode<"destructable">;

  /**
   * City Entrance (`YTcx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityEntrance_YTcx: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Both) (`YTfb`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerBoth_YTfb: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Both) (Large) (`YTfc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerBothLarge_YTfc: Rawcode<"destructable">;

  /**
   * Cityscape Fall Tree Wall (`YTft`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityscapeFallTreeWall_YTft: Rawcode<"destructable">;

  /**
   * Line of Sight Blocker (`YTlb`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LineOfSightBlocker_YTlb: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Ground) (`YTpb`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerGround_YTpb: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Ground) (Large) (`YTpc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerGroundLarge_YTpc: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Ground) (Thin) (Rotatable) (`YTpl`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerGroundThinRotatable_YTpl: Rawcode<"destructable">;

  /**
   * Pathing Blocker (Ground) (Tiny) (Rotatable) (`YTps`), a Built-in destructable of Patch 3.0.0.
   */
  readonly PathingBlockerGroundTinyRotatable_YTps: Rawcode<"destructable">;

  /**
   * Cityscape Snowy Tree Wall (`YTst`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityscapeSnowyTreeWall_YTst: Rawcode<"destructable">;

  /**
   * Cityscape Winter Tree Wall (`YTwt`), a Built-in destructable of Patch 3.0.0.
   */
  readonly CityscapeWinterTreeWall_YTwt: Rawcode<"destructable">;

  /**
   * Short Stratholme Bridge (`YY12`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStratholmeBridge_YY12: Rawcode<"destructable">;

  /**
   * Short Stratholme Bridge (`YY13`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStratholmeBridge_YY13: Rawcode<"destructable">;

  /**
   * Short Stratholme Bridge (`YY14`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStratholmeBridge_YY14: Rawcode<"destructable">;

  /**
   * Short Stratholme Bridge (`YY15`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ShortStratholmeBridge_YY15: Rawcode<"destructable">;

  /**
   * Long Stratholme Bridge (`YY16`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStratholmeBridge_YY16: Rawcode<"destructable">;

  /**
   * Long Stratholme Bridge (`YY17`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStratholmeBridge_YY17: Rawcode<"destructable">;

  /**
   * Long Stratholme Bridge (`YY18`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStratholmeBridge_YY18: Rawcode<"destructable">;

  /**
   * Long Stratholme Bridge (`YY19`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LongStratholmeBridge_YY19: Rawcode<"destructable">;

  /**
   * Wide Stratholme Bridge (`YY20`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStratholmeBridge_YY20: Rawcode<"destructable">;

  /**
   * Wide Stratholme Bridge (`YY21`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStratholmeBridge_YY21: Rawcode<"destructable">;

  /**
   * Wide Stratholme Bridge (`YY22`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStratholmeBridge_YY22: Rawcode<"destructable">;

  /**
   * Wide Stratholme Bridge (`YY23`), a Built-in destructable of Patch 3.0.0.
   */
  readonly WideStratholmeBridge_YY23: Rawcode<"destructable">;

  /**
   * Line of Sight Blocker (Large) (`Ytlc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly LineOfSightBlockerLarge_Ytlc: Rawcode<"destructable">;

  /**
   * Silvermoon Tree (`Yts1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly SilvermoonTree_Yts1: Rawcode<"destructable">;

  /**
   * Scorched Tree Wall (`Ytsc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly ScorchedTreeWall_Ytsc: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd1: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd2: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd3: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd4: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd5`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd5: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd6`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd6: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd7`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd7: Rawcode<"destructable">;

  /**
   * Rolling Stone Door (`ZTd8`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RollingStoneDoor_ZTd8: Rawcode<"destructable">;

  /**
   * Ruined Gate (`ZTg1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinedGate_ZTg1: Rawcode<"destructable">;

  /**
   * Ruined Gate (`ZTg2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinedGate_ZTg2: Rawcode<"destructable">;

  /**
   * Ruined Gate (`ZTg3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinedGate_ZTg3: Rawcode<"destructable">;

  /**
   * Ruined Gate (`ZTg4`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinedGate_ZTg4: Rawcode<"destructable">;

  /**
   * Ruins Naga Circle (`ZTnc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinsNagaCircle_ZTnc: Rawcode<"destructable">;

  /**
   * Ramp Naga Small (Left) (`ZTr0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RampNagaSmallLeft_ZTr0: Rawcode<"destructable">;

  /**
   * Ramp Naga Small (Top) (`ZTr1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RampNagaSmallTop_ZTr1: Rawcode<"destructable">;

  /**
   * Ramp Naga Small (Right) (`ZTr2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RampNagaSmallRight_ZTr2: Rawcode<"destructable">;

  /**
   * Ramp Naga Small (Bottom) (`ZTr3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RampNagaSmallBottom_ZTr3: Rawcode<"destructable">;

  /**
   * Massive Ruined Gate (`ZTsg`), a Built-in destructable of Patch 3.0.0.
   */
  readonly MassiveRuinedGate_ZTsg: Rawcode<"destructable">;

  /**
   * Massive Ruined Gate (`ZTsx`), a Built-in destructable of Patch 3.0.0.
   */
  readonly MassiveRuinedGate_ZTsx: Rawcode<"destructable">;

  /**
   * Ruins Canopy Tree (`ZTtc`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinsCanopyTree_ZTtc: Rawcode<"destructable">;

  /**
   * Ruins Tree Wall (`ZTtw`), a Built-in destructable of Patch 3.0.0.
   */
  readonly RuinsTreeWall_ZTtw: Rawcode<"destructable">;

  /**
   * Stone Wall (`ZTw0`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ZTw0: Rawcode<"destructable">;

  /**
   * Stone Wall (`ZTw1`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ZTw1: Rawcode<"destructable">;

  /**
   * Stone Wall (`ZTw2`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ZTw2: Rawcode<"destructable">;

  /**
   * Stone Wall (`ZTw3`), a Built-in destructable of Patch 3.0.0.
   */
  readonly StoneWall_ZTw3: Rawcode<"destructable">;
};
