// Generated by reforged-builtins from the Built-in objects of Game version 3.0.0 (3.0.0/index.json).
// Derived identifiers only: Rawcodes, Object kinds, races, enUS names and Game data sets.
// Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.
// The names and Rawcodes are derived from the game's data and are not licensed by this package.
// Never edited by hand: `pnpm builtins:generate` writes it and `pnpm builtins:check` compares it.

/**
 * The Built-in items of Patch 3.0.0, each named by its enUS name and Rawcode, such as `Items.AlleriasFluteOfAccuracy_afac`.
 */
export declare const Items: {
  /**
   * Alleria's Flute of Accuracy (`afac`), a Built-in item of Patch 3.0.0.
   */
  readonly AlleriasFluteOfAccuracy_afac: Rawcode<"item">;

  /**
   * Ancient Janggo of Endurance (`ajen`), a Built-in item of Patch 3.0.0.
   */
  readonly AncientJanggoOfEndurance_ajen: Rawcode<"item">;

  /**
   * Amulet of Recall (`amrc`), a Built-in item of Patch 3.0.0.
   */
  readonly AmuletOfRecall_amrc: Rawcode<"item">;

  /**
   * Ancient Figurine (`anfg`), a Built-in item of Patch 3.0.0.
   */
  readonly AncientFigurine_anfg: Rawcode<"item">;

  /**
   * Ankh of Reincarnation (`ankh`), a Built-in item of Patch 3.0.0.
   */
  readonly AnkhOfReincarnation_ankh: Rawcode<"item">;

  /**
   * Arcane Scroll (`arsc`), a Built-in item of Patch 3.0.0.
   */
  readonly ArcaneScroll_arsc: Rawcode<"item">;

  /**
   * Arcanite Shield (`arsh`), a Built-in item of Patch 3.0.0.
   */
  readonly ArcaniteShield_arsh: Rawcode<"item">;

  /**
   * Assassin's Blade (`asbl`), a Built-in item of Patch 3.0.0.
   */
  readonly AssassinsBlade_asbl: Rawcode<"item">;

  /**
   * Ancestral Staff (`axas`), a Built-in item of Patch 3.0.0.
   */
  readonly AncestralStaff_axas: Rawcode<"item">;

  /**
   * Heart of Aszune (`azhr`), a Built-in item of Patch 3.0.0.
   */
  readonly HeartOfAszune_azhr: Rawcode<"item">;

  /**
   * Boots of Quel'Thalas +6 (`belv`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfQuelThalas6_belv: Rawcode<"item">;

  /**
   * Bloodfeather's Heart (`bfhr`), a Built-in item of Patch 3.0.0.
   */
  readonly BloodfeathersHeart_bfhr: Rawcode<"item">;

  /**
   * Belt of Giant Strength +6 (`bgst`), a Built-in item of Patch 3.0.0.
   */
  readonly BeltOfGiantStrength6_bgst: Rawcode<"item">;

  /**
   * Bladebane Armor (`blba`), a Built-in item of Patch 3.0.0.
   */
  readonly BladebaneArmor_blba: Rawcode<"item">;

  /**
   * Runed Bracers (`brac`), a Built-in item of Patch 3.0.0.
   */
  readonly RunedBracers_brac: Rawcode<"item">;

  /**
   * Bracer of Agility (`brag`), a Built-in item of Patch 3.0.0.
   */
  readonly BracerOfAgility_brag: Rawcode<"item">;

  /**
   * Rusty Plated Boots (`brpb`), a Built-in item of Patch 3.0.0.
   */
  readonly RustyPlatedBoots_brpb: Rawcode<"item">;

  /**
   * Boots of Speed (`bspd`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfSpeed_bspd: Rawcode<"item">;

  /**
   * Battle Standard (`btst`), a Built-in item of Patch 3.0.0.
   */
  readonly BattleStandard_btst: Rawcode<"item">;

  /**
   * Empty Vial (`bzbe`), a Built-in item of Patch 3.0.0.
   */
  readonly EmptyVial_bzbe: Rawcode<"item">;

  /**
   * Full Vial (`bzbf`), a Built-in item of Patch 3.0.0.
   */
  readonly FullVial_bzbf: Rawcode<"item">;

  /**
   * Bandit Lord's Limbs (`cabl`), a Built-in item of Patch 3.0.0.
   */
  readonly BanditLordsLimbs_cabl: Rawcode<"item">;

  /**
   * Garithos's Head (`cagh`), a Built-in item of Patch 3.0.0.
   */
  readonly GarithossHead_cagh: Rawcode<"item">;

  /**
   * Broodmother Venom (`cbmv`), a Built-in item of Patch 3.0.0.
   */
  readonly BroodmotherVenom_cbmv: Rawcode<"item">;

  /**
   * Captured Ghoul (`cccg`), a Built-in item of Patch 3.0.0.
   */
  readonly CapturedGhoul_cccg: Rawcode<"item">;

  /**
   * Consecrated Mixture (`cccm`), a Built-in item of Patch 3.0.0.
   */
  readonly ConsecratedMixture_cccm: Rawcode<"item">;

  /**
   * Elixir of Cunning (`ccec`), a Built-in item of Patch 3.0.0.
   */
  readonly ElixirOfCunning_ccec: Rawcode<"item">;

  /**
   * Elixir of the Monster Hunter (`ccem`), a Built-in item of Patch 3.0.0.
   */
  readonly ElixirOfTheMonsterHunter_ccem: Rawcode<"item">;

  /**
   * Scepter of Mastery (`ccmd`), a Built-in item of Patch 3.0.0.
   */
  readonly ScepterOfMastery_ccmd: Rawcode<"item">;

  /**
   * Valve Wheel (`ccvw`), a Built-in item of Patch 3.0.0.
   */
  readonly ValveWheel_ccvw: Rawcode<"item">;

  /**
   * Darkhound Blood (`cdhb`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkhoundBlood_cdhb: Rawcode<"item">;

  /**
   * Elixir of Greater Intelligence (`cegi`), a Built-in item of Patch 3.0.0.
   */
  readonly ElixirOfGreaterIntelligence_cegi: Rawcode<"item">;

  /**
   * Elixir of Lesser Intelligence (`celi`), a Built-in item of Patch 3.0.0.
   */
  readonly ElixirOfLesserIntelligence_celi: Rawcode<"item">;

  /**
   * Experimental Serum (`cese`), a Built-in item of Patch 3.0.0.
   */
  readonly ExperimentalSerum_cese: Rawcode<"item">;

  /**
   * Explosive Barrel (`cexp`), a Built-in item of Patch 3.0.0.
   */
  readonly ExplosiveBarrel_cexp: Rawcode<"item">;

  /**
   * Cheese (`ches`), a Built-in item of Patch 3.0.0.
   */
  readonly Cheese_ches: Rawcode<"item">;

  /**
   * Robe of the Magi +6 (`ciri`), a Built-in item of Patch 3.0.0.
   */
  readonly RobeOfTheMagi6_ciri: Rawcode<"item">;

  /**
   * Key to the Chamber of Mysteries (`ckcm`), a Built-in item of Patch 3.0.0.
   */
  readonly KeyToTheChamberOfMysteries_ckcm: Rawcode<"item">;

  /**
   * Dungeon Key (`ckdk`), a Built-in item of Patch 3.0.0.
   */
  readonly DungeonKey_ckdk: Rawcode<"item">;

  /**
   * Crown of Kings +5 (`ckng`), a Built-in item of Patch 3.0.0.
   */
  readonly CrownOfKings5_ckng: Rawcode<"item">;

  /**
   * Cloak of Flames (`clfm`), a Built-in item of Patch 3.0.0.
   */
  readonly CloakOfFlames_clfm: Rawcode<"item">;

  /**
   * Lump of Meat (`clom`), a Built-in item of Patch 3.0.0.
   */
  readonly LumpOfMeat_clom: Rawcode<"item">;

  /**
   * Cloak of Shadows (`clsd`), a Built-in item of Patch 3.0.0.
   */
  readonly CloakOfShadows_clsd: Rawcode<"item">;

  /**
   * Magical Key (`cmag`), a Built-in item of Patch 3.0.0.
   */
  readonly MagicalKey_cmag: Rawcode<"item">;

  /**
   * Horn of Cenarius (`cnhn`), a Built-in item of Patch 3.0.0.
   */
  readonly HornOfCenarius_cnhn: Rawcode<"item">;

  /**
   * Circlet of Nobility (`cnob`), a Built-in item of Patch 3.0.0.
   */
  readonly CircletOfNobility_cnob: Rawcode<"item">;

  /**
   * Celestial Orb of Souls (`cosl`), a Built-in item of Patch 3.0.0.
   */
  readonly CelestialOrbOfSouls_cosl: Rawcode<"item">;

  /**
   * Portal Orb (`cpor`), a Built-in item of Patch 3.0.0.
   */
  readonly PortalOrb_cpor: Rawcode<"item">;

  /**
   * Prison Key (`cprk`), a Built-in item of Patch 3.0.0.
   */
  readonly PrisonKey_cprk: Rawcode<"item">;

  /**
   * Paladin's Torso (`cptz`), a Built-in item of Patch 3.0.0.
   */
  readonly PaladinsTorso_cptz: Rawcode<"item">;

  /**
   * Crown of the Deathlord (`crdt`), a Built-in item of Patch 3.0.0.
   */
  readonly CrownOfTheDeathlord_crdt: Rawcode<"item">;

  /**
   * Crystal Ball (`crys`), a Built-in item of Patch 3.0.0.
   */
  readonly CrystalBall_crys: Rawcode<"item">;

  /**
   * The Artifact (`ctat`), a Built-in item of Patch 3.0.0.
   */
  readonly TheArtifact_ctat: Rawcode<"item">;

  /**
   * Tome of Agility (`ctoa`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfAgility_ctoa: Rawcode<"item">;

  /**
   * Tome of Intelligence (`ctoi`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfIntelligence_ctoi: Rawcode<"item">;

  /**
   * Tome of Strength (`ctos`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfStrength_ctos: Rawcode<"item">;

  /**
   * Very Very Deep Thoughts (`cvdt`), a Built-in item of Patch 3.0.0.
   */
  readonly VeryVeryDeepThoughts_cvdt: Rawcode<"item">;

  /**
   * Vile Fin Scale (`cvfs`), a Built-in item of Patch 3.0.0.
   */
  readonly VileFinScale_cvfs: Rawcode<"item">;

  /**
   * Vial of Plague Essence (`cvpe`), a Built-in item of Patch 3.0.0.
   */
  readonly VialOfPlagueEssence_cvpe: Rawcode<"item">;

  /**
   * Vial of Vampire Bat Blood (`cvvb`), a Built-in item of Patch 3.0.0.
   */
  readonly VialOfVampireBatBlood_cvvb: Rawcode<"item">;

  /**
   * Kelen's Dagger of Escape (`desc`), a Built-in item of Patch 3.0.0.
   */
  readonly KelensDaggerOfEscape_desc: Rawcode<"item">;

  /**
   * Keg of Thunderwater (`dkfw`), a Built-in item of Patch 3.0.0.
   */
  readonly KegOfThunderwater_dkfw: Rawcode<"item">;

  /**
   * Thunder Phoenix Egg (`dphe`), a Built-in item of Patch 3.0.0.
   */
  readonly ThunderPhoenixEgg_dphe: Rawcode<"item">;

  /**
   * Druid Pouch (`drph`), a Built-in item of Patch 3.0.0.
   */
  readonly DruidPouch_drph: Rawcode<"item">;

  /**
   * Diamond of Summoning (`dsum`), a Built-in item of Patch 3.0.0.
   */
  readonly DiamondOfSummoning_dsum: Rawcode<"item">;

  /**
   * Thunderbloom Bulb (`dthb`), a Built-in item of Patch 3.0.0.
   */
  readonly ThunderbloomBulb_dthb: Rawcode<"item">;

  /**
   * Drek'thar's Spellbook (`dtsb`), a Built-in item of Patch 3.0.0.
   */
  readonly DrektharsSpellbook_dtsb: Rawcode<"item">;

  /**
   * Dust of Appearance (`dust`), a Built-in item of Patch 3.0.0.
   */
  readonly DustOfAppearance_dust: Rawcode<"item">;

  /**
   * Farstrider's Amulet (`eaaa`), a Built-in item of Patch 3.0.0.
   */
  readonly FarstridersAmulet_eaaa: Rawcode<"item">;

  /**
   * Blacksmith's Apron (`eaba`), a Built-in item of Patch 3.0.0.
   */
  readonly BlacksmithsApron_eaba: Rawcode<"item">;

  /**
   * Ancient Bronze Helmet (`eabh`), a Built-in item of Patch 3.0.0.
   */
  readonly AncientBronzeHelmet_eabh: Rawcode<"item">;

  /**
   * Agitating Totem (`eagt`), a Built-in item of Patch 3.0.0.
   */
  readonly AgitatingTotem_eagt: Rawcode<"item">;

  /**
   * Amulet of Minor Endurance (`eame`), a Built-in item of Patch 3.0.0.
   */
  readonly AmuletOfMinorEndurance_eame: Rawcode<"item">;

  /**
   * Armor of Reanimation (`eaor`), a Built-in item of Patch 3.0.0.
   */
  readonly ArmorOfReanimation_eaor: Rawcode<"item">;

  /**
   * Robes of Revenge (`earr`), a Built-in item of Patch 3.0.0.
   */
  readonly RobesOfRevenge_earr: Rawcode<"item">;

  /**
   * Arcane Spellblade (`easb`), a Built-in item of Patch 3.0.0.
   */
  readonly ArcaneSpellblade_easb: Rawcode<"item">;

  /**
   * Armor of the Scarlet Crusade (`easc`), a Built-in item of Patch 3.0.0.
   */
  readonly ArmorOfTheScarletCrusade_easc: Rawcode<"item">;

  /**
   * Agus's Shambling Hand (`eash`), a Built-in item of Patch 3.0.0.
   */
  readonly AgussShamblingHand_eash: Rawcode<"item">;

  /**
   * Untakable Candle (`eauc`), a Built-in item of Patch 3.0.0.
   */
  readonly UntakableCandle_eauc: Rawcode<"item">;

  /**
   * Vampiric Robes (`eavr`), a Built-in item of Patch 3.0.0.
   */
  readonly VampiricRobes_eavr: Rawcode<"item">;

  /**
   * Backpack (`ebac`), a Built-in item of Patch 3.0.0.
   */
  readonly Backpack_ebac: Rawcode<"item">;

  /**
   * Bone Cage Breastplate (`ebcb`), a Built-in item of Patch 3.0.0.
   */
  readonly BoneCageBreastplate_ebcb: Rawcode<"item">;

  /**
   * Bone Commander's Skull (`ebcs`), a Built-in item of Patch 3.0.0.
   */
  readonly BoneCommandersSkull_ebcs: Rawcode<"item">;

  /**
   * Blue Dragon Figurine (`ebdf`), a Built-in item of Patch 3.0.0.
   */
  readonly BlueDragonFigurine_ebdf: Rawcode<"item">;

  /**
   * Blade Dancer's Greaves (`ebdg`), a Built-in item of Patch 3.0.0.
   */
  readonly BladeDancersGreaves_ebdg: Rawcode<"item">;

  /**
   * Deathwalkers (`ebdw`), a Built-in item of Patch 3.0.0.
   */
  readonly Deathwalkers_ebdw: Rawcode<"item">;

  /**
   * Blade of Frozen Hunger (`ebfh`), a Built-in item of Patch 3.0.0.
   */
  readonly BladeOfFrozenHunger_ebfh: Rawcode<"item">;

  /**
   * Heavyduty Boots (`ebhb`), a Built-in item of Patch 3.0.0.
   */
  readonly HeavydutyBoots_ebhb: Rawcode<"item">;

  /**
   * Garek's Backpack (`ebhg`), a Built-in item of Patch 3.0.0.
   */
  readonly GareksBackpack_ebhg: Rawcode<"item">;

  /**
   * Ilastar's Backpack (`ebhi`), a Built-in item of Patch 3.0.0.
   */
  readonly IlastarsBackpack_ebhi: Rawcode<"item">;

  /**
   * Landen's Backpack (`ebhl`), a Built-in item of Patch 3.0.0.
   */
  readonly LandensBackpack_ebhl: Rawcode<"item">;

  /**
   * Necromancer's Plaguegreaves (`ebnp`), a Built-in item of Patch 3.0.0.
   */
  readonly NecromancersPlaguegreaves_ebnp: Rawcode<"item">;

  /**
   * Blade of Corruption (`eboc`), a Built-in item of Patch 3.0.0.
   */
  readonly BladeOfCorruption_eboc: Rawcode<"item">;

  /**
   * Boots of the Forsaken (`ebof`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfTheForsaken_ebof: Rawcode<"item">;

  /**
   * Bindings of Helya (`eboh`), a Built-in item of Patch 3.0.0.
   */
  readonly BindingsOfHelya_eboh: Rawcode<"item">;

  /**
   * Boots of the Icewalker (`eboi`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfTheIcewalker_eboi: Rawcode<"item">;

  /**
   * Bracers of the Ogre Magi (`ebom`), a Built-in item of Patch 3.0.0.
   */
  readonly BracersOfTheOgreMagi_ebom: Rawcode<"item">;

  /**
   * Overlord's Sabatons (`ebos`), a Built-in item of Patch 3.0.0.
   */
  readonly OverlordsSabatons_ebos: Rawcode<"item">;

  /**
   * Blackrock Chain Helm (`ebr1`), a Built-in item of Patch 3.0.0.
   */
  readonly BlackrockChainHelm_ebr1: Rawcode<"item">;

  /**
   * Blademaster's Greatsword (`ebr2`), a Built-in item of Patch 3.0.0.
   */
  readonly BlademastersGreatsword_ebr2: Rawcode<"item">;

  /**
   * Blackrock Steel Plate (`ebrp`), a Built-in item of Patch 3.0.0.
   */
  readonly BlackrockSteelPlate_ebrp: Rawcode<"item">;

  /**
   * Boots of the Scarlet Crusade (`ebsc`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfTheScarletCrusade_ebsc: Rawcode<"item">;

  /**
   * Band of the Sin'dorei (`ebsd`), a Built-in item of Patch 3.0.0.
   */
  readonly BandOfTheSindorei_ebsd: Rawcode<"item">;

  /**
   * Broken Skinning Knife (`ebsk`), a Built-in item of Patch 3.0.0.
   */
  readonly BrokenSkinningKnife_ebsk: Rawcode<"item">;

  /**
   * Band of the Skeletal Mage (`ebsm`), a Built-in item of Patch 3.0.0.
   */
  readonly BandOfTheSkeletalMage_ebsm: Rawcode<"item">;

  /**
   * Breastplate of the Scarlet Paladin (`ebsp`), a Built-in item of Patch 3.0.0.
   */
  readonly BreastplateOfTheScarletPaladin_ebsp: Rawcode<"item">;

  /**
   * Stormwalkers (`ebsw`), a Built-in item of Patch 3.0.0.
   */
  readonly Stormwalkers_ebsw: Rawcode<"item">;

  /**
   * Tactician's Boots (`ebtb`), a Built-in item of Patch 3.0.0.
   */
  readonly TacticiansBoots_ebtb: Rawcode<"item">;

  /**
   * Alicia's Favor (`ebtf`), a Built-in item of Patch 3.0.0.
   */
  readonly AliciasFavor_ebtf: Rawcode<"item">;

  /**
   * Bramblethorn Vestments (`ebtv`), a Built-in item of Patch 3.0.0.
   */
  readonly BramblethornVestments_ebtv: Rawcode<"item">;

  /**
   * Anya's Backpack (`ebua`), a Built-in item of Patch 3.0.0.
   */
  readonly AnyasBackpack_ebua: Rawcode<"item">;

  /**
   * Garek's Backpack (`ebug`), a Built-in item of Patch 3.0.0.
   */
  readonly GareksBackpack_ebug: Rawcode<"item">;

  /**
   * Leonid's Backpack (`ebul`), a Built-in item of Patch 3.0.0.
   */
  readonly LeonidsBackpack_ebul: Rawcode<"item">;

  /**
   * Butcher's Cleaver (`ebut`), a Built-in item of Patch 3.0.0.
   */
  readonly ButchersCleaver_ebut: Rawcode<"item">;

  /**
   * Blightweaver Boots (`ebwb`), a Built-in item of Patch 3.0.0.
   */
  readonly BlightweaverBoots_ebwb: Rawcode<"item">;

  /**
   * Wayfarer Greaves (`ebwg`), a Built-in item of Patch 3.0.0.
   */
  readonly WayfarerGreaves_ebwg: Rawcode<"item">;

  /**
   * Boots of the Warm Hearth (`ebwh`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfTheWarmHearth_ebwh: Rawcode<"item">;

  /**
   * Worn Sandals (`ebws`), a Built-in item of Patch 3.0.0.
   */
  readonly WornSandals_ebws: Rawcode<"item">;

  /**
   * Citrine Adorned Boots (`ecab`), a Built-in item of Patch 3.0.0.
   */
  readonly CitrineAdornedBoots_ecab: Rawcode<"item">;

  /**
   * Shoddy Cap (`ecap`), a Built-in item of Patch 3.0.0.
   */
  readonly ShoddyCap_ecap: Rawcode<"item">;

  /**
   * Amulet of Vitality (`ecav`), a Built-in item of Patch 3.0.0.
   */
  readonly AmuletOfVitality_ecav: Rawcode<"item">;

  /**
   * Colossal Battleaxe (`ecba`), a Built-in item of Patch 3.0.0.
   */
  readonly ColossalBattleaxe_ecba: Rawcode<"item">;

  /**
   * Coldbringer's Reach (`ecbr`), a Built-in item of Patch 3.0.0.
   */
  readonly ColdbringersReach_ecbr: Rawcode<"item">;

  /**
   * Chipped Circlet of Clarity (`eccc`), a Built-in item of Patch 3.0.0.
   */
  readonly ChippedCircletOfClarity_eccc: Rawcode<"item">;

  /**
   * Dreaded Chestplate (`ecdc`), a Built-in item of Patch 3.0.0.
   */
  readonly DreadedChestplate_ecdc: Rawcode<"item">;

  /**
   * Druidic Leafguard (`ecdl`), a Built-in item of Patch 3.0.0.
   */
  readonly DruidicLeafguard_ecdl: Rawcode<"item">;

  /**
   * Guardsman Boots (`ecgb`), a Built-in item of Patch 3.0.0.
   */
  readonly GuardsmanBoots_ecgb: Rawcode<"item">;

  /**
   * Guardsman Chestplate (`ecgc`), a Built-in item of Patch 3.0.0.
   */
  readonly GuardsmanChestplate_ecgc: Rawcode<"item">;

  /**
   * Guardsman Helmet (`ecgh`), a Built-in item of Patch 3.0.0.
   */
  readonly GuardsmanHelmet_ecgh: Rawcode<"item">;

  /**
   * Cursed Golden Ring (`ecgr`), a Built-in item of Patch 3.0.0.
   */
  readonly CursedGoldenRing_ecgr: Rawcode<"item">;

  /**
   * Staff of the Crimson Heart (`ech1`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfTheCrimsonHeart_ech1: Rawcode<"item">;

  /**
   * Blade of the Crimson Heart (`ech2`), a Built-in item of Patch 3.0.0.
   */
  readonly BladeOfTheCrimsonHeart_ech2: Rawcode<"item">;

  /**
   * Guardian of the Crimson Heart (`ech3`), a Built-in item of Patch 3.0.0.
   */
  readonly GuardianOfTheCrimsonHeart_ech3: Rawcode<"item">;

  /**
   * Immortal Guardian's Chestplate (`ecig`), a Built-in item of Patch 3.0.0.
   */
  readonly ImmortalGuardiansChestplate_ecig: Rawcode<"item">;

  /**
   * Chestpiece of Lesser Cunning (`eclc`), a Built-in item of Patch 3.0.0.
   */
  readonly ChestpieceOfLesserCunning_eclc: Rawcode<"item">;

  /**
   * Deerskin Gloves (`eclg`), a Built-in item of Patch 3.0.0.
   */
  readonly DeerskinGloves_eclg: Rawcode<"item">;

  /**
   * Chronomaster's Gloves (`ecmg`), a Built-in item of Patch 3.0.0.
   */
  readonly ChronomastersGloves_ecmg: Rawcode<"item">;

  /**
   * Novice Rags (`ecnr`), a Built-in item of Patch 3.0.0.
   */
  readonly NoviceRags_ecnr: Rawcode<"item">;

  /**
   * Convergence of Fates (`ecof`), a Built-in item of Patch 3.0.0.
   */
  readonly ConvergenceOfFates_ecof: Rawcode<"item">;

  /**
   * Crown of the Resolute Monarch (`ecrm`), a Built-in item of Patch 3.0.0.
   */
  readonly CrownOfTheResoluteMonarch_ecrm: Rawcode<"item">;

  /**
   * Cardinal Ruby of the Necrolyte (`ecrn`), a Built-in item of Patch 3.0.0.
   */
  readonly CardinalRubyOfTheNecrolyte_ecrn: Rawcode<"item">;

  /**
   * Ring of Regeneration (`ecrr`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfRegeneration_ecrr: Rawcode<"item">;

  /**
   * Steel Sword (`ecss`), a Built-in item of Patch 3.0.0.
   */
  readonly SteelSword_ecss: Rawcode<"item">;

  /**
   * Diamond Adorned Chestplate (`edac`), a Built-in item of Patch 3.0.0.
   */
  readonly DiamondAdornedChestplate_edac: Rawcode<"item">;

  /**
   * Deathbringer's Boots (`edbb`), a Built-in item of Patch 3.0.0.
   */
  readonly DeathbringersBoots_edbb: Rawcode<"item">;

  /**
   * Deathbloom Leaves (`edbl`), a Built-in item of Patch 3.0.0.
   */
  readonly DeathbloomLeaves_edbl: Rawcode<"item">;

  /**
   * Drained Bloodstone (`edbs`), a Built-in item of Patch 3.0.0.
   */
  readonly DrainedBloodstone_edbs: Rawcode<"item">;

  /**
   * Deepsea Bag (`edbw`), a Built-in item of Patch 3.0.0.
   */
  readonly DeepseaBag_edbw: Rawcode<"item">;

  /**
   * Diamond Staff of Dalaran (`edds`), a Built-in item of Patch 3.0.0.
   */
  readonly DiamondStaffOfDalaran_edds: Rawcode<"item">;

  /**
   * Dark Iron Breastplate (`edib`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkIronBreastplate_edib: Rawcode<"item">;

  /**
   * Dark Iron Greaves (`edif`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkIronGreaves_edif: Rawcode<"item">;

  /**
   * Dark Iron Gauntlets (`edig`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkIronGauntlets_edig: Rawcode<"item">;

  /**
   * Dark Iron Helm (`edih`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkIronHelm_edih: Rawcode<"item">;

  /**
   * Dark Iron Shield (`edis`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkIronShield_edis: Rawcode<"item">;

  /**
   * Dark Ranger's Bracers (`edrb`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkRangersBracers_edrb: Rawcode<"item">;

  /**
   * Dark Ranger's Chestguard (`edrc`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkRangersChestguard_edrc: Rawcode<"item">;

  /**
   * Dark Ranger's Hood (`edrh`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkRangersHood_edrh: Rawcode<"item">;

  /**
   * Dark Ranger's Insignia (`edri`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkRangersInsignia_edri: Rawcode<"item">;

  /**
   * Dark Ranger's Shadows (`edrs`), a Built-in item of Patch 3.0.0.
   */
  readonly DarkRangersShadows_edrs: Rawcode<"item">;

  /**
   * Damaged Spellbreaker Helmet (`edsh`), a Built-in item of Patch 3.0.0.
   */
  readonly DamagedSpellbreakerHelmet_edsh: Rawcode<"item">;

  /**
   * Decrepit Sorcerer's Mantle (`edsm`), a Built-in item of Patch 3.0.0.
   */
  readonly DecrepitSorcerersMantle_edsm: Rawcode<"item">;

  /**
   * Dalaran Sapphire Robes (`edsr`), a Built-in item of Patch 3.0.0.
   */
  readonly DalaranSapphireRobes_edsr: Rawcode<"item">;

  /**
   * Desecrated Tower Shield (`edts`), a Built-in item of Patch 3.0.0.
   */
  readonly DesecratedTowerShield_edts: Rawcode<"item">;

  /**
   * Demonic Warglaives (`edwg`), a Built-in item of Patch 3.0.0.
   */
  readonly DemonicWarglaives_edwg: Rawcode<"item">;

  /**
   * Endless Flask of Restoration (`eefr`), a Built-in item of Patch 3.0.0.
   */
  readonly EndlessFlaskOfRestoration_eefr: Rawcode<"item">;

  /**
   * Essencium, the Gathering of Elements (`eege`), a Built-in item of Patch 3.0.0.
   */
  readonly EssenciumTheGatheringOfElements_eege: Rawcode<"item">;

  /**
   * Lesser Engineering Goggles (`eeh1`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserEngineeringGoggles_eeh1: Rawcode<"item">;

  /**
   * Greater Engineering Goggles (`eeh2`), a Built-in item of Patch 3.0.0.
   */
  readonly GreaterEngineeringGoggles_eeh2: Rawcode<"item">;

  /**
   * Master Engineering Goggles (`eeh3`), a Built-in item of Patch 3.0.0.
   */
  readonly MasterEngineeringGoggles_eeh3: Rawcode<"item">;

  /**
   * Enchanted Inscription Tools (`eeit`), a Built-in item of Patch 3.0.0.
   */
  readonly EnchantedInscriptionTools_eeit: Rawcode<"item">;

  /**
   * Edge of the Ruined City (`eerc`), a Built-in item of Patch 3.0.0.
   */
  readonly EdgeOfTheRuinedCity_eerc: Rawcode<"item">;

  /**
   * Essence of the Spider Queen (`eesq`), a Built-in item of Patch 3.0.0.
   */
  readonly EssenceOfTheSpiderQueen_eesq: Rawcode<"item">;

  /**
   * Forsaken Champion's Helm (`efch`), a Built-in item of Patch 3.0.0.
   */
  readonly ForsakenChampionsHelm_efch: Rawcode<"item">;

  /**
   * Forgotten Frost Lotus (`effl`), a Built-in item of Patch 3.0.0.
   */
  readonly ForgottenFrostLotus_effl: Rawcode<"item">;

  /**
   * Frenzied Ghoul Claws (`efgc`), a Built-in item of Patch 3.0.0.
   */
  readonly FrenziedGhoulClaws_efgc: Rawcode<"item">;

  /**
   * Flesh Golem Ribcage (`efgh`), a Built-in item of Patch 3.0.0.
   */
  readonly FleshGolemRibcage_efgh: Rawcode<"item">;

  /**
   * Frayed Headwear of the Magehunter (`efhm`), a Built-in item of Patch 3.0.0.
   */
  readonly FrayedHeadwearOfTheMagehunter_efhm: Rawcode<"item">;

  /**
   * Frail Leather Armor (`efla`), a Built-in item of Patch 3.0.0.
   */
  readonly FrailLeatherArmor_efla: Rawcode<"item">;

  /**
   * Flame of Al'ar (`efoa`), a Built-in item of Patch 3.0.0.
   */
  readonly FlameOfAlar_efoa: Rawcode<"item">;

  /**
   * Forsaken Plaguebow (`efpb`), a Built-in item of Patch 3.0.0.
   */
  readonly ForsakenPlaguebow_efpb: Rawcode<"item">;

  /**
   * Forest Ranger's Gloves (`efrg`), a Built-in item of Patch 3.0.0.
   */
  readonly ForestRangersGloves_efrg: Rawcode<"item">;

  /**
   * Frayed Sorcerer's Handwraps (`efsh`), a Built-in item of Patch 3.0.0.
   */
  readonly FrayedSorcerersHandwraps_efsh: Rawcode<"item">;

  /**
   * Aviana's Talons (`egat`), a Built-in item of Patch 3.0.0.
   */
  readonly AvianasTalons_egat: Rawcode<"item">;

  /**
   * Crusader's Gauntlets (`egcg`), a Built-in item of Patch 3.0.0.
   */
  readonly CrusadersGauntlets_egcg: Rawcode<"item">;

  /**
   * Gloves of the Deathbringer (`egdb`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfTheDeathbringer_egdb: Rawcode<"item">;

  /**
   * Gravelight, the Echoing Flames (`egef`), a Built-in item of Patch 3.0.0.
   */
  readonly GravelightTheEchoingFlames_egef: Rawcode<"item">;

  /**
   * Forsaken Gauntlets (`egfg`), a Built-in item of Patch 3.0.0.
   */
  readonly ForsakenGauntlets_egfg: Rawcode<"item">;

  /**
   * Gloves of the Flamewalker (`egfw`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfTheFlamewalker_egfw: Rawcode<"item">;

  /**
   * Gloves of Necromancy (`eggn`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfNecromancy_eggn: Rawcode<"item">;

  /**
   * Gloves of the Phoenix (`eggp`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfThePhoenix_eggp: Rawcode<"item">;

  /**
   * Gloves of Lesser Cunning (`eglc`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfLesserCunning_eglc: Rawcode<"item">;

  /**
   * Golden Necklace of Serenity (`egns`), a Built-in item of Patch 3.0.0.
   */
  readonly GoldenNecklaceOfSerenity_egns: Rawcode<"item">;

  /**
   * Gloves of the Battlemage (`egob`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfTheBattlemage_egob: Rawcode<"item">;

  /**
   * Gloves of Perfection (`egop`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfPerfection_egop: Rawcode<"item">;

  /**
   * Magister's Handguards (`egos`), a Built-in item of Patch 3.0.0.
   */
  readonly MagistersHandguards_egos: Rawcode<"item">;

  /**
   * Gift of the Wilds (`egow`), a Built-in item of Patch 3.0.0.
   */
  readonly GiftOfTheWilds_egow: Rawcode<"item">;

  /**
   * Giant Skeleton Bone (`egsb`), a Built-in item of Patch 3.0.0.
   */
  readonly GiantSkeletonBone_egsb: Rawcode<"item">;

  /**
   * Gloves of the Scarlet Crusade (`egsc`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfTheScarletCrusade_egsc: Rawcode<"item">;

  /**
   * Selene, Grand Scepter of Elune (`egse`), a Built-in item of Patch 3.0.0.
   */
  readonly SeleneGrandScepterOfElune_egse: Rawcode<"item">;

  /**
   * Sage's Gloves (`egsg`), a Built-in item of Patch 3.0.0.
   */
  readonly SagesGloves_egsg: Rawcode<"item">;

  /**
   * Glacial Shard (`egsh`), a Built-in item of Patch 3.0.0.
   */
  readonly GlacialShard_egsh: Rawcode<"item">;

  /**
   * Gloves of Ultimate Vampirism (`eguv`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfUltimateVampirism_eguv: Rawcode<"item">;

  /**
   * Gnoll Warlord Hide (`egwh`), a Built-in item of Patch 3.0.0.
   */
  readonly GnollWarlordHide_egwh: Rawcode<"item">;

  /**
   * Gnomish Zapper X-4000 (`egzx`), a Built-in item of Patch 3.0.0.
   */
  readonly GnomishZapperX4000_egzx: Rawcode<"item">;

  /**
   * Bandit Mask (`ehbm`), a Built-in item of Patch 3.0.0.
   */
  readonly BanditMask_ehbm: Rawcode<"item">;

  /**
   * Helm of the Cenarion Circle (`ehcc`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfTheCenarionCircle_ehcc: Rawcode<"item">;

  /**
   * Huge Citrine of the Fierce (`ehcf`), a Built-in item of Patch 3.0.0.
   */
  readonly HugeCitrineOfTheFierce_ehcf: Rawcode<"item">;

  /**
   * Crimson Helm of Opportunity (`ehco`), a Built-in item of Patch 3.0.0.
   */
  readonly CrimsonHelmOfOpportunity_ehco: Rawcode<"item">;

  /**
   * Helm of the Dark Rider (`ehdr`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfTheDarkRider_ehdr: Rawcode<"item">;

  /**
   * Diamond Tiara (`ehdt`), a Built-in item of Patch 3.0.0.
   */
  readonly DiamondTiara_ehdt: Rawcode<"item">;

  /**
   * Ring of Holy Fire (`ehfi`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfHolyFire_ehfi: Rawcode<"item">;

  /**
   * Gilnean Headpiece (`ehgh`), a Built-in item of Patch 3.0.0.
   */
  readonly GilneanHeadpiece_ehgh: Rawcode<"item">;

  /**
   * Headpiece of the High Inquisitor (`ehhi`), a Built-in item of Patch 3.0.0.
   */
  readonly HeadpieceOfTheHighInquisitor_ehhi: Rawcode<"item">;

  /**
   * Helm of the Iron Guardian (`ehig`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfTheIronGuardian_ehig: Rawcode<"item">;

  /**
   * Horn of the Lost Spirits (`ehls`), a Built-in item of Patch 3.0.0.
   */
  readonly HornOfTheLostSpirits_ehls: Rawcode<"item">;

  /**
   * Moonstone Circlet (`ehmc`), a Built-in item of Patch 3.0.0.
   */
  readonly MoonstoneCirclet_ehmc: Rawcode<"item">;

  /**
   * Heart of the Lake (`ehol`), a Built-in item of Patch 3.0.0.
   */
  readonly HeartOfTheLake_ehol: Rawcode<"item">;

  /**
   * Pirate Hat (`ehph`), a Built-in item of Patch 3.0.0.
   */
  readonly PirateHat_ehph: Rawcode<"item">;

  /**
   * Helm of the Rimelord (`ehrl`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfTheRimelord_ehrl: Rawcode<"item">;

  /**
   * Helm of the Scarlet Captain (`ehsc`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfTheScarletCaptain_ehsc: Rawcode<"item">;

  /**
   * Hammer of the Silver Hand (`ehsh`), a Built-in item of Patch 3.0.0.
   */
  readonly HammerOfTheSilverHand_ehsh: Rawcode<"item">;

  /**
   * High Templar's Conqueror (`ehtc`), a Built-in item of Patch 3.0.0.
   */
  readonly HighTemplarsConqueror_ehtc: Rawcode<"item">;

  /**
   * High Templar's Flame (`ehtf`), a Built-in item of Patch 3.0.0.
   */
  readonly HighTemplarsFlame_ehtf: Rawcode<"item">;

  /**
   * High Templar's Judgment (`ehtj`), a Built-in item of Patch 3.0.0.
   */
  readonly HighTemplarsJudgment_ehtj: Rawcode<"item">;

  /**
   * Handful of Throwing Knives (`ehtk`), a Built-in item of Patch 3.0.0.
   */
  readonly HandfulOfThrowingKnives_ehtk: Rawcode<"item">;

  /**
   * High Templar's March (`ehtm`), a Built-in item of Patch 3.0.0.
   */
  readonly HighTemplarsMarch_ehtm: Rawcode<"item">;

  /**
   * High Templar's Visage (`ehtv`), a Built-in item of Patch 3.0.0.
   */
  readonly HighTemplarsVisage_ehtv: Rawcode<"item">;

  /**
   * Icecrown Ring (`eicc`), a Built-in item of Patch 3.0.0.
   */
  readonly IcecrownRing_eicc: Rawcode<"item">;

  /**
   * Ice Cold Diamond (`eicd`), a Built-in item of Patch 3.0.0.
   */
  readonly IceColdDiamond_eicd: Rawcode<"item">;

  /**
   * Intricate Emerald Pendant (`eiep`), a Built-in item of Patch 3.0.0.
   */
  readonly IntricateEmeraldPendant_eiep: Rawcode<"item">;

  /**
   * Infectious Ghoul Charm (`eigc`), a Built-in item of Patch 3.0.0.
   */
  readonly InfectiousGhoulCharm_eigc: Rawcode<"item">;

  /**
   * Iron Grip Gauntlets (`eigg`), a Built-in item of Patch 3.0.0.
   */
  readonly IronGripGauntlets_eigg: Rawcode<"item">;

  /**
   * Blade of Inferno (`einf`), a Built-in item of Patch 3.0.0.
   */
  readonly BladeOfInferno_einf: Rawcode<"item">;

  /**
   * Jagged Jade Ring (`ejjr`), a Built-in item of Patch 3.0.0.
   */
  readonly JaggedJadeRing_ejjr: Rawcode<"item">;

  /**
   * Kaldorei Moonglaive (`ekmg`), a Built-in item of Patch 3.0.0.
   */
  readonly KaldoreiMoonglaive_ekmg: Rawcode<"item">;

  /**
   * Kobold Mining Helm (`ekmh`), a Built-in item of Patch 3.0.0.
   */
  readonly KoboldMiningHelm_ekmh: Rawcode<"item">;

  /**
   * Aegis (`elae`), a Built-in item of Patch 3.0.0.
   */
  readonly Aegis_elae: Rawcode<"item">;

  /**
   * Lesser Blade of the Cultist (`elbc`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserBladeOfTheCultist_elbc: Rawcode<"item">;

  /**
   * Lesser Band of the Paladin (`elbp`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserBandOfThePaladin_elbp: Rawcode<"item">;

  /**
   * Lance of the Frozen Phoenix (`elfp`), a Built-in item of Patch 3.0.0.
   */
  readonly LanceOfTheFrozenPhoenix_elfp: Rawcode<"item">;

  /**
   * Lost Forsaken Quiver (`elfq`), a Built-in item of Patch 3.0.0.
   */
  readonly LostForsakenQuiver_elfq: Rawcode<"item">;

  /**
   * Tigerskin Helmet of Precision (`elhp`), a Built-in item of Patch 3.0.0.
   */
  readonly TigerskinHelmetOfPrecision_elhp: Rawcode<"item">;

  /**
   * Lesser Mark of the Forsaken (`elmf`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserMarkOfTheForsaken_elmf: Rawcode<"item">;

  /**
   * Lesser Mark of Time (`elmt`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserMarkOfTime_elmt: Rawcode<"item">;

  /**
   * Lance of the Dawn (`elod`), a Built-in item of Patch 3.0.0.
   */
  readonly LanceOfTheDawn_elod: Rawcode<"item">;

  /**
   * Captain's Helmet of Bravery (`elvl`), a Built-in item of Patch 3.0.0.
   */
  readonly CaptainsHelmetOfBravery_elvl: Rawcode<"item">;

  /**
   * Murloc Costume Gloves (`emcg`), a Built-in item of Patch 3.0.0.
   */
  readonly MurlocCostumeGloves_emcg: Rawcode<"item">;

  /**
   * Manuscript of the Forsaken (`emof`), a Built-in item of Patch 3.0.0.
   */
  readonly ManuscriptOfTheForsaken_emof: Rawcode<"item">;

  /**
   * Mantle of the Highborne (`emoh`), a Built-in item of Patch 3.0.0.
   */
  readonly MantleOfTheHighborne_emoh: Rawcode<"item">;

  /**
   * Mutated Rat's Whiptail (`emrw`), a Built-in item of Patch 3.0.0.
   */
  readonly MutatedRatsWhiptail_emrw: Rawcode<"item">;

  /**
   * Mysterious Twilight Opal (`emto`), a Built-in item of Patch 3.0.0.
   */
  readonly MysteriousTwilightOpal_emto: Rawcode<"item">;

  /**
   * Engraved Scale (`engr`), a Built-in item of Patch 3.0.0.
   */
  readonly EngravedScale_engr: Rawcode<"item">;

  /**
   * Enchanted Gemstone (`engs`), a Built-in item of Patch 3.0.0.
   */
  readonly EnchantedGemstone_engs: Rawcode<"item">;

  /**
   * Nevermelting Ice (`enmi`), a Built-in item of Patch 3.0.0.
   */
  readonly NevermeltingIce_enmi: Rawcode<"item">;

  /**
   * Enchanted Vial (`envl`), a Built-in item of Patch 3.0.0.
   */
  readonly EnchantedVial_envl: Rawcode<"item">;

  /**
   * Bone Buckler (`eobb`), a Built-in item of Patch 3.0.0.
   */
  readonly BoneBuckler_eobb: Rawcode<"item">;

  /**
   * Chipped Shield (`eocs`), a Built-in item of Patch 3.0.0.
   */
  readonly ChippedShield_eocs: Rawcode<"item">;

  /**
   * Overlord's Dreadplate (`eodp`), a Built-in item of Patch 3.0.0.
   */
  readonly OverlordsDreadplate_eodp: Rawcode<"item">;

  /**
   * Fractured Skull (`eofs`), a Built-in item of Patch 3.0.0.
   */
  readonly FracturedSkull_eofs: Rawcode<"item">;

  /**
   * Grieving Blade (`eogb`), a Built-in item of Patch 3.0.0.
   */
  readonly GrievingBlade_eogb: Rawcode<"item">;

  /**
   * Ironforge Defender (`eoid`), a Built-in item of Patch 3.0.0.
   */
  readonly IronforgeDefender_eoid: Rawcode<"item">;

  /**
   * Malachite Shortsword (`eoms`), a Built-in item of Patch 3.0.0.
   */
  readonly MalachiteShortsword_eoms: Rawcode<"item">;

  /**
   * Phalanx Shield (`eops`), a Built-in item of Patch 3.0.0.
   */
  readonly PhalanxShield_eops: Rawcode<"item">;

  /**
   * Shield of the Scarlet Crusade (`eosc`), a Built-in item of Patch 3.0.0.
   */
  readonly ShieldOfTheScarletCrusade_eosc: Rawcode<"item">;

  /**
   * Arcane Cleaver (`epac`), a Built-in item of Patch 3.0.0.
   */
  readonly ArcaneCleaver_epac: Rawcode<"item">;

  /**
   * Abomination's Hook (`epah`), a Built-in item of Patch 3.0.0.
   */
  readonly AbominationsHook_epah: Rawcode<"item">;

  /**
   * Plaguebearer Cuirass (`epbc`), a Built-in item of Patch 3.0.0.
   */
  readonly PlaguebearerCuirass_epbc: Rawcode<"item">;

  /**
   * Plaguebearer Shortsword (`epbs`), a Built-in item of Patch 3.0.0.
   */
  readonly PlaguebearerShortsword_epbs: Rawcode<"item">;

  /**
   * Corrupted Greatsword (`epcg`), a Built-in item of Patch 3.0.0.
   */
  readonly CorruptedGreatsword_epcg: Rawcode<"item">;

  /**
   * Crystal Sword (`epcs`), a Built-in item of Patch 3.0.0.
   */
  readonly CrystalSword_epcs: Rawcode<"item">;

  /**
   * Daybreaker (`epdb`), a Built-in item of Patch 3.0.0.
   */
  readonly Daybreaker_epdb: Rawcode<"item">;

  /**
   * Deathwhisper (`epdw`), a Built-in item of Patch 3.0.0.
   */
  readonly Deathwhisper_epdw: Rawcode<"item">;

  /**
   * Ghoulish Claw (`epfc`), a Built-in item of Patch 3.0.0.
   */
  readonly GhoulishClaw_epfc: Rawcode<"item">;

  /**
   * Gilnean Battleaxe (`epgb`), a Built-in item of Patch 3.0.0.
   */
  readonly GilneanBattleaxe_epgb: Rawcode<"item">;

  /**
   * Guardsman Dagger (`epgd`), a Built-in item of Patch 3.0.0.
   */
  readonly GuardsmanDagger_epgd: Rawcode<"item">;

  /**
   * Guardsman Longsword (`epgl`), a Built-in item of Patch 3.0.0.
   */
  readonly GuardsmanLongsword_epgl: Rawcode<"item">;

  /**
   * Huge Flail (`ephf`), a Built-in item of Patch 3.0.0.
   */
  readonly HugeFlail_ephf: Rawcode<"item">;

  /**
   * Portable Lightning Rod (`eplr`), a Built-in item of Patch 3.0.0.
   */
  readonly PortableLightningRod_eplr: Rawcode<"item">;

  /**
   * Mograine's Might (`epmb`), a Built-in item of Patch 3.0.0.
   */
  readonly MograinesMight_epmb: Rawcode<"item">;

  /**
   * Monastery Mace (`epmm`), a Built-in item of Patch 3.0.0.
   */
  readonly MonasteryMace_epmm: Rawcode<"item">;

  /**
   * Mundane Wand (`epmw`), a Built-in item of Patch 3.0.0.
   */
  readonly MundaneWand_epmw: Rawcode<"item">;

  /**
   * Nightfall (`epnf`), a Built-in item of Patch 3.0.0.
   */
  readonly Nightfall_epnf: Rawcode<"item">;

  /**
   * Suspicious Concoction (`epoa`), a Built-in item of Patch 3.0.0.
   */
  readonly SuspiciousConcoction_epoa: Rawcode<"item">;

  /**
   * Ogre Warclub (`epow`), a Built-in item of Patch 3.0.0.
   */
  readonly OgreWarclub_epow: Rawcode<"item">;

  /**
   * Quarry Pickaxe (`epqp`), a Built-in item of Patch 3.0.0.
   */
  readonly QuarryPickaxe_epqp: Rawcode<"item">;

  /**
   * Primal Ring of Magic (`eprm`), a Built-in item of Patch 3.0.0.
   */
  readonly PrimalRingOfMagic_eprm: Rawcode<"item">;

  /**
   * Skeletal Bow (`epsb`), a Built-in item of Patch 3.0.0.
   */
  readonly SkeletalBow_epsb: Rawcode<"item">;

  /**
   * Sharpened Cleaver (`epsc`), a Built-in item of Patch 3.0.0.
   */
  readonly SharpenedCleaver_epsc: Rawcode<"item">;

  /**
   * Sword of the Ghostlands (`epsg`), a Built-in item of Patch 3.0.0.
   */
  readonly SwordOfTheGhostlands_epsg: Rawcode<"item">;

  /**
   * Protector of the Silver Hand (`epsh`), a Built-in item of Patch 3.0.0.
   */
  readonly ProtectorOfTheSilverHand_epsh: Rawcode<"item">;

  /**
   * Staff of Jordan (`epsj`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfJordan_epsj: Rawcode<"item">;

  /**
   * Soulstealer (`epss`), a Built-in item of Patch 3.0.0.
   */
  readonly Soulstealer_epss: Rawcode<"item">;

  /**
   * The Kingbreaker (`eptk`), a Built-in item of Patch 3.0.0.
   */
  readonly TheKingbreaker_eptk: Rawcode<"item">;

  /**
   * Thornguard Rapier (`eptr`), a Built-in item of Patch 3.0.0.
   */
  readonly ThornguardRapier_eptr: Rawcode<"item">;

  /**
   * Plaguewrought, Blight Incarnate (`epwb`), a Built-in item of Patch 3.0.0.
   */
  readonly PlaguewroughtBlightIncarnate_epwb: Rawcode<"item">;

  /**
   * Painted Wooden Sword (`epws`), a Built-in item of Patch 3.0.0.
   */
  readonly PaintedWoodenSword_epws: Rawcode<"item">;

  /**
   * Ring of the Archdruid (`erad`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheArchdruid_erad: Rawcode<"item">;

  /**
   * Ring of Agitated Fervor (`eraf`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfAgitatedFervor_eraf: Rawcode<"item">;

  /**
   * Rusty Bronze Gauntlets (`erbg`), a Built-in item of Patch 3.0.0.
   */
  readonly RustyBronzeGauntlets_erbg: Rawcode<"item">;

  /**
   * Robes of the Battlemage (`erbm`), a Built-in item of Patch 3.0.0.
   */
  readonly RobesOfTheBattlemage_erbm: Rawcode<"item">;

  /**
   * Caged Soul (`ercs`), a Built-in item of Patch 3.0.0.
   */
  readonly CagedSoul_ercs: Rawcode<"item">;

  /**
   * Diamond Ring (`erdr`), a Built-in item of Patch 3.0.0.
   */
  readonly DiamondRing_erdr: Rawcode<"item">;

  /**
   * Energy Band (`ereb`), a Built-in item of Patch 3.0.0.
   */
  readonly EnergyBand_ereb: Rawcode<"item">;

  /**
   * Echoes of the Fallen (`eref`), a Built-in item of Patch 3.0.0.
   */
  readonly EchoesOfTheFallen_eref: Rawcode<"item">;

  /**
   * Earthen Signet (`eres`), a Built-in item of Patch 3.0.0.
   */
  readonly EarthenSignet_eres: Rawcode<"item">;

  /**
   * Ring of the Fortunate Adventurer (`erfa`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheFortunateAdventurer_erfa: Rawcode<"item">;

  /**
   * Ring of the Firelands (`erfl`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheFirelands_erfl: Rawcode<"item">;

  /**
   * Gift of Greed (`ergg`), a Built-in item of Patch 3.0.0.
   */
  readonly GiftOfGreed_ergg: Rawcode<"item">;

  /**
   * Ring of Greater Mana Efficiency (`ergm`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfGreaterManaEfficiency_ergm: Rawcode<"item">;

  /**
   * Gift of Pride (`ergp`), a Built-in item of Patch 3.0.0.
   */
  readonly GiftOfPride_ergp: Rawcode<"item">;

  /**
   * Gift of Sloth (`ergs`), a Built-in item of Patch 3.0.0.
   */
  readonly GiftOfSloth_ergs: Rawcode<"item">;

  /**
   * Gift of Wrath (`ergw`), a Built-in item of Patch 3.0.0.
   */
  readonly GiftOfWrath_ergw: Rawcode<"item">;

  /**
   * Honed Edge (`erhe`), a Built-in item of Patch 3.0.0.
   */
  readonly HonedEdge_erhe: Rawcode<"item">;

  /**
   * Heart of the Firelord (`erhf`), a Built-in item of Patch 3.0.0.
   */
  readonly HeartOfTheFirelord_erhf: Rawcode<"item">;

  /**
   * Ravage, Herald of Obliteration (`erho`), a Built-in item of Patch 3.0.0.
   */
  readonly RavageHeraldOfObliteration_erho: Rawcode<"item">;

  /**
   * Razorice, Harbinger of Winter (`erhw`), a Built-in item of Patch 3.0.0.
   */
  readonly RazoriceHarbingerOfWinter_erhw: Rawcode<"item">;

  /**
   * Robes of the Kirin Tor (`erkt`), a Built-in item of Patch 3.0.0.
   */
  readonly RobesOfTheKirinTor_erkt: Rawcode<"item">;

  /**
   * Ring of Lesser Restoration (`erlr`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfLesserRestoration_erlr: Rawcode<"item">;

  /**
   * Nerubian Necklace (`ernn`), a Built-in item of Patch 3.0.0.
   */
  readonly NerubianNecklace_ernn: Rawcode<"item">;

  /**
   * Ruby Necklace of Power (`ernp`), a Built-in item of Patch 3.0.0.
   */
  readonly RubyNecklaceOfPower_ernp: Rawcode<"item">;

  /**
   * Ring of Assassination (`eroa`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfAssassination_eroa: Rawcode<"item">;

  /**
   * Ring of Evasion (`eroe`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfEvasion_eroe: Rawcode<"item">;

  /**
   * Rune of Fire (`erof`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfFire_erof: Rawcode<"item">;

  /**
   * Ogre Gauntlets (`erog`), a Built-in item of Patch 3.0.0.
   */
  readonly OgreGauntlets_erog: Rawcode<"item">;

  /**
   * Purifier Blade (`erpb`), a Built-in item of Patch 3.0.0.
   */
  readonly PurifierBlade_erpb: Rawcode<"item">;

  /**
   * Ring of the Runeweaver (`errw`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheRuneweaver_errw: Rawcode<"item">;

  /**
   * Signet of Blood (`ersb`), a Built-in item of Patch 3.0.0.
   */
  readonly SignetOfBlood_ersb: Rawcode<"item">;

  /**
   * Signet of Decay (`ersd`), a Built-in item of Patch 3.0.0.
   */
  readonly SignetOfDecay_ersd: Rawcode<"item">;

  /**
   * Star of Elune (`erse`), a Built-in item of Patch 3.0.0.
   */
  readonly StarOfElune_erse: Rawcode<"item">;

  /**
   * Ring of Stone Fortitude (`ersf`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfStoneFortitude_ersf: Rawcode<"item">;

  /**
   * Ring of the Sacred Grove (`ersg`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheSacredGrove_ersg: Rawcode<"item">;

  /**
   * Tome of Azjol-Nerub (`ersk`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfAzjolNerub_ersk: Rawcode<"item">;

  /**
   * Ring of Sacred Magic (`ersm`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfSacredMagic_ersm: Rawcode<"item">;

  /**
   * Spellbreaker's Necklace (`ersn`), a Built-in item of Patch 3.0.0.
   */
  readonly SpellbreakersNecklace_ersn: Rawcode<"item">;

  /**
   * Ursoc's Gift (`erug`), a Built-in item of Patch 3.0.0.
   */
  readonly UrsocsGift_erug: Rawcode<"item">;

  /**
   * Sanctified Chestplate (`esa1`), a Built-in item of Patch 3.0.0.
   */
  readonly SanctifiedChestplate_esa1: Rawcode<"item">;

  /**
   * Sanctified Gauntlets (`esa2`), a Built-in item of Patch 3.0.0.
   */
  readonly SanctifiedGauntlets_esa2: Rawcode<"item">;

  /**
   * Staff of Arcane Hunger (`esah`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfArcaneHunger_esah: Rawcode<"item">;

  /**
   * Essence of Aszune (`esaz`), a Built-in item of Patch 3.0.0.
   */
  readonly EssenceOfAszune_esaz: Rawcode<"item">;

  /**
   * Bone Staff (`esbs`), a Built-in item of Patch 3.0.0.
   */
  readonly BoneStaff_esbs: Rawcode<"item">;

  /**
   * Spellbreaker Circlet (`esbt`), a Built-in item of Patch 3.0.0.
   */
  readonly SpellbreakerCirclet_esbt: Rawcode<"item">;

  /**
   * Signet of the Crypt Lord (`escl`), a Built-in item of Patch 3.0.0.
   */
  readonly SignetOfTheCryptLord_escl: Rawcode<"item">;

  /**
   * The Screecher (`escr`), a Built-in item of Patch 3.0.0.
   */
  readonly TheScreecher_escr: Rawcode<"item">;

  /**
   * Cork Shooter (`escs`), a Built-in item of Patch 3.0.0.
   */
  readonly CorkShooter_escs: Rawcode<"item">;

  /**
   * Silverpine Forest Shiv (`esfs`), a Built-in item of Patch 3.0.0.
   */
  readonly SilverpineForestShiv_esfs: Rawcode<"item">;

  /**
   * Shepherd's Curse (`eshc`), a Built-in item of Patch 3.0.0.
   */
  readonly ShepherdsCurse_eshc: Rawcode<"item">;

  /**
   * Wildhammer Breastplate (`esib`), a Built-in item of Patch 3.0.0.
   */
  readonly WildhammerBreastplate_esib: Rawcode<"item">;

  /**
   * Kris, the Everburning (`eske`), a Built-in item of Patch 3.0.0.
   */
  readonly KrisTheEverburning_eske: Rawcode<"item">;

  /**
   * Shredder's Left Arm (`esla`), a Built-in item of Patch 3.0.0.
   */
  readonly ShreddersLeftArm_esla: Rawcode<"item">;

  /**
   * Shattered Scourgelord's Crown (`eslc`), a Built-in item of Patch 3.0.0.
   */
  readonly ShatteredScourgelordsCrown_eslc: Rawcode<"item">;

  /**
   * Lich Orb (`eslo`), a Built-in item of Patch 3.0.0.
   */
  readonly LichOrb_eslo: Rawcode<"item">;

  /**
   * Lordaeron Shield (`esls`), a Built-in item of Patch 3.0.0.
   */
  readonly LordaeronShield_esls: Rawcode<"item">;

  /**
   * Necrolyte's March (`esnm`), a Built-in item of Patch 3.0.0.
   */
  readonly NecrolytesMarch_esnm: Rawcode<"item">;

  /**
   * Nexus Shiv (`esns`), a Built-in item of Patch 3.0.0.
   */
  readonly NexusShiv_esns: Rawcode<"item">;

  /**
   * Scepter of Darkness (`esod`), a Built-in item of Patch 3.0.0.
   */
  readonly ScepterOfDarkness_esod: Rawcode<"item">;

  /**
   * Scythe of Frost (`esof`), a Built-in item of Patch 3.0.0.
   */
  readonly ScytheOfFrost_esof: Rawcode<"item">;

  /**
   * Seal of Sylvanas (`esos`), a Built-in item of Patch 3.0.0.
   */
  readonly SealOfSylvanas_esos: Rawcode<"item">;

  /**
   * Shield of the Titans (`esot`), a Built-in item of Patch 3.0.0.
   */
  readonly ShieldOfTheTitans_esot: Rawcode<"item">;

  /**
   * Spell Parrying Buckler (`espb`), a Built-in item of Patch 3.0.0.
   */
  readonly SpellParryingBuckler_espb: Rawcode<"item">;

  /**
   * Sucker Punch Gauntlets (`espg`), a Built-in item of Patch 3.0.0.
   */
  readonly SuckerPunchGauntlets_espg: Rawcode<"item">;

  /**
   * Poison Nettle (`espn`), a Built-in item of Patch 3.0.0.
   */
  readonly PoisonNettle_espn: Rawcode<"item">;

  /**
   * Seal of the Red Court (`esrc`), a Built-in item of Patch 3.0.0.
   */
  readonly SealOfTheRedCourt_esrc: Rawcode<"item">;

  /**
   * Blade of the Scarlet Crusade (`essc`), a Built-in item of Patch 3.0.0.
   */
  readonly BladeOfTheScarletCrusade_essc: Rawcode<"item">;

  /**
   * Staff of the Scarlet Inquisitor (`essi`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfTheScarletInquisitor_essi: Rawcode<"item">;

  /**
   * Sticky Slime Ring (`essr`), a Built-in item of Patch 3.0.0.
   */
  readonly StickySlimeRing_essr: Rawcode<"item">;

  /**
   * Bag of Dust (`etbd`), a Built-in item of Patch 3.0.0.
   */
  readonly BagOfDust_etbd: Rawcode<"item">;

  /**
   * Shamanistic Headwear (`etbh`), a Built-in item of Patch 3.0.0.
   */
  readonly ShamanisticHeadwear_etbh: Rawcode<"item">;

  /**
   * Bottled Storm (`etbs`), a Built-in item of Patch 3.0.0.
   */
  readonly BottledStorm_etbs: Rawcode<"item">;

  /**
   * Edric's Eye (`etee`), a Built-in item of Patch 3.0.0.
   */
  readonly EdricsEye_etee: Rawcode<"item">;

  /**
   * Forsaken Fangs (`etff`), a Built-in item of Patch 3.0.0.
   */
  readonly ForsakenFangs_etff: Rawcode<"item">;

  /**
   * The Impenetrable Fortress (`etif`), a Built-in item of Patch 3.0.0.
   */
  readonly TheImpenetrableFortress_etif: Rawcode<"item">;

  /**
   * Knight's Javelin (`etkj`), a Built-in item of Patch 3.0.0.
   */
  readonly KnightsJavelin_etkj: Rawcode<"item">;

  /**
   * Tiara of the Kirin Tor (`etkt`), a Built-in item of Patch 3.0.0.
   */
  readonly TiaraOfTheKirinTor_etkt: Rawcode<"item">;

  /**
   * Mana Bauble (`etmb`), a Built-in item of Patch 3.0.0.
   */
  readonly ManaBauble_etmb: Rawcode<"item">;

  /**
   * Talisman of Minor Insight (`etmi`), a Built-in item of Patch 3.0.0.
   */
  readonly TalismanOfMinorInsight_etmi: Rawcode<"item">;

  /**
   * Mark of the Phoenix (`etmp`), a Built-in item of Patch 3.0.0.
   */
  readonly MarkOfThePhoenix_etmp: Rawcode<"item">;

  /**
   * Talisman of the Northern Winds (`etnw`), a Built-in item of Patch 3.0.0.
   */
  readonly TalismanOfTheNorthernWinds_etnw: Rawcode<"item">;

  /**
   * Totem of the Ogre Magi (`etom`), a Built-in item of Patch 3.0.0.
   */
  readonly TotemOfTheOgreMagi_etom: Rawcode<"item">;

  /**
   * Talisman of Nightmares (`eton`), a Built-in item of Patch 3.0.0.
   */
  readonly TalismanOfNightmares_eton: Rawcode<"item">;

  /**
   * Twilight Opal Orb (`etoo`), a Built-in item of Patch 3.0.0.
   */
  readonly TwilightOpalOrb_etoo: Rawcode<"item">;

  /**
   * Talisman of Willpower (`etow`), a Built-in item of Patch 3.0.0.
   */
  readonly TalismanOfWillpower_etow: Rawcode<"item">;

  /**
   * Restorative Balm (`etrb`), a Built-in item of Patch 3.0.0.
   */
  readonly RestorativeBalm_etrb: Rawcode<"item">;

  /**
   * Undercity Chain Robes (`eucr`), a Built-in item of Patch 3.0.0.
   */
  readonly UndercityChainRobes_eucr: Rawcode<"item">;

  /**
   * Vampiric Gargoyle Mask (`evgm`), a Built-in item of Patch 3.0.0.
   */
  readonly VampiricGargoyleMask_evgm: Rawcode<"item">;

  /**
   * Vestments of the Wavespeaker (`evow`), a Built-in item of Patch 3.0.0.
   */
  readonly VestmentsOfTheWavespeaker_evow: Rawcode<"item">;

  /**
   * Vestments of the Storm King (`evsk`), a Built-in item of Patch 3.0.0.
   */
  readonly VestmentsOfTheStormKing_evsk: Rawcode<"item">;

  /**
   * Talisman of Evasion (`evtl`), a Built-in item of Patch 3.0.0.
   */
  readonly TalismanOfEvasion_evtl: Rawcode<"item">;

  /**
   * Worn Adventurer's Outfit (`ewao`), a Built-in item of Patch 3.0.0.
   */
  readonly WornAdventurersOutfit_ewao: Rawcode<"item">;

  /**
   * Mordo's Club (`ewbl`), a Built-in item of Patch 3.0.0.
   */
  readonly MordosClub_ewbl: Rawcode<"item">;

  /**
   * Wicked Fang Blade (`ewfb`), a Built-in item of Patch 3.0.0.
   */
  readonly WickedFangBlade_ewfb: Rawcode<"item">;

  /**
   * Wand of the Apprentice (`ewoa`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfTheApprentice_ewoa: Rawcode<"item">;

  /**
   * Wand of the Battlemage (`ewob`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfTheBattlemage_ewob: Rawcode<"item">;

  /**
   * Worn Steel Plate (`ews1`), a Built-in item of Patch 3.0.0.
   */
  readonly WornSteelPlate_ews1: Rawcode<"item">;

  /**
   * Worn Thief's Boots (`ewtb`), a Built-in item of Patch 3.0.0.
   */
  readonly WornThiefsBoots_ewtb: Rawcode<"item">;

  /**
   * Webweaver's Gloves (`ewwg`), a Built-in item of Patch 3.0.0.
   */
  readonly WebweaversGloves_ewwg: Rawcode<"item">;

  /**
   * Borelgore, the Corpulent One (`eymo`), a Built-in item of Patch 3.0.0.
   */
  readonly BorelgoreTheCorpulentOne_eymo: Rawcode<"item">;

  /**
   * Zombie Arm (`ezba`), a Built-in item of Patch 3.0.0.
   */
  readonly ZombieArm_ezba: Rawcode<"item">;

  /**
   * Zandalari Giantcrusher (`ezgc`), a Built-in item of Patch 3.0.0.
   */
  readonly ZandalariGiantcrusher_ezgc: Rawcode<"item">;

  /**
   * Blue Drake Egg (`fgbd`), a Built-in item of Patch 3.0.0.
   */
  readonly BlueDrakeEgg_fgbd: Rawcode<"item">;

  /**
   * Demonic Figurine (`fgdg`), a Built-in item of Patch 3.0.0.
   */
  readonly DemonicFigurine_fgdg: Rawcode<"item">;

  /**
   * Spiked Collar (`fgfh`), a Built-in item of Patch 3.0.0.
   */
  readonly SpikedCollar_fgfh: Rawcode<"item">;

  /**
   * Red Drake Egg (`fgrd`), a Built-in item of Patch 3.0.0.
   */
  readonly RedDrakeEgg_fgrd: Rawcode<"item">;

  /**
   * Stone Token (`fgrg`), a Built-in item of Patch 3.0.0.
   */
  readonly StoneToken_fgrg: Rawcode<"item">;

  /**
   * Book of the Dead (`fgsk`), a Built-in item of Patch 3.0.0.
   */
  readonly BookOfTheDead_fgsk: Rawcode<"item">;

  /**
   * Flare Gun (`fgun`), a Built-in item of Patch 3.0.0.
   */
  readonly FlareGun_fgun: Rawcode<"item">;

  /**
   * Human Flag (`flag`), a Built-in item of Patch 3.0.0.
   */
  readonly HumanFlag_flag: Rawcode<"item">;

  /**
   * Frostguard (`frgd`), a Built-in item of Patch 3.0.0.
   */
  readonly Frostguard_frgd: Rawcode<"item">;

  /**
   * Firehand Gauntlets (`frhg`), a Built-in item of Patch 3.0.0.
   */
  readonly FirehandGauntlets_frhg: Rawcode<"item">;

  /**
   * Frost Wyrm Skull Shield (`fwss`), a Built-in item of Patch 3.0.0.
   */
  readonly FrostWyrmSkullShield_fwss: Rawcode<"item">;

  /**
   * Gloves of Haste (`gcel`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfHaste_gcel: Rawcode<"item">;

  /**
   * Gem of True Seeing (`gemt`), a Built-in item of Patch 3.0.0.
   */
  readonly GemOfTrueSeeing_gemt: Rawcode<"item">;

  /**
   * Glyph of Fortification (`gfor`), a Built-in item of Patch 3.0.0.
   */
  readonly GlyphOfFortification_gfor: Rawcode<"item">;

  /**
   * Orb of Kil'jaeden (`gldo`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfKiljaeden_gldo: Rawcode<"item">;

  /**
   * Skull of Gul'dan (`glsk`), a Built-in item of Patch 3.0.0.
   */
  readonly SkullOfGuldan_glsk: Rawcode<"item">;

  /**
   * Glix's Special (`glxb`), a Built-in item of Patch 3.0.0.
   */
  readonly GlixsSpecial_glxb: Rawcode<"item">;

  /**
   * Gem Fragment (`gmfr`), a Built-in item of Patch 3.0.0.
   */
  readonly GemFragment_gmfr: Rawcode<"item">;

  /**
   * Goblin Land Mines (`gobm`), a Built-in item of Patch 3.0.0.
   */
  readonly GoblinLandMines_gobm: Rawcode<"item">;

  /**
   * Gold Coins (`gold`), a Built-in item of Patch 3.0.0.
   */
  readonly GoldCoins_gold: Rawcode<"item">;

  /**
   * Glyph of Omniscience (`gomn`), a Built-in item of Patch 3.0.0.
   */
  readonly GlyphOfOmniscience_gomn: Rawcode<"item">;

  /**
   * Glyph of Purification (`gopr`), a Built-in item of Patch 3.0.0.
   */
  readonly GlyphOfPurification_gopr: Rawcode<"item">;

  /**
   * Grimoire of Souls (`grsl`), a Built-in item of Patch 3.0.0.
   */
  readonly GrimoireOfSouls_grsl: Rawcode<"item">;

  /**
   * Soul Gem (`gsou`), a Built-in item of Patch 3.0.0.
   */
  readonly SoulGem_gsou: Rawcode<"item">;

  /**
   * Glyph of Ultravision (`guvi`), a Built-in item of Patch 3.0.0.
   */
  readonly GlyphOfUltravision_guvi: Rawcode<"item">;

  /**
   * Gloves of Spell Mastery (`gvsm`), a Built-in item of Patch 3.0.0.
   */
  readonly GlovesOfSpellMastery_gvsm: Rawcode<"item">;

  /**
   * Helm of Battlethirst (`hbth`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfBattlethirst_hbth: Rawcode<"item">;

  /**
   * Hood of Cunning (`hcun`), a Built-in item of Patch 3.0.0.
   */
  readonly HoodOfCunning_hcun: Rawcode<"item">;

  /**
   * Health Stone (`hlst`), a Built-in item of Patch 3.0.0.
   */
  readonly HealthStone_hlst: Rawcode<"item">;

  /**
   * Sacred Relic (`horl`), a Built-in item of Patch 3.0.0.
   */
  readonly SacredRelic_horl: Rawcode<"item">;

  /**
   * Healing Salve (`hslv`), a Built-in item of Patch 3.0.0.
   */
  readonly HealingSalve_hslv: Rawcode<"item">;

  /**
   * Skeletal Mage Mask (`hsmm`), a Built-in item of Patch 3.0.0.
   */
  readonly SkeletalMageMask_hsmm: Rawcode<"item">;

  /**
   * Helm of Valor (`hval`), a Built-in item of Patch 3.0.0.
   */
  readonly HelmOfValor_hval: Rawcode<"item">;

  /**
   * Inferno Stone (`infs`), a Built-in item of Patch 3.0.0.
   */
  readonly InfernoStone_infs: Rawcode<"item">;

  /**
   * Idol of the Wild (`iotw`), a Built-in item of Patch 3.0.0.
   */
  readonly IdolOfTheWild_iotw: Rawcode<"item">;

  /**
   * Ironwood Branch (`iwbr`), a Built-in item of Patch 3.0.0.
   */
  readonly IronwoodBranch_iwbr: Rawcode<"item">;

  /**
   * Jade Ring (`jdrn`), a Built-in item of Patch 3.0.0.
   */
  readonly JadeRing_jdrn: Rawcode<"item">;

  /**
   * Note to Jaina Proudmoore (`jpnt`), a Built-in item of Patch 3.0.0.
   */
  readonly NoteToJainaProudmoore_jpnt: Rawcode<"item">;

  /**
   * Mooncrystal (`k3m1`), a Built-in item of Patch 3.0.0.
   */
  readonly Mooncrystal_k3m1: Rawcode<"item">;

  /**
   * Partial Key of the Three Moons (`k3m2`), a Built-in item of Patch 3.0.0.
   */
  readonly PartialKeyOfTheThreeMoons_k3m2: Rawcode<"item">;

  /**
   * Key of Three Moons (`k3m3`), a Built-in item of Patch 3.0.0.
   */
  readonly KeyOfThreeMoons_k3m3: Rawcode<"item">;

  /**
   * Keg of Ale (`kgal`), a Built-in item of Patch 3.0.0.
   */
  readonly KegOfAle_kgal: Rawcode<"item">;

  /**
   * Killmaim (`klmm`), a Built-in item of Patch 3.0.0.
   */
  readonly Killmaim_klmm: Rawcode<"item">;

  /**
   * Khadgar's Pipe of Insight (`kpin`), a Built-in item of Patch 3.0.0.
   */
  readonly KhadgarsPipeOfInsight_kpin: Rawcode<"item">;

  /**
   * Urn of King Terenas (`ktrm`), a Built-in item of Patch 3.0.0.
   */
  readonly UrnOfKingTerenas_ktrm: Rawcode<"item">;

  /**
   * Blood Key (`kybl`), a Built-in item of Patch 3.0.0.
   */
  readonly BloodKey_kybl: Rawcode<"item">;

  /**
   * Ghost Key (`kygh`), a Built-in item of Patch 3.0.0.
   */
  readonly GhostKey_kygh: Rawcode<"item">;

  /**
   * Moon Key (`kymn`), a Built-in item of Patch 3.0.0.
   */
  readonly MoonKey_kymn: Rawcode<"item">;

  /**
   * Sun Key (`kysn`), a Built-in item of Patch 3.0.0.
   */
  readonly SunKey_kysn: Rawcode<"item">;

  /**
   * Gerard's Lost Ledger (`ledg`), a Built-in item of Patch 3.0.0.
   */
  readonly GerardsLostLedger_ledg: Rawcode<"item">;

  /**
   * Legion Doom-Horn (`lgdh`), a Built-in item of Patch 3.0.0.
   */
  readonly LegionDoomHorn_lgdh: Rawcode<"item">;

  /**
   * The Lion Horn of Stormwind (`lhst`), a Built-in item of Patch 3.0.0.
   */
  readonly TheLionHornOfStormwind_lhst: Rawcode<"item">;

  /**
   * Bundle of Lumber (`lmbr`), a Built-in item of Patch 3.0.0.
   */
  readonly BundleOfLumber_lmbr: Rawcode<"item">;

  /**
   * Lion's Ring (`lnrn`), a Built-in item of Patch 3.0.0.
   */
  readonly LionsRing_lnrn: Rawcode<"item">;

  /**
   * Monster Lure (`lure`), a Built-in item of Patch 3.0.0.
   */
  readonly MonsterLure_lure: Rawcode<"item">;

  /**
   * Manual of Health (`manh`), a Built-in item of Patch 3.0.0.
   */
  readonly ManualOfHealth_manh: Rawcode<"item">;

  /**
   * Medallion of Courage (`mcou`), a Built-in item of Patch 3.0.0.
   */
  readonly MedallionOfCourage_mcou: Rawcode<"item">;

  /**
   * Mechanical Critter (`mcri`), a Built-in item of Patch 3.0.0.
   */
  readonly MechanicalCritter_mcri: Rawcode<"item">;

  /**
   * Magic Key Chain (`mgtk`), a Built-in item of Patch 3.0.0.
   */
  readonly MagicKeyChain_mgtk: Rawcode<"item">;

  /**
   * Maul of Strength (`mlst`), a Built-in item of Patch 3.0.0.
   */
  readonly MaulOfStrength_mlst: Rawcode<"item">;

  /**
   * Mindstaff (`mnsf`), a Built-in item of Patch 3.0.0.
   */
  readonly Mindstaff_mnsf: Rawcode<"item">;

  /**
   * Mana Stone (`mnst`), a Built-in item of Patch 3.0.0.
   */
  readonly ManaStone_mnst: Rawcode<"item">;

  /**
   * Mask of Death (`modt`), a Built-in item of Patch 3.0.0.
   */
  readonly MaskOfDeath_modt: Rawcode<"item">;

  /**
   * Moonstone (`moon`), a Built-in item of Patch 3.0.0.
   */
  readonly Moonstone_moon: Rawcode<"item">;

  /**
   * Mogrin's Report (`mort`), a Built-in item of Patch 3.0.0.
   */
  readonly MogrinsReport_mort: Rawcode<"item">;

  /**
   * Night Elf Flag (`nflg`), a Built-in item of Patch 3.0.0.
   */
  readonly NightElfFlag_nflg: Rawcode<"item">;

  /**
   * Necklace of Spell Immunity (`nspi`), a Built-in item of Patch 3.0.0.
   */
  readonly NecklaceOfSpellImmunity_nspi: Rawcode<"item">;

  /**
   * Orb of Corruption (`ocor`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfCorruption_ocor: Rawcode<"item">;

  /**
   * Orb of Darkness (`odef`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfDarkness_odef: Rawcode<"item">;

  /**
   * Orb of Fire (`ofir`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfFire_ofir: Rawcode<"item">;

  /**
   * Orc Flag (`oflg`), a Built-in item of Patch 3.0.0.
   */
  readonly OrcFlag_oflg: Rawcode<"item">;

  /**
   * Orb of Fire (`ofr2`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfFire_ofr2: Rawcode<"item">;

  /**
   * Orb of Frost (`ofro`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfFrost_ofro: Rawcode<"item">;

  /**
   * Orb of Lightning (`oli2`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfLightning_oli2: Rawcode<"item">;

  /**
   * Orb of Lightning (`olig`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfLightning_olig: Rawcode<"item">;

  /**
   * Orb of Slow (`oslo`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfSlow_oslo: Rawcode<"item">;

  /**
   * Orb of Venom (`oven`), a Built-in item of Patch 3.0.0.
   */
  readonly OrbOfVenom_oven: Rawcode<"item">;

  /**
   * Anti-magic Potion (`pams`), a Built-in item of Patch 3.0.0.
   */
  readonly AntiMagicPotion_pams: Rawcode<"item">;

  /**
   * Clarity Potion (`pclr`), a Built-in item of Patch 3.0.0.
   */
  readonly ClarityPotion_pclr: Rawcode<"item">;

  /**
   * Potion of Divinity (`pdi2`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfDivinity_pdi2: Rawcode<"item">;

  /**
   * Potion of Divinity (`pdiv`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfDivinity_pdiv: Rawcode<"item">;

  /**
   * Pendant of Energy (`penr`), a Built-in item of Patch 3.0.0.
   */
  readonly PendantOfEnergy_penr: Rawcode<"item">;

  /**
   * Essence of Undeath (`peou`), a Built-in item of Patch 3.0.0.
   */
  readonly EssenceOfUndeath_peou: Rawcode<"item">;

  /**
   * Potion of Greater Healing (`pghe`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfGreaterHealing_pghe: Rawcode<"item">;

  /**
   * Potion of Greater Invisibility (`pgin`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfGreaterInvisibility_pgin: Rawcode<"item">;

  /**
   * Potion of Greater Mana (`pgma`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfGreaterMana_pgma: Rawcode<"item">;

  /**
   * Potion of Healing (`phea`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfHealing_phea: Rawcode<"item">;

  /**
   * Phat Lewt (`phlt`), a Built-in item of Patch 3.0.0.
   */
  readonly PhatLewt_phlt: Rawcode<"item">;

  /**
   * Potion of Invisibility (`pinv`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfInvisibility_pinv: Rawcode<"item">;

  /**
   * Lesser Clarity Potion (`plcl`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserClarityPotion_plcl: Rawcode<"item">;

  /**
   * Potion of Mana (`pman`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfMana_pman: Rawcode<"item">;

  /**
   * Pendant of Mana (`pmna`), a Built-in item of Patch 3.0.0.
   */
  readonly PendantOfMana_pmna: Rawcode<"item">;

  /**
   * Potion of Lesser Invulnerability (`pnvl`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfLesserInvulnerability_pnvl: Rawcode<"item">;

  /**
   * Potion of Invulnerability (`pnvu`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfInvulnerability_pnvu: Rawcode<"item">;

  /**
   * Potion of Omniscience (`pomn`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfOmniscience_pomn: Rawcode<"item">;

  /**
   * Potion of Restoration (`pres`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfRestoration_pres: Rawcode<"item">;

  /**
   * Periapt of Vitality (`prvt`), a Built-in item of Patch 3.0.0.
   */
  readonly PeriaptOfVitality_prvt: Rawcode<"item">;

  /**
   * Potion of Speed (`pspd`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfSpeed_pspd: Rawcode<"item">;

  /**
   * Potion of Ultimate Healing (`puhe`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfUltimateHealing_puhe: Rawcode<"item">;

  /**
   * Potion of Ultimate Mana (`puma`), a Built-in item of Patch 3.0.0.
   */
  readonly PotionOfUltimateMana_puma: Rawcode<"item">;

  /**
   * Slippers of Agility +3 (`rag1`), a Built-in item of Patch 3.0.0.
   */
  readonly SlippersOfAgility3_rag1: Rawcode<"item">;

  /**
   * Ring of the Archmagi (`ram1`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheArchmagi_ram1: Rawcode<"item">;

  /**
   * Ring of the Archmagi (`ram2`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheArchmagi_ram2: Rawcode<"item">;

  /**
   * Ring of the Archmagi (`ram3`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheArchmagi_ram3: Rawcode<"item">;

  /**
   * Ring of the Archmagi (`ram4`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfTheArchmagi_ram4: Rawcode<"item">;

  /**
   * Claws of Attack +3 (`rat3`), a Built-in item of Patch 3.0.0.
   */
  readonly ClawsOfAttack3_rat3: Rawcode<"item">;

  /**
   * Claws of Attack +5 (`rat6`), a Built-in item of Patch 3.0.0.
   */
  readonly ClawsOfAttack5_rat6: Rawcode<"item">;

  /**
   * Claws of Attack +8 (`rat9`), a Built-in item of Patch 3.0.0.
   */
  readonly ClawsOfAttack8_rat9: Rawcode<"item">;

  /**
   * Claws of Attack +12 (`ratc`), a Built-in item of Patch 3.0.0.
   */
  readonly ClawsOfAttack12_ratc: Rawcode<"item">;

  /**
   * Claws of Attack +15 (`ratf`), a Built-in item of Patch 3.0.0.
   */
  readonly ClawsOfAttack15_ratf: Rawcode<"item">;

  /**
   * Boots of Haste (`rcdr`), a Built-in item of Patch 3.0.0.
   */
  readonly BootsOfHaste_rcdr: Rawcode<"item">;

  /**
   * Ring of Protection +1 (`rde0`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfProtection1_rde0: Rawcode<"item">;

  /**
   * Ring of Protection +2 (`rde1`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfProtection2_rde1: Rawcode<"item">;

  /**
   * Ring of Protection +3 (`rde2`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfProtection3_rde2: Rawcode<"item">;

  /**
   * Ring of Protection +4 (`rde3`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfProtection4_rde3: Rawcode<"item">;

  /**
   * Ring of Protection +5 (`rde4`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfProtection5_rde4: Rawcode<"item">;

  /**
   * Rune of Dispel Magic (`rdis`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfDispelMagic_rdis: Rawcode<"item">;

  /**
   * Minor Replenishment Potion (`rej1`), a Built-in item of Patch 3.0.0.
   */
  readonly MinorReplenishmentPotion_rej1: Rawcode<"item">;

  /**
   * Lesser Replenishment Potion (`rej2`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserReplenishmentPotion_rej2: Rawcode<"item">;

  /**
   * Replenishment Potion (`rej3`), a Built-in item of Patch 3.0.0.
   */
  readonly ReplenishmentPotion_rej3: Rawcode<"item">;

  /**
   * Greater Replenishment Potion (`rej4`), a Built-in item of Patch 3.0.0.
   */
  readonly GreaterReplenishmentPotion_rej4: Rawcode<"item">;

  /**
   * Lesser Scroll of Replenishment (`rej5`), a Built-in item of Patch 3.0.0.
   */
  readonly LesserScrollOfReplenishment_rej5: Rawcode<"item">;

  /**
   * Greater Scroll of Replenishment (`rej6`), a Built-in item of Patch 3.0.0.
   */
  readonly GreaterScrollOfReplenishment_rej6: Rawcode<"item">;

  /**
   * Rune of Lesser Healing (`rhe1`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfLesserHealing_rhe1: Rawcode<"item">;

  /**
   * Rune of Healing (`rhe2`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfHealing_rhe2: Rawcode<"item">;

  /**
   * Rune of Greater Healing (`rhe3`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfGreaterHealing_rhe3: Rawcode<"item">;

  /**
   * Khadgar's Gem of Health (`rhth`), a Built-in item of Patch 3.0.0.
   */
  readonly KhadgarsGemOfHealth_rhth: Rawcode<"item">;

  /**
   * Mantle of Intelligence +3 (`rin1`), a Built-in item of Patch 3.0.0.
   */
  readonly MantleOfIntelligence3_rin1: Rawcode<"item">;

  /**
   * Ritual Dagger (`ritd`), a Built-in item of Patch 3.0.0.
   */
  readonly RitualDagger_ritd: Rawcode<"item">;

  /**
   * Ring of Regeneration (`rlif`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfRegeneration_rlif: Rawcode<"item">;

  /**
   * Rune of Greater Mana (`rma2`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfGreaterMana_rma2: Rawcode<"item">;

  /**
   * Rune of Mana (`rman`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfMana_rman: Rawcode<"item">;

  /**
   * Ring of Mana Efficiency (`rmef`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfManaEfficiency_rmef: Rawcode<"item">;

  /**
   * Rod of Necromancy (`rnec`), a Built-in item of Patch 3.0.0.
   */
  readonly RodOfNecromancy_rnec: Rawcode<"item">;

  /**
   * Ring of Superiority (`rnsp`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfSuperiority_rnsp: Rawcode<"item">;

  /**
   * Scepter of the Sea (`rots`), a Built-in item of Patch 3.0.0.
   */
  readonly ScepterOfTheSea_rots: Rawcode<"item">;

  /**
   * Rune of Lesser Resurrection (`rre1`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfLesserResurrection_rre1: Rawcode<"item">;

  /**
   * Rune of Greater Resurrection (`rre2`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfGreaterResurrection_rre2: Rawcode<"item">;

  /**
   * Rune of Rebirth (`rreb`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfRebirth_rreb: Rawcode<"item">;

  /**
   * Rune of Restoration (`rres`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfRestoration_rres: Rawcode<"item">;

  /**
   * Lion's Heart (`rrsl`), a Built-in item of Patch 3.0.0.
   */
  readonly LionsHeart_rrsl: Rawcode<"item">;

  /**
   * Dalaran Signet Ring (`rspa`), a Built-in item of Patch 3.0.0.
   */
  readonly DalaranSignetRing_rspa: Rawcode<"item">;

  /**
   * Rune of Speed (`rspd`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfSpeed_rspd: Rawcode<"item">;

  /**
   * Rune of Spirit Link (`rspl`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfSpiritLink_rspl: Rawcode<"item">;

  /**
   * Rune of Shielding (`rsps`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfShielding_rsps: Rawcode<"item">;

  /**
   * Ring of Leeching (`rspv`), a Built-in item of Patch 3.0.0.
   */
  readonly RingOfLeeching_rspv: Rawcode<"item">;

  /**
   * Gauntlets of Ogre Strength +3 (`rst1`), a Built-in item of Patch 3.0.0.
   */
  readonly GauntletsOfOgreStrength3_rst1: Rawcode<"item">;

  /**
   * Runed Gauntlets (`rugt`), a Built-in item of Patch 3.0.0.
   */
  readonly RunedGauntlets_rugt: Rawcode<"item">;

  /**
   * Rusty Mining Pick (`rump`), a Built-in item of Patch 3.0.0.
   */
  readonly RustyMiningPick_rump: Rawcode<"item">;

  /**
   * Rune of the Watcher (`rwat`), a Built-in item of Patch 3.0.0.
   */
  readonly RuneOfTheWatcher_rwat: Rawcode<"item">;

  /**
   * Sobi Mask (`rwiz`), a Built-in item of Patch 3.0.0.
   */
  readonly SobiMask_rwiz: Rawcode<"item">;

  /**
   * Scroll of Animate Dead (`sand`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfAnimateDead_sand: Rawcode<"item">;

  /**
   * Scourge Bone Chimes (`sbch`), a Built-in item of Patch 3.0.0.
   */
  readonly ScourgeBoneChimes_sbch: Rawcode<"item">;

  /**
   * Spell Book (`sbok`), a Built-in item of Patch 3.0.0.
   */
  readonly SpellBook_sbok: Rawcode<"item">;

  /**
   * Scepter of Avarice (`scav`), a Built-in item of Patch 3.0.0.
   */
  readonly ScepterOfAvarice_scav: Rawcode<"item">;

  /**
   * Scepter of Healing (`schl`), a Built-in item of Patch 3.0.0.
   */
  readonly ScepterOfHealing_schl: Rawcode<"item">;

  /**
   * Secret Level Powerup (`sclp`), a Built-in item of Patch 3.0.0.
   */
  readonly SecretLevelPowerup_sclp: Rawcode<"item">;

  /**
   * Scroll of the Unholy Legion (`scul`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfTheUnholyLegion_scul: Rawcode<"item">;

  /**
   * The Heart of Searinox (`sehr`), a Built-in item of Patch 3.0.0.
   */
  readonly TheHeartOfSearinox_sehr: Rawcode<"item">;

  /**
   * Horn of the Clouds (`sfog`), a Built-in item of Patch 3.0.0.
   */
  readonly HornOfTheClouds_sfog: Rawcode<"item">;

  /**
   * Ice Shard (`shar`), a Built-in item of Patch 3.0.0.
   */
  readonly IceShard_shar: Rawcode<"item">;

  /**
   * Scroll of Speed (`shas`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfSpeed_shas: Rawcode<"item">;

  /**
   * Shaman Claws (`shcw`), a Built-in item of Patch 3.0.0.
   */
  readonly ShamanClaws_shcw: Rawcode<"item">;

  /**
   * Shield of the Deathlord (`shdt`), a Built-in item of Patch 3.0.0.
   */
  readonly ShieldOfTheDeathlord_shdt: Rawcode<"item">;

  /**
   * Scroll of Healing (`shea`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfHealing_shea: Rawcode<"item">;

  /**
   * Enchanted Shield (`shen`), a Built-in item of Patch 3.0.0.
   */
  readonly EnchantedShield_shen: Rawcode<"item">;

  /**
   * Shield of Honor (`shhn`), a Built-in item of Patch 3.0.0.
   */
  readonly ShieldOfHonor_shhn: Rawcode<"item">;

  /**
   * Shimmerglaze Roast (`shrs`), a Built-in item of Patch 3.0.0.
   */
  readonly ShimmerglazeRoast_shrs: Rawcode<"item">;

  /**
   * Shamanic Totem (`shtm`), a Built-in item of Patch 3.0.0.
   */
  readonly ShamanicTotem_shtm: Rawcode<"item">;

  /**
   * Shimmerweed (`shwd`), a Built-in item of Patch 3.0.0.
   */
  readonly Shimmerweed_shwd: Rawcode<"item">;

  /**
   * Spider Silk Broach (`silk`), a Built-in item of Patch 3.0.0.
   */
  readonly SpiderSilkBroach_silk: Rawcode<"item">;

  /**
   * Skeletal Artifact (`skrt`), a Built-in item of Patch 3.0.0.
   */
  readonly SkeletalArtifact_skrt: Rawcode<"item">;

  /**
   * Skull Shield (`sksh`), a Built-in item of Patch 3.0.0.
   */
  readonly SkullShield_sksh: Rawcode<"item">;

  /**
   * Sacrificial Skull (`skul`), a Built-in item of Patch 3.0.0.
   */
  readonly SacrificialSkull_skul: Rawcode<"item">;

  /**
   * Scroll of Mana (`sman`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfMana_sman: Rawcode<"item">;

  /**
   * Staff of Negation (`sneg`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfNegation_sneg: Rawcode<"item">;

  /**
   * Shadow Orb +1 (`sor1`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb1_sor1: Rawcode<"item">;

  /**
   * Shadow Orb +2 (`sor2`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb2_sor2: Rawcode<"item">;

  /**
   * Shadow Orb +3 (`sor3`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb3_sor3: Rawcode<"item">;

  /**
   * Shadow Orb +4 (`sor4`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb4_sor4: Rawcode<"item">;

  /**
   * Shadow Orb +5 (`sor5`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb5_sor5: Rawcode<"item">;

  /**
   * Shadow Orb +6 (`sor6`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb6_sor6: Rawcode<"item">;

  /**
   * Shadow Orb +7 (`sor7`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb7_sor7: Rawcode<"item">;

  /**
   * Shadow Orb +8 (`sor8`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb8_sor8: Rawcode<"item">;

  /**
   * Shadow Orb +9 (`sor9`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb9_sor9: Rawcode<"item">;

  /**
   * Shadow Orb +10 (`sora`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrb10_sora: Rawcode<"item">;

  /**
   * Shadow Orb Fragment (`sorf`), a Built-in item of Patch 3.0.0.
   */
  readonly ShadowOrbFragment_sorf: Rawcode<"item">;

  /**
   * Soul (`soul`), a Built-in item of Patch 3.0.0.
   */
  readonly Soul_soul: Rawcode<"item">;

  /**
   * Staff of Preservation (`spre`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfPreservation_spre: Rawcode<"item">;

  /**
   * Spider Ring (`sprn`), a Built-in item of Patch 3.0.0.
   */
  readonly SpiderRing_sprn: Rawcode<"item">;

  /**
   * Scroll of Protection (`spro`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfProtection_spro: Rawcode<"item">;

  /**
   * Amulet of Spell Shield (`spsh`), a Built-in item of Patch 3.0.0.
   */
  readonly AmuletOfSpellShield_spsh: Rawcode<"item">;

  /**
   * Searing Blade (`srbd`), a Built-in item of Patch 3.0.0.
   */
  readonly SearingBlade_srbd: Rawcode<"item">;

  /**
   * Scroll of Regeneration (`sreg`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfRegeneration_sreg: Rawcode<"item">;

  /**
   * Scroll of Restoration (`sres`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfRestoration_sres: Rawcode<"item">;

  /**
   * Scroll of the Beast (`sror`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfTheBeast_sror: Rawcode<"item">;

  /**
   * Scroll of Resurrection (`srrc`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfResurrection_srrc: Rawcode<"item">;

  /**
   * Serathil (`srtl`), a Built-in item of Patch 3.0.0.
   */
  readonly Serathil_srtl: Rawcode<"item">;

  /**
   * Staff of Sanctuary (`ssan`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfSanctuary_ssan: Rawcode<"item">;

  /**
   * Staff of Silence (`ssil`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfSilence_ssil: Rawcode<"item">;

  /**
   * Staff of Teleportation (`stel`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfTeleportation_stel: Rawcode<"item">;

  /**
   * Clockwork Penguin (`stpg`), a Built-in item of Patch 3.0.0.
   */
  readonly ClockworkPenguin_stpg: Rawcode<"item">;

  /**
   * Staff of Reanimation (`stre`), a Built-in item of Patch 3.0.0.
   */
  readonly StaffOfReanimation_stre: Rawcode<"item">;

  /**
   * Sturdy War Axe (`stwa`), a Built-in item of Patch 3.0.0.
   */
  readonly SturdyWarAxe_stwa: Rawcode<"item">;

  /**
   * Scroll of Town Portal (`stwp`), a Built-in item of Patch 3.0.0.
   */
  readonly ScrollOfTownPortal_stwp: Rawcode<"item">;

  /**
   * Seed of Expulsion (`sxpl`), a Built-in item of Patch 3.0.0.
   */
  readonly SeedOfExpulsion_sxpl: Rawcode<"item">;

  /**
   * Tiny Altar of Kings (`tbak`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyAltarOfKings_tbak: Rawcode<"item">;

  /**
   * Tiny Barracks (`tbar`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyBarracks_tbar: Rawcode<"item">;

  /**
   * Tiny Blacksmith (`tbsm`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyBlacksmith_tbsm: Rawcode<"item">;

  /**
   * Tiny Castle (`tcas`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyCastle_tcas: Rawcode<"item">;

  /**
   * Tome of Agility (`tdex`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfAgility_tdex: Rawcode<"item">;

  /**
   * Tome of Agility +2 (`tdx2`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfAgility2_tdx2: Rawcode<"item">;

  /**
   * Goblin Night Scope (`tels`), a Built-in item of Patch 3.0.0.
   */
  readonly GoblinNightScope_tels: Rawcode<"item">;

  /**
   * Tome of Experience (`texp`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfExperience_texp: Rawcode<"item">;

  /**
   * Tiny Farm (`tfar`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyFarm_tfar: Rawcode<"item">;

  /**
   * Tiny Great Hall (`tgrh`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyGreatHall_tgrh: Rawcode<"item">;

  /**
   * Tome of Greater Experience (`tgxp`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfGreaterExperience_tgxp: Rawcode<"item">;

  /**
   * Thunderlizard Diamond (`thdm`), a Built-in item of Patch 3.0.0.
   */
  readonly ThunderlizardDiamond_thdm: Rawcode<"item">;

  /**
   * Thunder Lizard Egg (`thle`), a Built-in item of Patch 3.0.0.
   */
  readonly ThunderLizardEgg_thle: Rawcode<"item">;

  /**
   * Tome of Intelligence +2 (`tin2`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfIntelligence2_tin2: Rawcode<"item">;

  /**
   * Tome of Intelligence (`tint`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfIntelligence_tint: Rawcode<"item">;

  /**
   * Tome of Power (`tkno`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfPower_tkno: Rawcode<"item">;

  /**
   * Tiny Lumber Mill (`tlum`), a Built-in item of Patch 3.0.0.
   */
  readonly TinyLumberMill_tlum: Rawcode<"item">;

  /**
   * Totem of Might (`tmmt`), a Built-in item of Patch 3.0.0.
   */
  readonly TotemOfMight_tmmt: Rawcode<"item">;

  /**
   * Tome of Sacrifices (`tmsc`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfSacrifices_tmsc: Rawcode<"item">;

  /**
   * Talisman of the Wild (`totw`), a Built-in item of Patch 3.0.0.
   */
  readonly TalismanOfTheWild_totw: Rawcode<"item">;

  /**
   * Tome of Knowledge (`tpow`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfKnowledge_tpow: Rawcode<"item">;

  /**
   * Tome of Retraining (`tret`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfRetraining_tret: Rawcode<"item">;

  /**
   * Ivory Tower (`tsct`), a Built-in item of Patch 3.0.0.
   */
  readonly IvoryTower_tsct: Rawcode<"item">;

  /**
   * Tome of Strength +2 (`tst2`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfStrength2_tst2: Rawcode<"item">;

  /**
   * Tome of Strength (`tstr`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfStrength_tstr: Rawcode<"item">;

  /**
   * Tome of Talent (`ttal`), a Built-in item of Patch 3.0.0.
   */
  readonly TomeOfTalent_ttal: Rawcode<"item">;

  /**
   * Undead Flag (`uflg`), a Built-in item of Patch 3.0.0.
   */
  readonly UndeadFlag_uflg: Rawcode<"item">;

  /**
   * Vampiric Potion (`vamp`), a Built-in item of Patch 3.0.0.
   */
  readonly VampiricPotion_vamp: Rawcode<"item">;

  /**
   * Voodoo Doll (`vddl`), a Built-in item of Patch 3.0.0.
   */
  readonly VoodooDoll_vddl: Rawcode<"item">;

  /**
   * Vine of Purification (`vpur`), a Built-in item of Patch 3.0.0.
   */
  readonly VineOfPurification_vpur: Rawcode<"item">;

  /**
   * Warsong Battle Drums (`war2`), a Built-in item of Patch 3.0.0.
   */
  readonly WarsongBattleDrums_war2: Rawcode<"item">;

  /**
   * Warsong Battle Drums (`ward`), a Built-in item of Patch 3.0.0.
   */
  readonly WarsongBattleDrums_ward: Rawcode<"item">;

  /**
   * Wand of the Wind (`wcyc`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfTheWind_wcyc: Rawcode<"item">;

  /**
   * Healing Wards (`whwd`), a Built-in item of Patch 3.0.0.
   */
  readonly HealingWards_whwd: Rawcode<"item">;

  /**
   * Amulet of the Wild (`wild`), a Built-in item of Patch 3.0.0.
   */
  readonly AmuletOfTheWild_wild: Rawcode<"item">;

  /**
   * Wand of Illusion (`will`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfIllusion_will: Rawcode<"item">;

  /**
   * Wand of Lightning Shield (`wlsd`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfLightningShield_wlsd: Rawcode<"item">;

  /**
   * Wand of Negation (`wneg`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfNegation_wneg: Rawcode<"item">;

  /**
   * Wand of Neutralization (`wneu`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfNeutralization_wneu: Rawcode<"item">;

  /**
   * Wirt's Other Leg (`wolg`), a Built-in item of Patch 3.0.0.
   */
  readonly WirtsOtherLeg_wolg: Rawcode<"item">;

  /**
   * Wand of Mana Stealing (`woms`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfManaStealing_woms: Rawcode<"item">;

  /**
   * Wand of Shadowsight (`wshs`), a Built-in item of Patch 3.0.0.
   */
  readonly WandOfShadowsight_wshs: Rawcode<"item">;

  /**
   * Sentry Wards (`wswd`), a Built-in item of Patch 3.0.0.
   */
  readonly SentryWards_wswd: Rawcode<"item">;

  /**
   * Wirt's Leg (`wtlg`), a Built-in item of Patch 3.0.0.
   */
  readonly WirtsLeg_wtlg: Rawcode<"item">;
};
