// Generated by reforged-builtins from the Built-in objects of Game version 3.0.0 (3.0.0/index.json).
// Derived identifiers only: Rawcodes, Object kinds, races, enUS names and Game data sets.
// Not affiliated with or endorsed by Blizzard Entertainment. Warcraft is a trademark of Blizzard Entertainment.
// The names and Rawcodes are derived from the game's data and are not licensed by this package.
// Never edited by hand: `pnpm builtins:generate` writes it and `pnpm builtins:check` compares it.

/**
 * The Built-in upgrades of Patch 3.0.0, each named by its enUS name and Rawcode, such as `Upgrades.CorrosiveBreath_Recb`.
 */
export declare const Upgrades: {
  /**
   * Corrosive Breath (`Recb`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly CorrosiveBreath_Recb: Rawcode<"upgrade">;

  /**
   * Druid of the Claw Adept Training (`Redc`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly DruidOfTheClawAdeptTraining_Redc: Rawcode<"upgrade">;

  /**
   * Druid of the Talon Adept Training (`Redt`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly DruidOfTheTalonAdeptTraining_Redt: Rawcode<"upgrade">;

  /**
   * Mark of the Claw (`Reeb`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly MarkOfTheClaw_Reeb: Rawcode<"upgrade">;

  /**
   * Mark of the Talon (`Reec`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly MarkOfTheTalon_Reec: Rawcode<"upgrade">;

  /**
   * Hardened Skin (`Rehs`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly HardenedSkin_Rehs: Rawcode<"upgrade">;

  /**
   * Hippogryph Taming (`Reht`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly HippogryphTaming_Reht: Rawcode<"upgrade">;

  /**
   * Improved Bows (`Reib`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly ImprovedBows_Reib: Rawcode<"upgrade">;

  /**
   * Moon Armor (`Rema`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly MoonArmor_Rema: Rawcode<"upgrade">;

  /**
   * Upgrade Moon Glaive (`Remg`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly UpgradeMoonGlaive_Remg: Rawcode<"upgrade">;

  /**
   * Marksmanship (`Remk`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly Marksmanship_Remk: Rawcode<"upgrade">;

  /**
   * Nature's Blessing (`Renb`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly NaturesBlessing_Renb: Rawcode<"upgrade">;

  /**
   * Vorpal Blades (`Repb`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly VorpalBlades_Repb: Rawcode<"upgrade">;

  /**
   * Backpack (`Repm`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly Backpack_Repm: Rawcode<"upgrade">;

  /**
   * Reinforced Hides (`Rerh`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly ReinforcedHides_Rerh: Rawcode<"upgrade">;

  /**
   * Resistant Skin (`Rers`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly ResistantSkin_Rers: Rawcode<"upgrade">;

  /**
   * Sentinel (`Resc`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly Sentinel_Resc: Rawcode<"upgrade">;

  /**
   * Abolish Magic (`Resi`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly AbolishMagic_Resi: Rawcode<"upgrade">;

  /**
   * Strength of the Moon (`Resm`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly StrengthOfTheMoon_Resm: Rawcode<"upgrade">;

  /**
   * Strength of the Wild (`Resw`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly StrengthOfTheWild_Resw: Rawcode<"upgrade">;

  /**
   * Ultravision (`Reuv`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly Ultravision_Reuv: Rawcode<"upgrade">;

  /**
   * Well Spring (`Rews`), a Built-in upgrade of Patch 3.0.0, race nightelf.
   */
  readonly WellSpring_Rews: Rawcode<"upgrade">;

  /**
   * Glyph of Fortification (`Rgfo`), a Built-in upgrade of Patch 3.0.0, race unknown.
   */
  readonly GlyphOfFortification_Rgfo: Rawcode<"upgrade">;

  /**
   * Glyph of Ultravision (`Rguv`), a Built-in upgrade of Patch 3.0.0, race unknown.
   */
  readonly GlyphOfUltravision_Rguv: Rawcode<"upgrade">;

  /**
   * Improved Masonry (`Rhac`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly ImprovedMasonry_Rhac: Rawcode<"upgrade">;

  /**
   * Animal War Training (`Rhan`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly AnimalWarTraining_Rhan: Rawcode<"upgrade">;

  /**
   * Iron Plating (`Rhar`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly IronPlating_Rhar: Rawcode<"upgrade">;

  /**
   * Cloud (`Rhcd`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly Cloud_Rhcd: Rawcode<"upgrade">;

  /**
   * Defend (`Rhde`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly Defend_Rhde: Rawcode<"upgrade">;

  /**
   * Flak Cannons (`Rhfc`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly FlakCannons_Rhfc: Rawcode<"upgrade">;

  /**
   * Flare (`Rhfl`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly Flare_Rhfl: Rawcode<"upgrade">;

  /**
   * Fragmentation Shards (`Rhfs`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly FragmentationShards_Rhfs: Rawcode<"upgrade">;

  /**
   * Flying Machine Bombs (`Rhgb`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly FlyingMachineBombs_Rhgb: Rawcode<"upgrade">;

  /**
   * Storm Hammers (`Rhhb`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly StormHammers_Rhhb: Rawcode<"upgrade">;

  /**
   * Studded Leather Armor (`Rhla`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly StuddedLeatherArmor_Rhla: Rawcode<"upgrade">;

  /**
   * Improved Lumber Harvesting (`Rhlh`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly ImprovedLumberHarvesting_Rhlh: Rawcode<"upgrade">;

  /**
   * Iron Forged Swords (`Rhme`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly IronForgedSwords_Rhme: Rawcode<"upgrade">;

  /**
   * Backpack (`Rhpm`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly Backpack_Rhpm: Rawcode<"upgrade">;

  /**
   * Priest Adept Training (`Rhpt`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly PriestAdeptTraining_Rhpt: Rawcode<"upgrade">;

  /**
   * Black Gunpowder (`Rhra`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly BlackGunpowder_Rhra: Rawcode<"upgrade">;

  /**
   * Long Rifles (`Rhri`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly LongRifles_Rhri: Rawcode<"upgrade">;

  /**
   * Barrage (`Rhrt`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly Barrage_Rhrt: Rawcode<"upgrade">;

  /**
   * Sundering Blades (`Rhsb`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly SunderingBlades_Rhsb: Rawcode<"upgrade">;

  /**
   * Magic Sentry (`Rhse`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly MagicSentry_Rhse: Rawcode<"upgrade">;

  /**
   * Control Magic (`Rhss`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly ControlMagic_Rhss: Rawcode<"upgrade">;

  /**
   * Sorceress Adept Training (`Rhst`), a Built-in upgrade of Patch 3.0.0, race human.
   */
  readonly SorceressAdeptTraining_Rhst: Rawcode<"upgrade">;

  /**
   * Coral Scales (`Rnam`), a Built-in upgrade of Patch 3.0.0, race naga.
   */
  readonly CoralScales_Rnam: Rawcode<"upgrade">;

  /**
   * Coral Blades (`Rnat`), a Built-in upgrade of Patch 3.0.0, race naga.
   */
  readonly CoralBlades_Rnat: Rawcode<"upgrade">;

  /**
   * Ensnare (`Rnen`), a Built-in upgrade of Patch 3.0.0, race naga.
   */
  readonly Ensnare_Rnen: Rawcode<"upgrade">;

  /**
   * Submerge (`Rnsb`), a Built-in upgrade of Patch 3.0.0, race naga.
   */
  readonly Submerge_Rnsb: Rawcode<"upgrade">;

  /**
   * Abolish Magic (`Rnsi`), a Built-in upgrade of Patch 3.0.0, race naga.
   */
  readonly AbolishMagic_Rnsi: Rawcode<"upgrade">;

  /**
   * Naga Siren Adept Training (`Rnsw`), a Built-in upgrade of Patch 3.0.0, race naga.
   */
  readonly NagaSirenAdeptTraining_Rnsw: Rawcode<"upgrade">;

  /**
   * Steel Armor (`Roar`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly SteelArmor_Roar: Rawcode<"upgrade">;

  /**
   * Burning Oil (`Robf`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly BurningOil_Robf: Rawcode<"upgrade">;

  /**
   * Berserker Upgrade (`Robk`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly BerserkerUpgrade_Robk: Rawcode<"upgrade">;

  /**
   * Brute Strength (`Robs`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly BruteStrength_Robs: Rawcode<"upgrade">;

  /**
   * Chaos (`Roch`), a Built-in upgrade of Patch 3.0.0, race demon.
   */
  readonly Chaos_Roch: Rawcode<"upgrade">;

  /**
   * Ensnare (`Roen`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly Ensnare_Roen: Rawcode<"upgrade">;

  /**
   * Liquid Fire (`Rolf`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly LiquidFire_Rolf: Rawcode<"upgrade">;

  /**
   * Steel Melee Weapons (`Rome`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly SteelMeleeWeapons_Rome: Rawcode<"upgrade">;

  /**
   * Pillage (`Ropg`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly Pillage_Ropg: Rawcode<"upgrade">;

  /**
   * Backpack (`Ropm`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly Backpack_Ropm: Rawcode<"upgrade">;

  /**
   * Steel Ranged Weapons (`Rora`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly SteelRangedWeapons_Rora: Rawcode<"upgrade">;

  /**
   * Reinforced Defenses (`Rorb`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly ReinforcedDefenses_Rorb: Rawcode<"upgrade">;

  /**
   * Spiked Barricades (`Rosp`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly SpikedBarricades_Rosp: Rawcode<"upgrade">;

  /**
   * Shaman Adept Training (`Rost`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly ShamanAdeptTraining_Rost: Rawcode<"upgrade">;

  /**
   * Troll Regeneration (`Rotr`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly TrollRegeneration_Rotr: Rawcode<"upgrade">;

  /**
   * Envenomed Spears (`Rovs`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly EnvenomedSpears_Rovs: Rawcode<"upgrade">;

  /**
   * Witch Doctor Adept Training (`Rowd`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly WitchDoctorAdeptTraining_Rowd: Rawcode<"upgrade">;

  /**
   * Pulverize Damage Increase (`Rows`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly PulverizeDamageIncrease_Rows: Rawcode<"upgrade">;

  /**
   * Spirit Walker Adept Training (`Rowt`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly SpiritWalkerAdeptTraining_Rowt: Rawcode<"upgrade">;

  /**
   * Cannibalize (`Ruac`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly Cannibalize_Ruac: Rawcode<"upgrade">;

  /**
   * Unholy Armor (`Ruar`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly UnholyArmor_Ruar: Rawcode<"upgrade">;

  /**
   * Banshee Adept Training (`Ruba`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly BansheeAdeptTraining_Ruba: Rawcode<"upgrade">;

  /**
   * Burrow (`Rubu`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly Burrow_Rubu: Rawcode<"upgrade">;

  /**
   * Creature Carapace (`Rucr`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly CreatureCarapace_Rucr: Rawcode<"upgrade">;

  /**
   * Exhume Corpses (`Ruex`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly ExhumeCorpses_Ruex: Rawcode<"upgrade">;

  /**
   * Freezing Breath (`Rufb`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly FreezingBreath_Rufb: Rawcode<"upgrade">;

  /**
   * Ghoul Frenzy (`Rugf`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly GhoulFrenzy_Rugf: Rawcode<"upgrade">;

  /**
   * Unholy Strength (`Rume`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly UnholyStrength_Rume: Rawcode<"upgrade">;

  /**
   * Necromancer Adept Training (`Rune`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly NecromancerAdeptTraining_Rune: Rawcode<"upgrade">;

  /**
   * Disease Cloud (`Rupc`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly DiseaseCloud_Rupc: Rawcode<"upgrade">;

  /**
   * Backpack (`Rupm`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly Backpack_Rupm: Rawcode<"upgrade">;

  /**
   * Creature Attack (`Rura`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly CreatureAttack_Rura: Rawcode<"upgrade">;

  /**
   * Stone Form (`Rusf`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly StoneForm_Rusf: Rawcode<"upgrade">;

  /**
   * Skeletal Longevity (`Rusl`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly SkeletalLongevity_Rusl: Rawcode<"upgrade">;

  /**
   * Skeletal Mastery (`Rusm`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly SkeletalMastery_Rusm: Rawcode<"upgrade">;

  /**
   * Destroyer Form (`Rusp`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly DestroyerForm_Rusp: Rawcode<"upgrade">;

  /**
   * Web (`Ruwb`), a Built-in upgrade of Patch 3.0.0, race undead.
   */
  readonly Web_Ruwb: Rawcode<"upgrade">;

  /**
   * War Drums Damage Increase (`Rwdm`), a Built-in upgrade of Patch 3.0.0, race orc.
   */
  readonly WarDrumsDamageIncrease_Rwdm: Rawcode<"upgrade">;
};
