#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# The first-publish wizard (#149): human steps 1 to 4 of docs/release.md,
# "Human steps". It publishes 1.0.0-alpha.0 of the four packages from a local
# checkout of master with a granular npm token, then walks the maintainer
# through each package's trusted publisher and its "Require two-factor
# authentication and disallow tokens" setting on npmjs.com, and the
# revocation of the token.
#
# From the repository root, in Git Bash (Windows) or a Linux shell:
#
#   bash release/first-publish.sh            the real run
#   bash release/first-publish.sh --dry-run  prints every command, runs none
#
# It checks what the npm CLI and git can check and stops at the first failed
# check, saying what to fix. What only npmjs.com shows (the trusted
# publisher, the package's publishing access, the token's 2FA setting and
# its revocation) it asks the maintainer to confirm. It is safe to re-run: a
# package npm already holds with `next` at 1.0.0-alpha.0 is not published
# again. It never stores or prints the token: the token goes into the user
# npm config for the run and is removed from it when the wizard exits.
#
# The dry run still runs the read-only checks (git, the pre mode state, the
# versions, what npm holds). It only warns about the branch and the working
# tree, so the wizard can be reviewed from any branch; it answers every
# confirmation with yes and opens no browser.

readonly PACKAGES=(reforged-ts reforged-types reforged-test eslint-plugin-reforged)
readonly VERSION=1.0.0-alpha.0
readonly DIST_TAG=next
readonly PRE_TAG=alpha
readonly REPO_OWNER=phmilk
readonly REPO_NAME=reforged-ts
readonly WORKFLOW=release.yml
readonly AUTH_KEY=//registry.npmjs.org/:_authToken
readonly GUIDE=docs/release.md
readonly RERUN="bash release/first-publish.sh"

usage() {
  printf 'Usage: %s [--dry-run]\n' "$RERUN"
  printf '  The first publish of %s: docs/release.md, "Human steps".\n' "$VERSION"
}

DRY_RUN=false
if [[ $# -gt 1 ]]; then usage >&2; exit 2; fi
case "${1:-}" in
  "") ;;
  --dry-run) DRY_RUN=true ;;
  -h | --help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac

# Git Bash rewrites arguments that look like POSIX paths, and would turn
# `//registry.npmjs.org/...` into `/registry.npmjs.org/...`. Paths handed to
# native programs go through cygpath instead (see native_path).
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'

# Nothing this wizard captures is persisted: no value is read from or
# written to a .env file.
ENV_FILE=/dev/null

TOKEN_SET=false # the wizard put a token into the user npm config
NPM_USER=""
PACK_DIR=""
ERR_FILE=$(mktemp)

cleanup() {
  rm -f "$ERR_FILE"
  if [[ -n "$PACK_DIR" ]]; then rm -rf "$PACK_DIR"; fi
  if $TOKEN_SET; then
    npm config delete "$AUTH_KEY" >/dev/null 2>&1 || true
    TOKEN_SET=false
    printf '  %s✓ removed the npm token from your npm config%s\n' "$GREEN" "$RESET"
  fi
}
trap cleanup EXIT
trap 'exit 130' INT TERM

# In the dry run, nothing waits for the human and no browser opens: the
# library's gates print what they would ask instead.
if $DRY_RUN; then
  _clear() { :; }
  pause() { printf '  %s%s%s %s(dry run: continues)%s\n' "$DIM" "${1:-Press Enter to continue}" "$RESET" "$YELLOW" "$RESET"; }
  confirm() { printf '  %s? %s%s %s(dry run: answered yes)%s\n' "$YELLOW" "$1" "$RESET" "$YELLOW" "$RESET"; }
  open_url() { printf '  %s↗ would open%s %s\n' "$GREEN" "$RESET" "$1"; }
fi

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# fail "what failed" ["what to fix"...] stops the wizard.
fail() {
  printf '\n  %s%s✗ %s%s\n' "$BOLD" "$RED" "$1" "$RESET" >&2
  shift
  local line
  for line in "$@"; do printf '    %s\n' "$line" >&2; done
  printf '\n  %sThen re-run: %s%s%s\n\n' "$DIM" "$RERUN" "$($DRY_RUN && printf ' --dry-run')" "$RESET" >&2
  exit 1
}

# soft_fail stops the wizard, except in the dry run, where it only warns:
# the checks of the repository state, so the dry run can be reviewed from
# any branch.
soft_fail() {
  if $DRY_RUN; then
    warn "$1 (a real run stops here)"
    shift
    local line
    for line in "$@"; do note "  $line"; done
    return 0
  fi
  fail "$@"
}

# run CMD... prints the command, then runs it; in the dry run it only prints.
run() {
  printf '  %s$ %s%s\n' "$BOLD" "$*" "$RESET"
  $DRY_RUN || "$@"
}

# native_path PATH: PATH as native programs (node, pnpm) read it.
native_path() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}

# npm_next PACKAGE prints the version the `next` dist-tag of PACKAGE points
# at: empty when npm has no such package or no such tag. Stops the wizard
# when npm cannot be asked.
npm_next() {
  local out
  if out=$(npm view "$1" "dist-tags.$DIST_TAG" 2>"$ERR_FILE"); then
    printf '%s' "$out"
  elif grep -q E404 "$ERR_FILE"; then
    return 0
  else
    fail "npm view $1 failed:" "$(cat "$ERR_FILE")" "Check your network and the npm registry."
  fi
}

# npm_has_version PACKAGE: whether npm holds VERSION of PACKAGE.
npm_has_version() {
  [[ -n "$(npm view "$1@$VERSION" version 2>/dev/null)" ]]
}

# manifest_field FILE FIELD prints FIELD of the JSON file FILE.
manifest_field() {
  node -e 'const v = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))[process.argv[2]]; process.stdout.write(v === undefined ? "" : String(v))' "$1" "$2"
}

# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
PENDING=() # the packages npm does not hold with next at VERSION yet

if $DRY_RUN; then
  banner "First publish of $VERSION (dry run: nothing is published)"
else
  banner "First publish of $VERSION"
fi

# ── 1. Before anything ────────────────────────────────────────────────────
stage "Check the checkout and what npm holds"

for tool in git node pnpm npm; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is not on the PATH." "Install it; $GUIDE and the root README list the Toolchain."
done
ok "git, node, pnpm and npm are on the PATH"

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) ||
  fail "This is not a git checkout." "Run the wizard from a clone of $REPO_OWNER/$REPO_NAME."
cd "$ROOT"
[[ -f .changeset/config.json && -f packages/reforged-ts/package.json ]] ||
  fail "$ROOT is not the $REPO_NAME repository." "Run the wizard from a clone of $REPO_OWNER/$REPO_NAME."

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" == master ]]; then
  ok "on master"
else
  soft_fail "The checkout is on $BRANCH, not master." "git switch master && git pull --ff-only"
fi

if [[ -z "$(git status --porcelain)" ]]; then
  ok "the working tree is clean"
else
  soft_fail "The working tree has changes:" "$(git status --short)" "Commit, stash or discard them: the wizard publishes what master holds."
fi

if git fetch --quiet origin master 2>"$ERR_FILE"; then
  if [[ "$(git rev-parse HEAD)" == "$(git rev-parse origin/master)" ]]; then
    ok "HEAD is origin/master"
  else
    soft_fail "HEAD is not origin/master." "git switch master && git pull --ff-only"
  fi
else
  soft_fail "git fetch origin master failed: $(cat "$ERR_FILE")" "Check your network and your access to $REPO_OWNER/$REPO_NAME."
fi

PRE_MODE=$(manifest_field .changeset/pre.json mode 2>/dev/null || true)
PRE_ID=$(manifest_field .changeset/pre.json tag 2>/dev/null || true)
if [[ "$PRE_MODE" == pre && "$PRE_ID" == "$PRE_TAG" ]]; then
  ok "Changesets is in pre mode $PRE_TAG"
else
  fail "Changesets is not in pre mode $PRE_TAG (.changeset/pre.json: mode '${PRE_MODE:-none}', tag '${PRE_ID:-none}')." \
    "The first publish is the first alpha: see $GUIDE, \"Pre mode and the next dist-tag\"."
fi

UNVERSIONED=()
for pkg in "${PACKAGES[@]}"; do
  manifest="packages/$pkg/package.json"
  [[ -f "$manifest" ]] || fail "$manifest is missing." "The four packages must be in the workspace: $GUIDE."
  name=$(manifest_field "$manifest" name)
  version=$(manifest_field "$manifest" version)
  [[ "$name" == "$pkg" ]] || fail "$manifest names the package $name, not $pkg."
  [[ "$version" == "$VERSION" ]] || UNVERSIONED+=("$pkg is at $version")
done
if ((${#UNVERSIONED[@]})); then
  fail "The versions of the first alpha are not applied: every package must be at $VERSION." \
    "${UNVERSIONED[@]}" \
    "Merge the pull request that applies them (branch release/first-alpha-versions)," \
    "or apply them as $GUIDE, \"Applying the versions\", says; then pull master."
fi
ok "the four packages are at $VERSION"

say ""
say "What npm holds:"
for pkg in "${PACKAGES[@]}"; do
  next=$(npm_next "$pkg") || exit 1
  if [[ "$next" == "$VERSION" ]]; then
    ok "$pkg: $DIST_TAG is $VERSION, already published"
  elif [[ -n "$next" ]]; then
    fail "$pkg: npm's $DIST_TAG is $next, past the first publish." \
      "This wizard only does the first publish of $VERSION; the release workflow publishes the later ones."
  else
    note "  $pkg: not published yet"
    PENDING+=("$pkg")
  fi
done
pause "Press Enter to continue"

# ── 2. The npm token ──────────────────────────────────────────────────────
stage "Log npm in with a granular token"

if ((${#PENDING[@]} == 0)); then
  ok "Nothing left to publish: no token is needed."
  pause "Press Enter to continue"
elif $DRY_RUN; then
  say "The real run asks for your npm username, opens its Access Tokens page and"
  say "reads a new granular token without echoing it, then runs:"
  printf '  %s$ npm config set %s=<the token>%s\n' "$BOLD" "$AUTH_KEY" "$RESET"
  run npm whoami
  confirm "Does the token have 'Bypass two-factor authentication' unticked?"
  pause "Press Enter to continue"
else
  if current=$(npm whoami 2>/dev/null); then
    fail "npm is already logged in, as $current." \
      "Log out first (npm logout), so this run uses a granular token of its own" \
      "that it removes from your npm config at the end."
  fi
  say "npm configures trusted publishing only on a package that exists, so this"
  say "first publish uses a granular access token, which you revoke at the end."
  ask NPM_USER "Your npm username:"
  [[ -n "$NPM_USER" ]] || fail "No npm username given."
  open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
  step "Generate New Token → Granular Access Token."
  step "Token name: reforged-ts first publish. Expiration: short; a few days is enough."
  step "Leave 'Bypass two-factor authentication' UNticked: 2FA must protect the token."
  step "Packages and scopes: Read and write, All Packages (the four do not exist yet)."
  step "Organizations: No access. Generate Token, then copy it."
  ask_secret NPM_TOKEN "Paste the token (hidden):"
  [[ -n "$NPM_TOKEN" ]] || fail "No token given."
  printf '  %s$ npm config set %s=<the token>%s\n' "$BOLD" "$AUTH_KEY" "$RESET"
  TOKEN_SET=true
  npm config set "$AUTH_KEY=$NPM_TOKEN" >/dev/null
  NPM_TOKEN=""
  printf '  %s$ npm whoami%s\n' "$BOLD" "$RESET"
  who=$(npm whoami 2>"$ERR_FILE") ||
    fail "npm rejects the token: $(cat "$ERR_FILE")" "Generate a new token as above; this one is removed from your npm config."
  ok "npm answers as $who"
  if [[ "$who" != "$NPM_USER" ]]; then
    warn "You named $NPM_USER, but the token is $who's."
    NPM_USER="$who"
  fi
  confirm "Does the token have 'Bypass two-factor authentication' unticked?" ||
    fail "The token must be protected by 2FA." "Delete it on the Access Tokens page and generate one without the bypass."
fi

# ── 3. Publish ────────────────────────────────────────────────────────────
stage "Build, pack and publish"

if ((${#PENDING[@]} == 0)); then
  ok "The four packages are on npm with $DIST_TAG at $VERSION: nothing to publish."
  pause "Press Enter to continue"
else
  say "To publish: ${PENDING[*]}"
  say "The same steps as the release workflow's pack and publish jobs ($GUIDE)."
  say ""
  run pnpm install --frozen-lockfile || fail "pnpm install failed." "Read the error above."
  run pnpm build || fail "The build failed." "Fix it on master first."
  run pnpm typings:check || fail "The Typings differ from what their generator writes." "Fix it on master first."
  PACK_DIR=$(native_path "$(mktemp -d)")
  run pnpm changeset pack --out-dir "$PACK_DIR" || fail "changeset pack failed." "Read the error above."
  run pnpm release:dist-tag --pack-dir "$PACK_DIR" ||
    fail "release:dist-tag refused the publish plan." "Read the error above: $GUIDE, \"The dist-tag\"."

  PLANNED=()
  if ! $DRY_RUN; then
    while read -r name version tag; do
      [[ " ${PENDING[*]} " == *" $name "* ]] || fail "The publish plan holds $name, which is not one of the packages to publish."
      [[ "$version" == "$VERSION" && "$tag" == "$DIST_TAG" ]] ||
        fail "The publish plan has $name at $version under '$tag', not $VERSION under '$DIST_TAG'."
      PLANNED+=("$name")
    done < <(node -e '
      const plan = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
      for (const entry of plan.plan.flat())
        if (entry.kind === "publish") console.log(entry.name, entry.version, entry.tag);
    ' "$PACK_DIR/publish-plan.json")
    ok "the publish plan: ${PLANNED[*]:-nothing} at $VERSION under '$DIST_TAG'"
  fi

  if $DRY_RUN || ((${#PLANNED[@]})); then
    say ""
    warn "Publishing cannot be undone: npm never accepts the same version twice."
    confirm "Publish to npm now?" || fail "Nothing was published."
    note "npm may ask for a one-time password from your authenticator."
    run pnpm changeset publish --from-pack-dir "$PACK_DIR" ||
      fail "changeset publish failed." "Read the error above. A package it did publish is skipped on the re-run."
  fi

  say ""
  say "Checking npm (a new version can take a minute to show):"
  for pkg in "${PENDING[@]}"; do
    if $DRY_RUN; then
      run npm view "$pkg" "dist-tags.$DIST_TAG"
      continue
    fi
    next=""
    for attempt in 1 2 3 4 5 6 7 8 9 10 11 12; do
      next=$(npm_next "$pkg") || exit 1
      [[ "$next" == "$VERSION" || $attempt -eq 12 ]] && break
      sleep 10
    done
    if [[ "$next" == "$VERSION" ]]; then
      ok "$pkg: $DIST_TAG is $VERSION"
    elif npm_has_version "$pkg"; then
      warn "$pkg@$VERSION is on npm, but its $DIST_TAG dist-tag is '${next:-missing}'."
      confirm "Point $DIST_TAG at $pkg@$VERSION now?" ||
        fail "$pkg has no $DIST_TAG at $VERSION." "npm dist-tag add $pkg@$VERSION $DIST_TAG"
      run npm dist-tag add "$pkg@$VERSION" "$DIST_TAG" ||
        fail "npm dist-tag add failed." "Read the error above."
      ok "$pkg: $DIST_TAG is $VERSION"
    else
      fail "$pkg@$VERSION is not on npm." "Read the publish output above."
    fi
  done

  # changeset publish tags each published package locally, as the release
  # workflow does; the workflow also pushes them.
  TAGS=()
  for pkg in "${PENDING[@]}"; do
    if $DRY_RUN || [[ -n "$(git tag --list "$pkg@$VERSION")" ]]; then TAGS+=("$pkg@$VERSION"); fi
  done
  if ((${#TAGS[@]})); then
    say ""
    if confirm "Push the tags ${TAGS[*]} to origin?"; then
      run git push origin "${TAGS[@]/#/refs/tags/}" || fail "git push failed." "Push them later: git push origin ${TAGS[*]}"
    else
      note "Not pushed. Later: git push origin ${TAGS[*]}"
    fi
  fi
  pause "Press Enter to continue"
fi

# ── 4 to 7. Each package: trusted publisher, then no tokens ───────────────
for pkg in "${PACKAGES[@]}"; do
  stage "$pkg: trusted publisher and publishing access"
  open_url "https://www.npmjs.com/package/$pkg/access"
  say "${BOLD}Trusted publishing${RESET}: Select your publisher → GitHub Actions, then enter:"
  say "  Organization or user  ${BOLD}$REPO_OWNER${RESET}"
  say "  Repository            ${BOLD}$REPO_NAME${RESET}"
  say "  Workflow filename     ${BOLD}$WORKFLOW${RESET}"
  say "  Environment name      (leave empty)"
  say "  Allowed actions       allow ${BOLD}npm publish${RESET} (the workflow publishes directly)"
  step "Save the trusted publisher."
  confirm "Is the trusted publisher of $pkg saved with exactly these values?" ||
    fail "$pkg has no trusted publisher." "Add it on https://www.npmjs.com/package/$pkg/access"
  say ""
  say "${BOLD}Publishing access${RESET}, on the same page:"
  step "Select 'Require two-factor authentication and disallow tokens'."
  step "Click 'Update Package Settings' (npm asks for your 2FA code)."
  confirm "Is $pkg set to 'Require two-factor authentication and disallow tokens'?" ||
    fail "$pkg still accepts tokens." "Set it on https://www.npmjs.com/package/$pkg/access"
done

# ── 8. Revoke the token ───────────────────────────────────────────────────
stage "Revoke the token"

if $DRY_RUN; then
  open_url "https://www.npmjs.com/settings/<your npm username>/tokens"
  step "Delete the 'reforged-ts first publish' token (the × on its row)."
  say "The real run then checks that npm refuses it:"
  run npm whoami
  run npm config delete "$AUTH_KEY"
elif $TOKEN_SET; then
  open_url "https://www.npmjs.com/settings/$NPM_USER/tokens"
  step "Delete the 'reforged-ts first publish' token (the × on its row), and confirm."
  pause "Press Enter once it is deleted"
  while npm whoami >/dev/null 2>"$ERR_FILE"; do
    warn "npm still accepts the token."
    pause "Delete it on the Access Tokens page, then press Enter"
  done
  if grep -qE 'E401|401 Unauthorized' "$ERR_FILE"; then
    ok "npm refuses the token: it is revoked"
  else
    warn "npm whoami failed, but not with a 401: $(head -n 1 "$ERR_FILE")"
    confirm "Is the token deleted on the Access Tokens page?" ||
      fail "The token is not revoked." "Delete it on https://www.npmjs.com/settings/$NPM_USER/tokens"
  fi
  printf '  %s$ npm config delete %s%s\n' "$BOLD" "$AUTH_KEY" "$RESET"
  npm config delete "$AUTH_KEY" >/dev/null
  TOKEN_SET=false
  ok "removed the token from your npm config"
else
  say "This run used no token; revoke the one an earlier run used."
  ask NPM_USER "Your npm username:"
  open_url "https://www.npmjs.com/settings/${NPM_USER:-<your npm username>}/tokens"
  step "Delete the 'reforged-ts first publish' token (the × on its row), and confirm."
  confirm "Is the token of the first publish deleted?" ||
    fail "The token is not revoked." "Delete it on the Access Tokens page."
fi

finish
if $DRY_RUN; then
  note "Dry run: nothing was published, set or pushed."
else
  ok "The four packages are on npm with $DIST_TAG at $VERSION, publish through $WORKFLOW only, and no token remains."
fi
say ""
say "Next, human step 5 of $GUIDE: with the workflow's prerequisites in place, run"
say "the release workflow's dry run, then merge the next Version Packages pull request:"
say "  ${BOLD}gh workflow run $WORKFLOW --ref master -f dry-run=true${RESET}"
say ""
