#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# The repository-setup wizard (#198): the one-off human steps of #48 and
# of the Claim board (#529). It registers the repository's GitHub App and
# installs it on this repository, stores its client ID and a private key as
# the variable APP_CLIENT_ID and the secret APP_PRIVATE_KEY, installs the
# Renovate GitHub App, applies the repository settings with
# `pnpm repo:settings`, and sets up the Claim board: the environment
# `board`, whose deployment branch policy admits master alone, a classic
# token of the maintainer as its secret PROJECT_TOKEN, the Template's
# environment `board` (ADR 0017), whose policy admits main alone and whose
# one secret is the App's key APP_PRIVATE_KEY, read by the Template's board
# dispatch, `pnpm board:setup`, the views' hand settings and the first
# `pnpm board:reconcile`.
#
# From the repository root, in Git Bash (Windows) or a Linux shell:
#
#   bash release/repo-setup.sh            the real run
#   bash release/repo-setup.sh --dry-run  prints every command, changes nothing
#
# It checks what gh can check and stops at the first failed check, saying
# what to fix. The App's owner, permissions and installation it checks as
# the App itself (`pnpm github-app check`, a JWT signed with the key); the
# board's token as its holder (the login, the scopes, the expiration); which
# repositories an installation reaches, and Renovate's installation scope,
# it asks the maintainer to confirm. It never prints the private key or the
# token: the key file goes to `gh secret set` on its standard input, the
# token is typed hidden and piped the same way. It is safe to re-run: the
# App stages are skipped when the variable and the secret exist, Renovate's
# installation when its Dependency Dashboard issue exists, the settings
# when they read back as committed, the board when its environment, its
# policy and its secret exist in both repositories and
# `pnpm board:setup --dry-run` plans nothing. An environment that exists
# is left as it is: only a missing branch policy is added to it.
#
# The dry run still runs `pnpm install` and the read-only checks (gh, git,
# what the repository holds, `pnpm repo:settings --dry-run`,
# `pnpm board:setup --dry-run`). It only warns about the branch, the working
# tree and what master lacks, so the wizard can be reviewed from any branch;
# it answers every confirmation with yes, opens no browser, and prints the
# commands that change something instead of running them.

readonly REPO_OWNER=phmilk
readonly REPO_NAME=reforged-ts
readonly REPO="$REPO_OWNER/$REPO_NAME"
# The release dispatches to it with the App (docs/release.md, "The Template
# dispatch").
readonly TEMPLATE_NAME=reforged-ts-template
readonly CLIENT_ID_VARIABLE=APP_CLIENT_ID
readonly PRIVATE_KEY_SECRET=APP_PRIVATE_KEY
# The board's token: a classic personal access token of the maintainer with
# the project scope, read by board.yml (docs/release.md, "The board") as a
# secret of the environment BOARD_ENVIRONMENT, whose deployment branch
# policy admits BOARD_BRANCH alone: a run on any other ref is refused it.
readonly PROJECT_TOKEN_SECRET=PROJECT_TOKEN
readonly BOARD_ENVIRONMENT=board
readonly BOARD_BRANCH=master
readonly BOARD_POLICY='{"deployment_branch_policy":{"protected_branches":false,"custom_branch_policies":true}}'
readonly TOKEN_PAGE="https://github.com/settings/tokens/new?scopes=project&description=reforged-ts+board"
# The Template's environment of the same name (ADR 0017): its board
# dispatch reads the App's key as the secret PRIVATE_KEY_SECRET of it,
# whose deployment branch policy admits TEMPLATE_BRANCH alone. The App's
# client ID stays the Template's repository variable.
readonly TEMPLATE="$REPO_OWNER/$TEMPLATE_NAME"
readonly TEMPLATE_BRANCH=main
readonly RULESET_FILE=.github/rulesets/master.json
readonly RENOVATE_CONFIG=renovate.json5
readonly GUIDE=docs/release.md
readonly RERUN="bash release/repo-setup.sh"

usage() {
  printf 'Usage: %s [--dry-run]\n' "$RERUN"
  printf '  The one-off setup of %s: its GitHub App, Renovate, settings (#48) and Claim board (#529).\n' "$REPO"
}

DRY_RUN=false
if [[ $# -gt 1 ]]; then usage >&2; exit 2; fi
case "${1:-}" in
  "") ;;
  --dry-run) DRY_RUN=true ;;
  -h | --help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac

# Git Bash rewrites arguments that look like POSIX paths. Paths handed to
# native programs go through cygpath instead (see native_path).
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'

# pnpm's Windows launcher (a corepack or nvm shell script) hands node a POSIX
# path to its own pnpm.js, which only Git Bash's conversion makes readable to
# node: run pnpm with the conversion back on. Its arguments are native paths
# already.
pnpm() { env -u MSYS_NO_PATHCONV -u MSYS2_ARG_CONV_EXCL pnpm "$@"; }

# Nothing this wizard captures is persisted locally: no value is read from
# or written to a .env file. The GitHub variable and secret are the store.
ENV_FILE=/dev/null

ERR_FILE=$(mktemp)
trap 'rm -f "$ERR_FILE"' EXIT
trap 'exit 130' INT TERM

# In the dry run, nothing waits for the human and no browser opens: the
# library's gates print what they would ask instead.
if $DRY_RUN; then
  _clear() { :; }
  pause() { printf '  %s%s%s %s(dry run: continues)%s\n' "$DIM" "${1:-Press Enter to continue}" "$RESET" "$YELLOW" "$RESET"; }
  confirm() { printf '  %s? %s%s %s(dry run: answered yes)%s\n' "$YELLOW" "$1" "$RESET" "$YELLOW" "$RESET"; }
  open_url() { printf '  %s↗ would open%s %s\n' "$GREEN" "$RESET" "$1"; }
fi

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# fail "what failed" ["what to fix"...] stops the wizard.
fail() {
  printf '\n  %s%s✗ %s%s\n' "$BOLD" "$RED" "$1" "$RESET" >&2
  shift
  local line
  for line in "$@"; do printf '    %s\n' "$line" >&2; done
  printf '\n  %sThen re-run: %s%s%s\n\n' "$DIM" "$RERUN" "$($DRY_RUN && printf ' --dry-run')" "$RESET" >&2
  exit 1
}

# soft_fail stops the wizard, except in the dry run, where it only warns:
# the checks of the checkout and of master, so the dry run can be reviewed
# from any branch before the pull request adding this wizard merges.
soft_fail() {
  if $DRY_RUN; then
    warn "$1 (a real run stops here)"
    shift
    local line
    for line in "$@"; do note "  $line"; done
    return 0
  fi
  fail "$@"
}

# What gh, git and node print when the connection to GitHub drops (a
# timeout, a reset, a failed lookup), as opposed to an answer from GitHub.
NETWORK_ERROR='dial tcp|connectex|i/o timeout|TLS handshake timeout|connection reset|unexpected EOF|ECONNRESET|ETIMEDOUT|EAI_AGAIN|ENOTFOUND|fetch failed'
ATTEMPTS=3

# network_dropped: whether the last error in ERR_FILE is a dropped connection.
network_dropped() {
  grep -Eq "$NETWORK_ERROR" "$ERR_FILE" 2>/dev/null
}

# retried CMD... runs CMD and, when it fails because the connection to GitHub
# dropped, runs it again after a pause, up to ATTEMPTS times. Every command
# this wizard runs gives the same result when run twice. Its error output is
# shown after it ends.
retried() {
  local attempt status
  for ((attempt = 1; ; attempt++)); do
    status=0
    "$@" 2>"$ERR_FILE" || status=$?
    cat "$ERR_FILE" >&2
    if ((status == 0)) || ((attempt >= ATTEMPTS)) || ! network_dropped; then
      return "$status"
    fi
    note "The connection to GitHub dropped; trying again in $((attempt * 5)) s ($((attempt + 1)) of $ATTEMPTS)."
    sleep $((attempt * 5))
  done
}

# run CMD... prints the command, then runs it; in the dry run it only prints.
run() {
  printf '  %s$ %s%s\n' "$BOLD" "$*" "$RESET"
  $DRY_RUN || retried "$@"
}

# show CMD... prints the command, then runs it, in the dry run too: for the
# read-only commands whose output the maintainer reads.
show() {
  printf '  %s$ %s%s\n' "$BOLD" "$*" "$RESET"
  retried "$@"
}

# native_path PATH: PATH as native programs (node, pnpm) read it.
native_path() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}

# shell_path PATH: a path as typed or pasted (quoted, ~/..., C:\...), as
# this shell reads it.
shell_path() {
  local path="$1"
  path="${path#[\"\']}"
  path="${path%[\"\']}"
  if [[ "$path" == \~/* ]]; then path="$HOME/${path:2}"; fi
  if command -v cygpath >/dev/null 2>&1; then path=$(cygpath -u "$path"); fi
  printf '%s' "$path"
}

# gh_read ARGS...: gh's output for a read-only query; empty when it fails
# (a 404 included; gh api prints the error body on stdout), its message
# kept in ERR_FILE. A dropped connection is retried like `retried` does,
# so it never reads as "not there".
gh_read() {
  local out attempt
  for ((attempt = 1; attempt <= ATTEMPTS; attempt++)); do
    if out=$(gh "$@" 2>"$ERR_FILE"); then
      printf '%s\n' "$out"
      return 0
    fi
    network_dropped || return 0
    ((attempt < ATTEMPTS)) && sleep $((attempt * 5))
  done
  return 0
}

# secret_stored NAME [ENVIRONMENT [REPOSITORY]]: whether REPOSITORY (this
# one by default), or its environment when one is named, holds the Actions
# secret NAME.
secret_stored() {
  local name="$1" environment="${2:-}" repository="${3:-$REPO}" scope=()
  [[ -n "$environment" ]] && scope=(--env "$environment")
  [[ -n "$(gh_read secret list --repo "$repository" "${scope[@]}" --json name --jq ".[] | select(.name == \"$name\") | .name")" ]]
}

# app_stored: whether the repository holds the App's variable and secret.
app_stored() {
  [[ -n "$(gh_read variable get "$CLIENT_ID_VARIABLE" --repo "$REPO")" ]] &&
    secret_stored "$PRIVATE_KEY_SECRET"
}

# renovate_dashboard: the number of Renovate's open Dependency Dashboard
# issue, the sign that it is installed and read the configuration.
renovate_dashboard() {
  gh_read issue list --repo "$REPO" --author app/renovate --state open \
    --search 'Dependency Dashboard in:title' --json number --jq '.[0].number // empty'
}

# renovate_onboarding: the number of Renovate's open onboarding pull request.
renovate_onboarding() {
  gh_read pr list --repo "$REPO" --author app/renovate --state open \
    --head renovate/configure --json number --jq '.[0].number // empty'
}

# settings_problems prints one line per repository setting that does not
# read back as committed; nothing when all do.
settings_problems() {
  local expected id actual merge pages
  expected=$(node -e '
    const ruleset = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
    const checks = ruleset.rules.filter((rule) => rule.type === "required_status_checks")
      .flatMap((rule) => rule.parameters.required_status_checks.map((check) => check.context));
    process.stdout.write("active;refs/heads/master;" + checks.sort().join(","));
  ' "$RULESET_FILE")
  id=$(gh_read api "repos/$REPO/rulesets?includes_parents=false" --jq '.[] | select(.name == "master") | .id')
  if [[ -z "$id" ]]; then
    printf 'No ruleset named master.\n'
  else
    actual=$(gh_read api "repos/$REPO/rulesets/$id" --jq '[.enforcement, (.conditions.ref_name.include | join(",")), ([.rules[] | select(.type == "required_status_checks") | .parameters.required_status_checks[].context] | sort | join(","))] | join(";")')
    [[ "$actual" == "$expected" ]] ||
      printf 'The ruleset master reads "%s" (enforcement;branches;required checks), not "%s".\n' "$actual" "$expected"
  fi
  merge=$(gh_read api "repos/$REPO" --jq '"\(.allow_squash_merge) \(.allow_merge_commit) \(.allow_rebase_merge) \(.allow_auto_merge) \(.delete_branch_on_merge)"')
  [[ "$merge" == "true false false true true" ]] ||
    printf 'Merge settings (squash, merge commits, rebase, auto-merge, delete head branches) read "%s", not "true false false true true".\n' "$merge"
  pages=$(gh_read api "repos/$REPO/pages" --jq .build_type)
  [[ "$pages" == workflow ]] || printf 'The Pages source is "%s", not GitHub Actions (workflow).\n' "${pages:-off}"
  [[ -n "$(gh_read api "repos/$REPO/labels/game-patch" --jq .name)" ]] || printf 'No game-patch label.\n'
}

# board_secret_stored: whether the board's environment holds its token.
board_secret_stored() {
  secret_stored "$PROJECT_TOKEN_SECRET" "$BOARD_ENVIRONMENT"
}

# board_policy_branches [REPOSITORY] prints the branches the board
# environment's deployment branch policy admits in REPOSITORY (this one by
# default), one per line; nothing when the environment does not exist or
# admits every branch.
board_policy_branches() {
  local repository="${1:-$REPO}"
  [[ "$(gh_read api "repos/$repository/environments/$BOARD_ENVIRONMENT" --jq '.deployment_branch_policy.custom_branch_policies')" == true ]] || return 0
  gh_read api "repos/$repository/environments/$BOARD_ENVIRONMENT/deployment-branch-policies" --jq '.branch_policies[] | select(.type == "branch") | .name'
}

# board_environment_ok: whether the board environment exists and its
# deployment branch policy admits BOARD_BRANCH alone.
board_environment_ok() {
  [[ "$(board_policy_branches)" == "$BOARD_BRANCH" ]]
}

# template_environment_exists: whether the Template has the board
# environment, whatever its policy.
template_environment_exists() {
  [[ -n "$(gh_read api "repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT" --jq .name)" ]]
}

# template_environment_ok: whether the Template's board environment exists
# and its deployment branch policy admits TEMPLATE_BRANCH alone.
template_environment_ok() {
  [[ "$(board_policy_branches "$TEMPLATE")" == "$TEMPLATE_BRANCH" ]]
}

# template_key_stored: whether the Template's board environment holds the
# App's key.
template_key_stored() {
  secret_stored "$PRIVATE_KEY_SECRET" "$BOARD_ENVIRONMENT" "$TEMPLATE"
}

# ask_key_file asks for the path of the App's downloaded .pem file and sets
# KEY_FILE to it, as native programs read it; in the dry run it only says so.
ask_key_file() {
  if $DRY_RUN; then
    note "  (dry run: asks for the path of the .pem file)"
    KEY_FILE="<key file>"
    return 0
  fi
  ask KEY_PATH "Path of the downloaded .pem file (its path, not its content):"
  KEY_FILE=$(shell_path "$KEY_PATH")
  [[ -f "$KEY_FILE" && -r "$KEY_FILE" ]] ||
    fail "$KEY_FILE is not a readable file." "Give the path of the downloaded .pem file, such as ~/Downloads/$REPO_NAME-bot.<date>.private-key.pem"
  grep -q -- '-----BEGIN RSA PRIVATE KEY-----' "$KEY_FILE" ||
    fail "$KEY_FILE is not a private key the App's page generated." "Give the path of the downloaded .pem file."
  KEY_FILE=$(native_path "$KEY_FILE")
}

# board_plan prints what `pnpm board:setup --dry-run` plans, the board's
# read-back: "Dry run, 0 requests" is the board as committed (the project
# exists, is public, is linked to both repositories, its Status options and
# its views as release/src/board.ts holds them). Its notes are shown after
# it ends and kept in ERR_FILE; a dropped connection is retried, as `show`
# does.
board_plan() {
  retried pnpm --silent board:setup --dry-run
}

# board_url prints the project's URL from a board_plan, empty when the
# project does not exist yet.
board_url() {
  sed -n 's/^Project "[^"]*" under [^:]*: \([^ ]*\) (number [0-9]*)\.$/\1/p' <<<"$1" | head -n 1
}

# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
APP_DONE=false # the variable and the secret exist and are kept
CLIENT_ID=""
KEY_FILE=""
INSTALL_PAGE=""

if $DRY_RUN; then
  banner "Setup of $REPO (dry run: nothing is changed)"
else
  banner "Setup of $REPO"
fi

# ── 1. Before anything ────────────────────────────────────────────────────
stage "Check gh, your rights and the checkout"

for tool in git gh node pnpm; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is not on the PATH." "Install it; the root README lists the Toolchain, gh is https://cli.github.com."
done
ok "git, gh, node and pnpm are on the PATH"

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) ||
  fail "This is not a git checkout." "Run the wizard from a clone of $REPO."
cd "$ROOT"
[[ -f "$RULESET_FILE" && -f release/src/cli/github-app.ts ]] ||
  fail "$ROOT is not the $REPO_NAME repository." "Run the wizard from a clone of $REPO."

gh auth status >/dev/null 2>"$ERR_FILE" ||
  fail "gh is not logged in: $(head -n 1 "$ERR_FILE")" "gh auth login"
ADMIN=$(gh_read api "repos/$REPO" --jq .permissions.admin)
if [[ "$ADMIN" == true ]]; then
  ok "gh is logged in as $(gh_read api user --jq .login), an administrator of $REPO"
else
  fail "gh's login is not an administrator of $REPO${ADMIN:+ (admin: $ADMIN)}. $(head -n 1 "$ERR_FILE")" \
    "Log in as the maintainer: gh auth login"
fi
# The board stage makes the Template's environment board.
ADMIN=$(gh_read api "repos/$TEMPLATE" --jq .permissions.admin)
if [[ "$ADMIN" == true ]]; then
  ok "it is an administrator of $TEMPLATE too"
else
  fail "gh's login is not an administrator of $TEMPLATE${ADMIN:+ (admin: $ADMIN)}. $(head -n 1 "$ERR_FILE")" \
    "Log in as the maintainer: gh auth login"
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" == master ]]; then
  ok "on master"
else
  soft_fail "The checkout is on $BRANCH, not master." "git switch master && git pull --ff-only"
fi

if [[ -z "$(git status --porcelain)" ]]; then
  ok "the working tree is clean"
else
  soft_fail "The working tree has changes:" "$(git status --short)" "Commit, stash or discard them: the settings applied are master's."
fi

if git fetch --quiet origin master 2>"$ERR_FILE"; then
  if [[ "$(git rev-parse HEAD)" == "$(git rev-parse origin/master)" ]]; then
    ok "HEAD is origin/master"
  else
    soft_fail "HEAD is not origin/master." "git switch master && git pull --ff-only"
  fi
else
  fail "git fetch origin master failed: $(cat "$ERR_FILE")" "Check your network and your access to $REPO."
fi

# In the dry run too: it only fills node_modules, and the dry run's
# `pnpm github-app url` and `pnpm repo:settings --dry-run` compile first.
show pnpm install --frozen-lockfile || fail "pnpm install failed." "Read the error above."
pause "Press Enter to continue"

# ── 2 to 5. The GitHub App ────────────────────────────────────────────────
stage "Register the GitHub App"

if app_stored; then
  ok "$REPO holds the variable $CLIENT_ID_VARIABLE and the secret $PRIVATE_KEY_SECRET: the App was set up on an earlier run."
  if confirm "Set the App up again (another App, or a new private key)?"; then
    note "For a new key of the same App, do not register another: answer yes below."
  else
    APP_DONE=true
  fi
fi

if $APP_DONE; then
  pause "Press Enter to continue"
else
  say "The workflows open their pull requests and the Patch-watch issue as this"
  say "App, with short-lived tokens (release.yml, patch-watch.yml, docs.yml)."
  say "The page opens pre-filled; check each value before creating the App:"
  URL=$(pnpm --silent github-app url --repo "$REPO") || fail "pnpm github-app url failed." "Read the error above."
  open_url "$URL"
  say "  GitHub App name         ${BOLD}$REPO_NAME-bot${RESET} (any free name: the workflows use the client ID)"
  say "  Homepage URL            ${BOLD}https://github.com/$REPO${RESET}"
  say "  Webhook                 ${BOLD}Active unticked${RESET}"
  say "  Repository permissions  ${BOLD}Contents, Issues, Pull requests: Read and write${RESET};"
  say "                          Metadata: Read-only (GitHub adds it); every other: No access"
  say "  Organization, Account   ${BOLD}No access${RESET} for every permission"
  say "  Where can this GitHub App be installed?  ${BOLD}Only on this account${RESET}"
  step "Create GitHub App. If an earlier run created it, do not create another:"
  step "open it from https://github.com/settings/apps instead."
  confirm "Is the App created, owned by $REPO_OWNER?" ||
    fail "No App yet." "Create it on the page above."
fi

stage "The App's client ID and a private key"

if $APP_DONE; then
  ok "Kept from an earlier run."
  pause "Press Enter to continue"
else
  say "On the App's settings page (General):"
  step "Copy the ${BOLD}Client ID${RESET} (it starts with Iv), not the App ID (a number)."
  if $DRY_RUN; then
    note "  (dry run: asks for the client ID)"
    CLIENT_ID="<client ID>"
  else
    ask CLIENT_ID "Paste the client ID:"
    CLIENT_ID="${CLIENT_ID//[[:space:]]/}"
    if [[ "$CLIENT_ID" =~ ^[0-9]+$ ]]; then
      fail "$CLIENT_ID is the App ID." "Copy the Client ID, next to it on the App's settings page."
    fi
    [[ "$CLIENT_ID" =~ ^Iv[A-Za-z0-9._-]+$ ]] ||
      fail "'$CLIENT_ID' is not a client ID (it starts with Iv)." "Copy the Client ID from the App's settings page."
  fi
  step "Under Private keys, ${BOLD}Generate a private key${RESET}: the browser downloads a .pem file."
  ask_key_file
  say ""
  say "Checking the App as the App itself (a token signed with the key):"
  if $DRY_RUN; then
    run pnpm --silent github-app check --repo "$REPO" --client-id "$CLIENT_ID" --private-key "$KEY_FILE"
    INSTALL_PAGE="https://github.com/apps/<the App's slug>/installations/new"
  else
    printf '  %s$ pnpm --silent github-app check --repo %s --client-id %s --private-key %s%s\n' "$BOLD" "$REPO" "$CLIENT_ID" "$KEY_FILE" "$RESET"
    REPORT=$(pnpm --silent github-app check --repo "$REPO" --client-id "$CLIENT_ID" --private-key "$KEY_FILE") ||
      fail "The App is not as the workflows need it (above)." "Fix it on the App's settings page: https://github.com/settings/apps"
    while IFS= read -r line; do note "  $line"; done <<<"$REPORT"
    INSTALL_PAGE=$(sed -n 's/^Installation page: //p' <<<"$REPORT")
    ok "the client ID and the key are the App's, with the permissions the workflows need and no webhook"
  fi
  pause "Press Enter to continue"
fi

stage "Install the App on $REPO"

if $APP_DONE; then
  ok "Kept from an earlier run."
  pause "Press Enter to continue"
else
  open_url "$INSTALL_PAGE"
  step "Install it on ${BOLD}$REPO_OWNER${RESET}."
  step "Repository access: ${BOLD}Only select repositories${RESET} → ${BOLD}$REPO_NAME${RESET} and ${BOLD}$TEMPLATE_NAME${RESET}, and nothing else."
  step "Install."
  pause "Press Enter once it is installed"
  # This repository, then the Template, which the release dispatches to.
  for INSTALLED_REPO in "$REPO" "$TEMPLATE"; do
    if $DRY_RUN; then
      run pnpm --silent github-app check --repo "$INSTALLED_REPO" --client-id "$CLIENT_ID" --private-key "$KEY_FILE" --installed
    else
      printf '  %s$ pnpm --silent github-app check --repo %s ... --installed%s\n' "$BOLD" "$INSTALLED_REPO" "$RESET"
      REPORT=$(pnpm --silent github-app check --repo "$INSTALLED_REPO" --client-id "$CLIENT_ID" --private-key "$KEY_FILE" --installed) ||
        fail "The installation on $INSTALLED_REPO is not as the workflows need it (above)." "Fix it, then re-run. The account's installations: https://github.com/settings/installations"
      while IFS= read -r line; do note "  $line"; done <<<"$REPORT"
      ok "installed on $INSTALLED_REPO, on selected repositories, with the permissions accepted"
    fi
  done
  note "Which repositories an installation reaches, only its settings page shows."
  confirm "Does its Repository access list $REPO_NAME and $TEMPLATE_NAME only?" ||
    fail "The App reaches other repositories." "Remove them under Repository access: https://github.com/settings/installations"
fi

stage "Store the client ID and the private key"

if $APP_DONE; then
  ok "Kept from an earlier run: $CLIENT_ID_VARIABLE and $PRIVATE_KEY_SECRET."
  pause "Press Enter to continue"
else
  run gh variable set "$CLIENT_ID_VARIABLE" --repo "$REPO" --body "$CLIENT_ID" ||
    fail "gh variable set failed." "Read the error above."
  # The key goes to gh on its standard input: never on a command line,
  # never printed.
  printf '  %s$ gh secret set %s --repo %s < %s%s\n' "$BOLD" "$PRIVATE_KEY_SECRET" "$REPO" "$KEY_FILE" "$RESET"
  if ! $DRY_RUN; then
    gh secret set "$PRIVATE_KEY_SECRET" --repo "$REPO" <"$(shell_path "$KEY_FILE")" ||
      fail "gh secret set failed." "Read the error above."
    WRITTEN_SECRET+=("$PRIVATE_KEY_SECRET")
  fi
  say ""
  say "Checking:"
  if $DRY_RUN; then
    run gh variable get "$CLIENT_ID_VARIABLE" --repo "$REPO"
    run gh secret list --repo "$REPO"
  else
    [[ "$(gh_read variable get "$CLIENT_ID_VARIABLE" --repo "$REPO")" == "$CLIENT_ID" ]] ||
      fail "The variable $CLIENT_ID_VARIABLE does not read back as $CLIENT_ID." "gh variable set $CLIENT_ID_VARIABLE --repo $REPO --body <client ID>"
    ok "the variable $CLIENT_ID_VARIABLE is $CLIENT_ID"
    app_stored || fail "The secret $PRIVATE_KEY_SECRET is not listed." "gh secret set $PRIVATE_KEY_SECRET --repo $REPO < <key file>"
    ok "the secret $PRIVATE_KEY_SECRET is set"
  fi
  note "Keep the .pem file until the board stage has stored it in $TEMPLATE_NAME's"
  note "environment $BOARD_ENVIRONMENT; it says when it is no longer needed."
  pause "Press Enter to continue"
fi

# ── 6. Renovate ───────────────────────────────────────────────────────────
stage "Install Renovate"

if git cat-file -e "origin/master:$RENOVATE_CONFIG" 2>/dev/null; then
  ok "$RENOVATE_CONFIG is on master"
else
  soft_fail "$RENOVATE_CONFIG is not on master." \
    "Merge the pull request adding it first: installed before it, Renovate opens an" \
    "onboarding pull request instead of reading the configuration."
fi

DASHBOARD=$(renovate_dashboard)
if $DRY_RUN; then
  show gh issue list --repo "$REPO" --author app/renovate --state open --search 'Dependency Dashboard in:title'
fi
if [[ -n "$DASHBOARD" ]]; then
  ok "Renovate is installed: its Dependency Dashboard is issue #$DASHBOARD"
else
  say "Renovate opens the weekly dependency pull requests of $RENOVATE_CONFIG."
  open_url "https://github.com/apps/renovate/installations/new"
  step "Install it on ${BOLD}$REPO_OWNER${RESET} (Configure, when it is already on the account)."
  step "Repository access: ${BOLD}Only select repositories${RESET}, with ${BOLD}$REPO_NAME${RESET} among them."
  step "Install (or Save)."
  note "It finds $RENOVATE_CONFIG on master, so it opens no onboarding pull request;"
  note "within minutes it opens a Dependency Dashboard issue, then its first pull"
  note "requests in the Monday 00:00-04:00 UTC window."
  pause "Press Enter once it is installed"
  say ""
  if $DRY_RUN; then
    note "A real run then waits up to 10 minutes for the Dependency Dashboard issue."
  else
    say "Waiting for its Dependency Dashboard issue (up to 10 minutes):"
    for attempt in $(seq 1 20); do
      DASHBOARD=$(renovate_dashboard)
      [[ -n "$DASHBOARD" || -n "$(renovate_onboarding)" || $attempt -eq 20 ]] && break
      sleep 30
    done
    if [[ -n "$DASHBOARD" ]]; then
      ok "Renovate is installed: its Dependency Dashboard is issue #$DASHBOARD"
    else
      warn "No Dependency Dashboard yet: Renovate's first run can take longer."
      confirm "Is Renovate listed at https://github.com/$REPO/settings/installations?" ||
        fail "Renovate is not installed." "Install it from https://github.com/apps/renovate/installations/new"
    fi
  fi
fi

ONBOARDING=$(renovate_onboarding)
if $DRY_RUN; then
  show gh pr list --repo "$REPO" --author app/renovate --state open --head renovate/configure
fi
if [[ -n "$ONBOARDING" ]]; then
  warn "Renovate opened the onboarding pull request #$ONBOARDING: close it, never merge it"
  warn "(the renovate.json it adds would take precedence over $RENOVATE_CONFIG)."
  confirm "Close #$ONBOARDING and delete its branch now?" ||
    fail "The onboarding pull request #$ONBOARDING is open." "Close it without merging: gh pr close $ONBOARDING --repo $REPO --delete-branch"
  run gh pr close "$ONBOARDING" --repo "$REPO" --delete-branch \
    --comment "Closed by the repository setup wizard: the configuration is $RENOVATE_CONFIG." ||
    fail "gh pr close failed." "Read the error above."
else
  ok "no onboarding pull request is open"
fi
confirm "Does Renovate's installation reach $REPO_NAME through Only select repositories (not All repositories)?" ||
  fail "Renovate reaches every repository of $REPO_OWNER." "Choose Only select repositories: https://github.com/settings/installations"
pause "Press Enter to continue"

# ── 7. Repository settings ────────────────────────────────────────────────
stage "Apply the repository settings"

say "The ruleset on master ($RULESET_FILE), squash merge only, auto-merge,"
say "head branches deleted, Pages from GitHub Actions and the labels."
PROBLEMS=$(settings_problems)
if [[ -z "$PROBLEMS" ]]; then
  ok "they already read back as committed"
else
  while IFS= read -r line; do note "  not yet: $line"; done <<<"$PROBLEMS"
  say ""
  show pnpm --silent repo:settings --dry-run ||
    fail "pnpm repo:settings --dry-run failed." "Read the error above."
  say ""
  confirm "Send these requests?" || fail "The settings are not applied." "Review them, then re-run."
  run pnpm --silent repo:settings ||
    fail "pnpm repo:settings failed; it stops at the first failed request (above)." "Fix the cause, then re-run: what was applied reads back and is not planned again."
  say ""
  if $DRY_RUN; then
    note "A real run then checks that the ruleset is active on master with the"
    note "required checks of $RULESET_FILE, and reads back the merge settings,"
    note "the Pages source and the game-patch label."
  else
    PROBLEMS=$(settings_problems)
    [[ -z "$PROBLEMS" ]] || fail "The settings do not read back as committed:" "$PROBLEMS"
    ok "the ruleset is active on master with the required checks; the merge settings, the Pages source and the labels read back as committed"
  fi
fi
pause "Press Enter to continue"

# ── 8. The Claim board ────────────────────────────────────────────────────
stage "The Claim board, its environments, its token and the Template's key"

say "The Claim board ($GUIDE, \"The board\"): a Projects board on $REPO_OWNER's account"
say "over $REPO_NAME and $TEMPLATE_NAME, whose Status board.yml writes with a classic"
say "token of yours, the secret $PROJECT_TOKEN_SECRET of the environment $BOARD_ENVIRONMENT: scope"
say "project only, expiring in a year. The environment's deployment branch policy"
say "admits $BOARD_BRANCH alone, so a run on any other ref is refused the secret."
say "$TEMPLATE_NAME has an environment $BOARD_ENVIRONMENT too (ADR 0017): its board dispatch"
say "tells board.yml to run on the Template's issue events, with a token of the App"
say "minted from the App's key, the secret $PRIVATE_KEY_SECRET of that environment, whose"
say "policy admits $TEMPLATE_BRANCH alone. It holds that key and nothing else."
say ""
ENVIRONMENT_OK=false
board_environment_ok && ENVIRONMENT_OK=true
if $ENVIRONMENT_OK; then
  ok "the environment $BOARD_ENVIRONMENT exists and admits $BOARD_BRANCH alone"
else
  note "not yet: no environment $BOARD_ENVIRONMENT whose policy admits $BOARD_BRANCH alone"
fi
SECRET_STORED=false
board_secret_stored && SECRET_STORED=true
if $SECRET_STORED; then
  ok "the secret $PROJECT_TOKEN_SECRET is set on the environment $BOARD_ENVIRONMENT"
else
  note "not yet: no secret $PROJECT_TOKEN_SECRET on the environment $BOARD_ENVIRONMENT"
fi
TEMPLATE_OK=false
template_environment_ok && TEMPLATE_OK=true
if $TEMPLATE_OK; then
  ok "$TEMPLATE_NAME's environment $BOARD_ENVIRONMENT exists and admits $TEMPLATE_BRANCH alone"
else
  note "not yet: no environment $BOARD_ENVIRONMENT in $TEMPLATE_NAME whose policy admits $TEMPLATE_BRANCH alone"
fi
TEMPLATE_KEY_STORED=false
template_key_stored && TEMPLATE_KEY_STORED=true
if $TEMPLATE_KEY_STORED; then
  ok "the secret $PRIVATE_KEY_SECRET is set on $TEMPLATE_NAME's environment $BOARD_ENVIRONMENT"
else
  note "not yet: no secret $PRIVATE_KEY_SECRET on $TEMPLATE_NAME's environment $BOARD_ENVIRONMENT"
fi
# The read-back of the project, in the dry run too: it reads GitHub with the
# gh login and sends nothing.
printf '  %s$ pnpm --silent board:setup --dry-run%s\n' "$BOLD" "$RESET"
BOARD_PLAN=$(board_plan) || fail "pnpm board:setup --dry-run failed: $(head -n 1 "$ERR_FILE")" "Read the error above."
while IFS= read -r line; do note "  $line"; done <<<"$BOARD_PLAN"
BOARD_PENDING=true
grep -q '^Dry run, 0 requests, none sent' <<<"$BOARD_PLAN" && BOARD_PENDING=false
if $BOARD_PENDING; then
  note "not yet: the board does not read back as committed (the requests above)"
else
  ok "the board reads back as committed: the project exists, is public, is linked to both repositories, its Status options and its views as release/src/board.ts holds them"
fi

ROTATE=false
if $ENVIRONMENT_OK && $SECRET_STORED && $TEMPLATE_OK && $TEMPLATE_KEY_STORED && ! $BOARD_PENDING; then
  confirm "Replace the token (a rotation: it expires a year after it was made)?" && ROTATE=true
fi

if ! $ENVIRONMENT_OK; then
  say ""
  say "The environment $BOARD_ENVIRONMENT, the secret's home, with a deployment branch policy"
  say "of its own ($BOARD_BRANCH alone, below); both calls are idempotent:"
  # The JSON goes to gh on its standard input, as the token does below.
  printf '  %s$ printf %s | gh api -X PUT repos/%s/environments/%s --input -%s\n' "$BOLD" "'$BOARD_POLICY'" "$REPO" "$BOARD_ENVIRONMENT" "$RESET"
  if ! $DRY_RUN; then
    printf '%s' "$BOARD_POLICY" | gh api --silent -X PUT "repos/$REPO/environments/$BOARD_ENVIRONMENT" --input - ||
      fail "gh api -X PUT repos/$REPO/environments/$BOARD_ENVIRONMENT failed." "Read the error above."
  fi
  if grep -qx "$BOARD_BRANCH" <<<"$(board_policy_branches)"; then
    ok "the policy admits $BOARD_BRANCH"
  else
    run gh api --silent -X POST "repos/$REPO/environments/$BOARD_ENVIRONMENT/deployment-branch-policies" -f "name=$BOARD_BRANCH" -f type=branch ||
      fail "gh api -X POST repos/$REPO/environments/$BOARD_ENVIRONMENT/deployment-branch-policies failed." "Read the error above."
  fi
  if $DRY_RUN; then
    run gh api "repos/$REPO/environments/$BOARD_ENVIRONMENT/deployment-branch-policies"
    note "A real run then checks that the environment admits $BOARD_BRANCH alone."
  else
    board_environment_ok ||
      fail "The environment $BOARD_ENVIRONMENT does not admit $BOARD_BRANCH alone: its policy admits '$(board_policy_branches | tr '\n' ' ')'." "Remove every other branch from it: https://github.com/$REPO/settings/environments"
    ok "the environment $BOARD_ENVIRONMENT exists and admits $BOARD_BRANCH alone"
  fi
fi

TOKEN=""
if ! $SECRET_STORED || $ROTATE; then
  say ""
  say "A classic personal access token of your account, for the board's workflow:"
  open_url "$TOKEN_PAGE"
  say "  Note        ${BOLD}reforged-ts board${RESET} (pre-filled)"
  say "  Expiration  ${BOLD}Custom, one year from today${RESET}; never No expiration"
  say "  Scopes      ${BOLD}project${RESET} only (pre-ticked); nothing under repo"
  step "Generate token, then copy it: the page shows it once."
  if $DRY_RUN; then
    note "  (dry run: asks for the token, hidden, and checks it as its holder:"
    note "   your login, the project scope, an expiration)"
    TOKEN="<the token>"
  else
    ask_secret TOKEN "Paste the token:"
    TOKEN="${TOKEN//[[:space:]]/}"
    [[ "$TOKEN" =~ ^ghp_[A-Za-z0-9]+$ ]] ||
      fail "That is not a classic token (one starts with ghp_)." "Create it on $TOKEN_PAGE"
    # As the token: whose it is, its scopes and its expiration, from the
    # headers GitHub answers with.
    LOGIN=$(GH_TOKEN="$TOKEN" gh api user --jq .login 2>"$ERR_FILE") ||
      fail "GitHub refuses the token: $(head -n 1 "$ERR_FILE")" "Create it again on $TOKEN_PAGE"
    [[ "$LOGIN" == "$REPO_OWNER" ]] ||
      fail "The token is $LOGIN's, not $REPO_OWNER's, and only the owner writes the board." "Create it logged in as $REPO_OWNER: $TOKEN_PAGE"
    HEADERS=$(GH_TOKEN="$TOKEN" gh api --include user 2>"$ERR_FILE" | tr -d '\r') ||
      fail "GitHub refuses the token: $(head -n 1 "$ERR_FILE")" "Create it again on $TOKEN_PAGE"
    SCOPES=$(grep -i '^x-oauth-scopes:' <<<"$HEADERS" | sed 's/^[^:]*: *//' || true)
    [[ ",${SCOPES// /}," == *,project,* ]] ||
      fail "The token's scopes are '${SCOPES:-none}', without project." "Create it with the project scope: $TOKEN_PAGE"
    EXPIRES=$(grep -i '^github-authentication-token-expiration:' <<<"$HEADERS" | sed 's/^[^:]*: *//' || true)
    [[ -n "$EXPIRES" ]] ||
      fail "The token has no expiration." "Delete it (https://github.com/settings/tokens) and create one that expires in a year: $TOKEN_PAGE"
    ok "the token is $LOGIN's, scopes '$SCOPES', expiring $EXPIRES"
  fi
  # The token goes to gh on its standard input: never on a command line,
  # never printed. An environment secret, never a repository one: a
  # repository secret is readable by a workflow of any branch.
  printf '  %s$ gh secret set %s --env %s --repo %s < (the token)%s\n' "$BOLD" "$PROJECT_TOKEN_SECRET" "$BOARD_ENVIRONMENT" "$REPO" "$RESET"
  if $DRY_RUN; then
    run gh secret list --env "$BOARD_ENVIRONMENT" --repo "$REPO"
  else
    printf '%s' "$TOKEN" | gh secret set "$PROJECT_TOKEN_SECRET" --env "$BOARD_ENVIRONMENT" --repo "$REPO" ||
      fail "gh secret set failed." "Read the error above."
    WRITTEN_SECRET+=("$PROJECT_TOKEN_SECRET")
    board_secret_stored || fail "The secret $PROJECT_TOKEN_SECRET is not listed on the environment $BOARD_ENVIRONMENT." "gh secret set $PROJECT_TOKEN_SECRET --env $BOARD_ENVIRONMENT --repo $REPO"
    ok "the secret $PROJECT_TOKEN_SECRET is set on the environment $BOARD_ENVIRONMENT"
  fi
  note "GitHub holds the token as the secret and nothing else does: it is not"
  note "saved here. It expires in a year; re-run this wizard to rotate it."
fi

# A repository secret of the same name, from before the environment: every
# workflow of every branch can read one, which the environment prevents.
if secret_stored "$PROJECT_TOKEN_SECRET"; then
  warn "A repository secret $PROJECT_TOKEN_SECRET exists next to the environment's: a workflow of any branch can read it."
  confirm "Delete the repository secret $PROJECT_TOKEN_SECRET (the environment's stays)?" ||
    fail "The repository secret $PROJECT_TOKEN_SECRET is still there." "gh secret delete $PROJECT_TOKEN_SECRET --repo $REPO"
  run gh secret delete "$PROJECT_TOKEN_SECRET" --repo "$REPO" ||
    fail "gh secret delete failed." "Read the error above."
fi

# The Template's environment, for its board dispatch (ADR 0017). One that
# exists is left as it is: no PUT rewrites its settings, only a missing
# TEMPLATE_BRANCH policy is added to its custom branch policies.
if ! $TEMPLATE_OK; then
  say ""
  if template_environment_exists; then
    ok "$TEMPLATE_NAME has the environment $BOARD_ENVIRONMENT: it is left as it is"
    [[ "$(gh_read api "repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT" --jq '.deployment_branch_policy.custom_branch_policies')" == true ]] ||
      fail "$TEMPLATE_NAME's environment $BOARD_ENVIRONMENT does not admit selected branches only." \
        "Set its Deployment branches to Selected branches and tags, with $TEMPLATE_BRANCH alone: https://github.com/$TEMPLATE/settings/environments"
  else
    say "$TEMPLATE_NAME's environment $BOARD_ENVIRONMENT, the key's home, with a deployment branch"
    say "policy of its own ($TEMPLATE_BRANCH alone, below); both calls are idempotent:"
    printf '  %s$ printf %s | gh api -X PUT repos/%s/environments/%s --input -%s\n' "$BOLD" "'$BOARD_POLICY'" "$TEMPLATE" "$BOARD_ENVIRONMENT" "$RESET"
    if ! $DRY_RUN; then
      printf '%s' "$BOARD_POLICY" | gh api --silent -X PUT "repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT" --input - ||
        fail "gh api -X PUT repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT failed." "Read the error above."
    fi
  fi
  if grep -qx "$TEMPLATE_BRANCH" <<<"$(board_policy_branches "$TEMPLATE")"; then
    ok "the policy admits $TEMPLATE_BRANCH"
  else
    run gh api --silent -X POST "repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT/deployment-branch-policies" -f "name=$TEMPLATE_BRANCH" -f type=branch ||
      fail "gh api -X POST repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT/deployment-branch-policies failed." "Read the error above."
  fi
  if $DRY_RUN; then
    run gh api "repos/$TEMPLATE/environments/$BOARD_ENVIRONMENT/deployment-branch-policies"
    note "A real run then checks that the environment admits $TEMPLATE_BRANCH alone."
  else
    template_environment_ok ||
      fail "$TEMPLATE_NAME's environment $BOARD_ENVIRONMENT does not admit $TEMPLATE_BRANCH alone: its policy admits '$(board_policy_branches "$TEMPLATE" | tr '\n' ' ')'." "Remove every other branch from it: https://github.com/$TEMPLATE/settings/environments"
    ok "$TEMPLATE_NAME's environment $BOARD_ENVIRONMENT exists and admits $TEMPLATE_BRANCH alone"
  fi
fi

# The App's key in it: when it is missing, or when the App stages stored a
# new key this run, so both repositories hold the same one.
if ! $TEMPLATE_KEY_STORED || ! $APP_DONE; then
  say ""
  say "The App's private key, as the secret $PRIVATE_KEY_SECRET of $TEMPLATE_NAME's environment $BOARD_ENVIRONMENT:"
  if [[ -z "$KEY_FILE" ]]; then
    say "the App stages were kept from an earlier run, so give the .pem file again. If it"
    say "was deleted, generate another under Private keys on the App's settings page: the"
    say "key $REPO_NAME holds stays valid."
    open_url "https://github.com/settings/apps"
    ask_key_file
    say ""
    say "Checking the key as the App, installed on $TEMPLATE_NAME:"
    if $DRY_RUN; then
      run pnpm --silent github-app check --repo "$TEMPLATE" --client-id "<$CLIENT_ID_VARIABLE>" --private-key "$KEY_FILE" --installed
    else
      CLIENT_ID=$(gh_read variable get "$CLIENT_ID_VARIABLE" --repo "$REPO")
      printf '  %s$ pnpm --silent github-app check --repo %s --client-id %s --private-key %s --installed%s\n' "$BOLD" "$TEMPLATE" "$CLIENT_ID" "$KEY_FILE" "$RESET"
      REPORT=$(pnpm --silent github-app check --repo "$TEMPLATE" --client-id "$CLIENT_ID" --private-key "$KEY_FILE" --installed) ||
        fail "The key is not the App's, or the App is not installed on $TEMPLATE as the workflows need it (above)." "Give the App's .pem file, or fix the installation: https://github.com/settings/installations"
      while IFS= read -r line; do note "  $line"; done <<<"$REPORT"
      ok "the key is the App's, installed on $TEMPLATE"
    fi
  fi
  # The key goes to gh on its standard input, as in the App stages. An
  # environment secret, never a repository one: the environment admits
  # TEMPLATE_BRANCH alone.
  printf '  %s$ gh secret set %s --env %s --repo %s < %s%s\n' "$BOLD" "$PRIVATE_KEY_SECRET" "$BOARD_ENVIRONMENT" "$TEMPLATE" "$KEY_FILE" "$RESET"
  if $DRY_RUN; then
    run gh secret list --env "$BOARD_ENVIRONMENT" --repo "$TEMPLATE"
  else
    gh secret set "$PRIVATE_KEY_SECRET" --env "$BOARD_ENVIRONMENT" --repo "$TEMPLATE" <"$(shell_path "$KEY_FILE")" ||
      fail "gh secret set failed." "Read the error above."
    WRITTEN_SECRET+=("$PRIVATE_KEY_SECRET ($TEMPLATE_NAME, $BOARD_ENVIRONMENT)")
    template_key_stored || fail "The secret $PRIVATE_KEY_SECRET is not listed on $TEMPLATE_NAME's environment $BOARD_ENVIRONMENT." "gh secret set $PRIVATE_KEY_SECRET --env $BOARD_ENVIRONMENT --repo $TEMPLATE < <key file>"
    ok "the secret $PRIVATE_KEY_SECRET is set on $TEMPLATE_NAME's environment $BOARD_ENVIRONMENT"
  fi
fi
if [[ -n "$KEY_FILE" ]]; then
  note "The .pem file is no longer needed: delete it, or keep it offline. A lost"
  note "key is replaced by generating a new one and re-running this wizard."
fi

if $BOARD_PENDING; then
  say ""
  confirm "Send these requests (pnpm board:setup)?" || fail "The board is not set up." "Review them, then re-run."
  run pnpm --silent board:setup ||
    fail "pnpm board:setup failed; it stops at the first failed request (above)." "Fix the cause, then re-run: what was applied reads back and is not planned again."
  say ""
  say "Reading it back:"
  printf '  %s$ pnpm --silent board:setup --dry-run%s\n' "$BOLD" "$RESET"
  if $DRY_RUN; then
    note "A real run then checks that it plans nothing: the project exists, is"
    note "public, is linked to both repositories, with the Status options and the"
    note "views as committed."
  else
    BOARD_PLAN=$(board_plan) || fail "pnpm board:setup --dry-run failed: $(head -n 1 "$ERR_FILE")" "Read the error above."
    grep -q '^Dry run, 0 requests, none sent' <<<"$BOARD_PLAN" ||
      fail "The board does not read back as committed:" "$BOARD_PLAN"
    ok "the project exists, is public, is linked to both repositories, its Status options and its views as committed"
  fi
fi
BOARD_URL=$(board_url "$BOARD_PLAN")
: "${BOARD_URL:=https://github.com/users/$REPO_OWNER/projects/<its number>}"

if $BOARD_PENDING; then
  say ""
  say "The settings the API cannot make, on the board's views; each one is saved"
  say "with Save changes in the view's menu, or it stays yours alone:"
  open_url "$BOARD_URL"
  step "View ${BOLD}Board${RESET}: its column field is ${BOLD}Status${RESET} (a board the API makes takes it by itself; check it)."
  pause "Press Enter once Board shows the Status columns"
  step "View ${BOLD}By assignee${RESET}: Group by → ${BOLD}Assignees${RESET}, then Save changes."
  pause "Press Enter once By assignee is grouped and saved"
  step "View ${BOLD}By parent${RESET}: Group by → ${BOLD}Parent issue${RESET}, then Save changes."
  pause "Press Enter once By parent is grouped and saved"
  step "GitHub's own first view, ${BOLD}View 1${RESET}: its menu → Delete view (board:setup leaves it)."
  pause "Press Enter once View 1 is deleted"
fi

if $BOARD_PENDING || [[ -n "$TOKEN" ]]; then
  say ""
  say "The first reconcile, the board's single writer, as board.yml runs it:"
  if [[ -n "$TOKEN" ]]; then
    # With the token, as the workflow: its scope is proven by it.
    printf '  %s$ PROJECT_TOKEN=<the token> pnpm --silent board:reconcile%s\n' "$BOLD" "$RESET"
    $DRY_RUN || PROJECT_TOKEN="$TOKEN" retried pnpm --silent board:reconcile ||
      fail "pnpm board:reconcile failed with the token." "A refused write means the token lacks a scope: project, or public_repo for adding the issues (docs/release.md, \"The board\"). Create it again, then re-run."
  else
    note "The token of an earlier run is not at hand: this reconcile runs with your gh login;"
    note "board.yml runs the next one with the secret within the hour."
    run pnpm --silent board:reconcile ||
      fail "pnpm board:reconcile failed." "Read the error above, then re-run."
  fi
fi
unset TOKEN
pause "Press Enter to continue"

finish
if $DRY_RUN; then
  note "Dry run: nothing was set, installed or applied."
else
  ok "$REPO has its GitHub App, Renovate, its settings and its Claim board."
fi
say ""
say "Next, now that the App exists:"
say "  - Rehearse the Patch watch (#200), a dry run first, then for real:"
say "    ${BOLD}gh workflow run patch-watch.yml --ref master -f simulate_current_patch=3.0.0.24267 -f dry_run=true${RESET}"
say "    ${BOLD}gh workflow run patch-watch.yml --ref master -f simulate_current_patch=3.0.0.24267${RESET}"
say "    then close its issue and pull request as their bodies say."
say "  - Human step 5 of $GUIDE (#46): the release workflow's dry run:"
say "    ${BOLD}gh workflow run release.yml --ref master -f dry-run=true${RESET}"
say "  - The board's workflow runs hourly and on this repository's issue events;"
say "    see its first run go green, or start one now (from $BOARD_BRANCH: another ref"
say "    is refused the secret by the environment $BOARD_ENVIRONMENT):"
say "    ${BOLD}gh workflow run board.yml --ref $BOARD_BRANCH${RESET}"
say ""
