// The renderers: the model to the text of the two generated files.

import type { EditorGlobalsModel } from "./model.js";

const BANNER = [
  "Generated by reforged-map from the map folder's war3map.lua and war3map.wtg on every install, build and watch.",
  "Do not edit: add or rename the globals in the World Editor.",
];

/** The declaration file: one `declare let` per global. */
export function renderDeclarations(model: EditorGlobalsModel): string {
  return render(
    "//",
    model.globals.map((g) => `declare let ${g.name}: ${g.type};`),
  );
}

/**
 * The Lua stub for the reforged-test harness: nil or the header literal per
 * global, so it calls no Native, adds no call-log line and consumes no
 * handle id. It defines `__jarray` when absent, since reforged-test does not
 * stub the game's array helper.
 */
export function renderLuaStub(model: EditorGlobalsModel): string {
  return render("--", [
    "if __jarray == nil then",
    "  function __jarray(default)",
    "    return setmetatable({}, { __index = function() return default end })",
    "  end",
    "end",
    ...model.globals.map((g) => `${g.name} = ${g.stubValue}`),
  ]);
}

function render(comment: string, body: readonly string[]): string {
  return [...BANNER.map((line) => `${comment} ${line}`), "", ...body, ""].join(
    "\n",
  );
}
