/** @noSelfInFile */
// Generated by reforged-types: the entry of game version 3.0.0, Patch 3.0.0.24268.
// Source: jass-history tag Reforged-v3.0.0.24268-w3-3a9d8f2, commit a392fc3d5e6c37980accbfc560b28387fc7d01bc.
// Do not edit: curate the Overlay, then run `pnpm --filter reforged-types typings:generate`.
// common.ai is not referenced here: add `reforged-types/3.0.0/common.ai` to `types` to use it.
/// <reference types="lua-types/5.3" resolution-mode="require" />
/// <reference path="./lua-runtime.d.ts" />
/// <reference path="./3.0.0/common.j.d.ts" />
/// <reference path="./3.0.0/blizzard.j.d.ts" />
