/**
 * The report's two files: the JSON the docs site and the compatibility
 * matrix read, and its Markdown rendering for the CI artefact. Both are
 * deterministic: LF, no timestamps, one trailing newline.
 */
import type { CoverageReport, WrapperCoverage } from "./report.js";

export function renderJson(report: CoverageReport): string {
  return JSON.stringify(report, null, 2) + "\n";
}

/** A Markdown table: the header, its alignment row, then one row per line. */
function table(
  header: readonly string[],
  align: readonly ("left" | "right")[],
  rows: readonly (readonly (string | number)[])[],
): string[] {
  const line = (cells: readonly (string | number)[]) =>
    `| ${cells.map(String).join(" | ")} |`;
  const rule = header.map((cell, index) =>
    align[index] === "right"
      ? `${"-".repeat(cell.length - 1)}:`
      : "-".repeat(cell.length),
  );
  return [line(header), line(rule), ...rows.map(line)];
}

/** The section of one Wrapper: its missing, excluded and covered Natives. */
function wrapperSection(entry: WrapperCoverage): string[] {
  const lists: string[][] = [];
  if (entry.missing.length > 0)
    lists.push([
      "Missing:",
      "",
      ...entry.missing.map((native) => `- \`${native.signature}\``),
    ]);
  if (entry.excluded.length > 0)
    lists.push([
      "Excluded:",
      "",
      ...entry.excluded.map(
        (native) =>
          `- \`${native.signature}\`: ${native.reason} Source: ${native.source} (${native.date}).`,
      ),
    ]);
  if (entry.covered.length > 0)
    lists.push([
      "Covered:",
      "",
      ...table(
        ["Native", "Covered by"],
        ["left", "left"],
        entry.covered.map((native) => [
          `\`${native.name}\``,
          native.coveredBy.join(", "),
        ]),
      ),
    ]);
  return [
    `### ${entry.wrapper} (\`${entry.type}\`)`,
    "",
    ...lists.flatMap((list) => [...list, ""]),
  ];
}

export function renderMarkdown(report: CoverageReport): string {
  const { totals } = report;
  return [
    "# Wrapper coverage report",
    "",
    `Generated by \`pnpm coverage:report\` from the manifest of Patch ${report.patch} and the library sources; do not edit. ` +
      "A Wrapper covers the common.j Natives its handle type owns (ADR 0008).",
    "",
    ...table(
      [
        "Owned",
        "Covered",
        "Excluded",
        "Missing",
        "Unowned",
        "common.j Natives",
      ],
      ["right", "right", "right", "right", "right", "right"],
      [
        [
          totals.owned,
          totals.covered,
          totals.excluded,
          totals.missing,
          totals.unowned,
          totals.natives,
        ],
      ],
    ),
    "",
    "## Problems",
    "",
    ...(report.problems.length === 0
      ? ["None."]
      : report.problems.map(
          ({ kind, message }) => `- \`${kind}\`: ${message}`,
        )),
    "",
    "## Wrappers",
    "",
    ...table(
      ["Wrapper", "Type", "Owned", "Covered", "Excluded", "Missing"],
      ["left", "left", "right", "right", "right", "right"],
      report.wrappers.map(({ wrapper, type, counts }) => [
        wrapper,
        `\`${type}\``,
        counts.owned,
        counts.covered,
        counts.excluded,
        counts.missing,
      ]),
    ),
    "",
    ...report.wrappers.flatMap(wrapperSection),
    "## Unowned Natives",
    "",
    "Outside the coverage rule: the first parameter is a handle type no Wrapper owns, " +
      "or no handle and no wrapped handle is returned. The JSON report names each Native.",
    "",
    ...table(
      ["First parameter", "Natives"],
      ["left", "right"],
      [
        ...report.unowned.handleFirst.map(({ type, count }) => [
          `\`${type}\``,
          count,
        ]),
        ["No handle", report.unowned.noHandle.count],
      ],
    ),
    "",
  ].join("\n");
}
