// The API reference (#40): the docusaurus-plugin-typedoc instances that
// generate it into the docs tree, and their place in the sidebar. The site's
// own TypeDoc plugin (typedoc/plugin.mts) runs in each instance.
import { existsSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, posix } from "node:path";
import { fileURLToPath } from "node:url";
import type { PluginConfig } from "@docusaurus/types";
import type { PluginOptions as DocsPluginOptions } from "@docusaurus/plugin-content-docs";
import type { PluginOptions as MarkdownOptions } from "docusaurus-plugin-typedoc";
import type { TypeDocOptions } from "typedoc";

const SITE = dirname(fileURLToPath(import.meta.url));
const WORKSPACE = join(SITE, "..");

/**
 * The site's TypeDoc plugin, by path: TypeDoc imports it itself, so it runs
 * against TypeDoc's own module instance.
 */
export const SITE_TYPEDOC_PLUGIN = join(SITE, "typedoc", "plugin.mts");

/** One API reference: a TypeDoc run whose Markdown goes into the docs tree. */
export interface Reference {
  /** The docusaurus-plugin-typedoc instance's plugin id. */
  readonly id: string;
  /** The sidebar label of its category. */
  readonly label: string;
  /**
   * Its folder in the docs tree, relative to the docs folder, POSIX slashes.
   * A subfolder of a section: TypeDoc empties it at every run, and the
   * section's own index page and category file must survive.
   */
  readonly dir: string;
  /** The entry points, absolute. */
  readonly entryPoints: readonly string[];
  /** The tsconfig TypeDoc compiles them with, absolute. */
  readonly tsconfig: string;
}

/** The library, from its index, with its own tsconfig. */
export const LIBRARY_REFERENCE: Reference = {
  id: "reforged-ts",
  label: "reforged-ts",
  dir: "api/reforged-ts",
  entryPoints: [join(WORKSPACE, "packages/reforged-ts/src/index.ts")],
  tsconfig: join(WORKSPACE, "packages/reforged-ts/tsconfig.json"),
};

/** Every reference the site generates, in sidebar order. */
export const REFERENCES: readonly Reference[] = [LIBRARY_REFERENCE];

/** How a reference is generated. */
export interface ReferenceOptions {
  /**
   * Fail on TypeDoc's validation warnings, an undocumented member first,
   * instead of reporting them.
   */
  readonly strict: boolean;
  /** Where the docs tree is, absolute. The site's `docs` by default. */
  readonly docsPath?: string;
}

/** The options of a reference's TypeDoc run, as docusaurus-plugin-typedoc takes them. */
export type ReferencePluginOptions = Partial<TypeDocOptions> &
  Partial<MarkdownOptions> & { readonly id: string };

export function referencePluginOptions(
  reference: Reference,
  options: ReferenceOptions,
): ReferencePluginOptions {
  const docsPath = options.docsPath ?? join(SITE, "docs");
  return {
    id: reference.id,
    // TypeDoc reads entry points as globs, which take POSIX slashes only.
    entryPoints: reference.entryPoints.map((path) =>
      path.replaceAll("\\", "/"),
    ),
    name: reference.label,
    tsconfig: reference.tsconfig,
    out: join(docsPath, reference.dir),
    docsPath,
    plugin: [SITE_TYPEDOC_PLUGIN],
    readme: "none",
    // An `@example` whose body is only an `{@includeCode}` is parsed as
    // TSDoc, not taken as literal code the JSDoc way: TypeDoc then expands the
    // include into a fenced block. The line on the tag is the example's title.
    jsDocCompatibility: { exampleTag: false },
    validation: { notDocumented: true },
    treatValidationWarningsAsErrors: options.strict,
  };
}

/** A reference's docusaurus-plugin-typedoc instance, for the site's `plugins`. */
export function referencePlugin(
  reference: Reference,
  options: ReferenceOptions,
): PluginConfig {
  return [
    "docusaurus-plugin-typedoc",
    referencePluginOptions(reference, options),
  ];
}

type SidebarItemsGenerator = NonNullable<
  DocsPluginOptions["sidebarItemsGenerator"]
>;
type SidebarItem = Awaited<ReturnType<SidebarItemsGenerator>>[number];

/**
 * The docs plugin's sidebar generator: the autogenerated sidebar, where each
 * reference's folder is replaced by the sidebar its TypeDoc run wrote
 * (`typedoc-sidebar.cjs`), as a category linked to its index page, at the
 * end of the section that holds the folder.
 */
export function referenceSidebars(
  references: readonly Reference[],
): SidebarItemsGenerator {
  return async ({ defaultSidebarItemsGenerator, ...args }) => {
    const inReference = (dir: string) =>
      references.some(
        (reference) =>
          dir === reference.dir || dir.startsWith(`${reference.dir}/`),
      );
    const items = await defaultSidebarItemsGenerator({
      ...args,
      docs: args.docs.filter((doc) => !inReference(doc.sourceDirName)),
    });
    for (const reference of references) {
      const section = findSection(items, posix.dirname(reference.dir));
      if (section === undefined) {
        throw new Error(
          `The reference of ${reference.label} goes in docs/${posix.dirname(reference.dir)}, which has no index page in the sidebar.`,
        );
      }
      section.items.push({
        type: "category",
        label: reference.label,
        link: { type: "doc", id: `${reference.dir}/index` },
        items: generatedSidebar(args.version.contentPath, reference),
      });
    }
    return items;
  };
}

type SidebarCategory = Extract<SidebarItem, { type: "category" }>;

/** The category whose link is the index page of `dir`. */
function findSection(
  items: readonly SidebarItem[],
  dir: string,
): SidebarCategory | undefined {
  for (const item of items) {
    if (item.type !== "category") continue;
    if (item.link?.type === "doc" && item.link.id === `${dir}/index`) {
      return item;
    }
    const found = findSection(item.items, dir);
    if (found !== undefined) return found;
  }
  return undefined;
}

/** The sidebar a reference's TypeDoc run wrote, read afresh at every call. */
function generatedSidebar(
  contentPath: string,
  reference: Reference,
): SidebarItem[] {
  const file = join(contentPath, reference.dir, "typedoc-sidebar.cjs");
  if (!existsSync(file)) {
    throw new Error(
      `${file} does not exist: the reference of ${reference.label} was not generated. TypeDoc's log above says why.`,
    );
  }
  const require = createRequire(import.meta.url);
  // A rerun of `docs:start` regenerates the file: never serve a cached one.
  // eslint-disable-next-line @typescript-eslint/no-dynamic-delete -- the require cache is keyed by path
  delete require.cache[file];
  return require(file) as SidebarItem[];
}
