import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One sidebar generated from the docs folders: each section's order and label
// are in its `_category_.json`, and its `index` page is the section's link.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
