/**
 * The files a generation writes besides the three declaration files: the
 * entry of the Game version, `async-natives.json` and the manifest of the
 * Patch. Deterministic like the declaration files: LF, no timestamps, one
 * trailing newline.
 */
import { gameVersion } from "./build.js";
import { REGENERATE_COMMAND } from "./emit.js";
import { byCodePoint } from "./order.js";
import type { PatchIdentity } from "./provenance.js";
import type { Resolved, ResolvedFunction, ResolvedGlobal } from "./resolve.js";

/** The hand-written declarations of the Lua runtime, at the package root. */
export const LUA_RUNTIME_FILE = "lua-runtime.d.ts";

/** The Lua standard library the game embeds, by lua-types reference. */
export const LUA_TYPES_REFERENCE = "lua-types/5.3";

export const ASYNC_NATIVES_FILE = "async-natives.json";

export const MANIFEST_FILE = "manifest.json";

/**
 * The entry of the Game version: references the Lua standard library, the
 * Lua runtime file and the common.j and blizzard.j outputs. The common.ai
 * output is opt-in by its own path and never referenced here.
 */
export function emitEntry({ patch, tag, commit }: PatchIdentity): string {
  const folder = gameVersion(patch);
  return [
    "/** @noSelfInFile */",
    `// Generated by reforged-types: the entry of game version ${folder}, Patch ${patch}.`,
    `// Source: jass-history tag ${tag}, commit ${commit}.`,
    `// Do not edit: curate the Overlay, then run \`${REGENERATE_COMMAND}\`.`,
    `// common.ai is not referenced here: add \`reforged-types/${folder}/common.ai\` to \`types\` to use it.`,
    // The package is `"type": "module"`, so under node16/nodenext the entry
    // resolves as an ES module, which adds no extension; lua-types has no
    // `exports` and only a `5.3.d.ts`. CommonJS rules find it in every mode.
    `/// <reference types="${LUA_TYPES_REFERENCE}" resolution-mode="require" />`,
    `/// <reference path="./${LUA_RUNTIME_FILE}" />`,
    `/// <reference path="./${folder}/common.j.d.ts" />`,
    `/// <reference path="./${folder}/blizzard.j.d.ts" />`,
    "",
  ].join("\n");
}

/** The names of the async functions, in code-point order, one per line. */
export function emitAsyncNatives(declarations: readonly Resolved[]): string {
  const names = new Set(
    declarations
      .filter((d): d is ResolvedFunction => isFunction(d) && d.overlay.async)
      .map((d) => d.name),
  );
  return JSON.stringify([...names].sort(byCodePoint), null, 2) + "\n";
}

/**
 * Every function and global of the Patch in source order, with its Jass
 * types and Overlay facts; one entry per line, so that the diff between two
 * Patches reads declaration by declaration. Absent facts are `null`, so
 * every entry of a kind has the same keys.
 */
export function emitManifest(
  patch: string,
  declarations: readonly Resolved[],
): string {
  const entries = declarations.flatMap((d) =>
    d.kind === "type" ? [] : [JSON.stringify(manifestEntry(d))],
  );
  const list =
    entries.length === 0
      ? "[]"
      : `[\n${entries.map((line) => `    ${line}`).join(",\n")}\n  ]`;
  return `{\n  "patch": ${JSON.stringify(patch)},\n  "entries": ${list}\n}\n`;
}

function manifestEntry(declaration: ResolvedFunction | ResolvedGlobal) {
  if (declaration.kind === "global") {
    const { name, source, constant, array, type, overlay } = declaration;
    return {
      name,
      source,
      kind: "global",
      constant,
      array,
      type,
      nullable: overlay.nullable,
      since: overlay.since ?? null,
      deprecated: overlay.deprecated ?? null,
    };
  }
  const { name, source, kind, constant, params, returns, overlay } =
    declaration;
  return {
    name,
    source,
    kind,
    constant,
    params: params.map((param, index) => ({
      name: param.name,
      type: param.type,
      nullable: overlay.params[index].nullable,
    })),
    returns: { type: returns, nullable: overlay.returns.nullable },
    async: overlay.async,
    since: overlay.since ?? null,
    deprecated: overlay.deprecated ?? null,
  };
}

function isFunction(declaration: Resolved): declaration is ResolvedFunction {
  return declaration.kind === "native" || declaration.kind === "function";
}
