/**
 * Writes the declaration file of one Patch source: `@noSelfInFile`, the
 * generated-file banner, the common.j prelude, then every declaration in
 * source order. Deterministic: LF, no timestamps, one trailing newline.
 */
import { functionHeader } from "./header.js";
import { CODE_ALIAS, tsType } from "./jass-types.js";
import type { SourceName, TypeDeclaration } from "./model.js";
import type { PatchIdentity } from "./provenance.js";
import type { Resolved, ResolvedFunction } from "./resolve.js";

export const REGENERATE_COMMAND =
  "pnpm --filter reforged-types typings:generate";

export function emitFile(
  source: SourceName,
  declarations: readonly Resolved[],
  identity: PatchIdentity
): string {
  const blocks: string[][] = [banner(source, identity)];
  if (source === "common.j") blocks.push(prelude());

  let types: string[] | undefined;
  for (const declaration of declarations) {
    if (declaration.kind === "type") {
      // Consecutive types share one block, one line each.
      if (!types) blocks.push((types = []));
      types.push(typeDeclaration(declaration));
    } else {
      types = undefined;
      blocks.push(functionDeclaration(declaration));
    }
  }
  return blocks.map((block) => block.join("\n")).join("\n\n") + "\n";
}

function banner(
  source: SourceName,
  { patch, tag, commit }: PatchIdentity
): string[] {
  return [
    "/** @noSelfInFile */",
    `// Generated by reforged-types from ${source} of Patch ${patch}.`,
    `// Source: jass-history tag ${tag}, commit ${commit}.`,
    `// Do not edit: curate the Overlay, then run \`${REGENERATE_COMMAND}\`.`,
  ];
}

/** The root of the handle hierarchy and the callback alias. */
function prelude(): string[] {
  return [
    "declare interface handle { __handle: never }",
    `type ${CODE_ALIAS} = (this: void) => void;`,
  ];
}

function typeDeclaration({ name, parent }: TypeDeclaration): string {
  return `declare interface ${name} extends ${parent} { __${name}: never }`;
}

function functionDeclaration(fn: ResolvedFunction): string[] {
  const params = parameterList(fn);
  const returns =
    tsType(fn.returns) + (fn.overlay.returns.nullable ? " | undefined" : "");
  return [
    ...functionHeader(fn),
    `declare function ${fn.name}(${params}): ${returns};`,
  ];
}

/**
 * Nullable trailing parameters become optional; a nullable parameter
 * followed by a non-nullable one becomes `T | undefined`.
 */
function parameterList(fn: ResolvedFunction): string {
  const nullable = fn.overlay.params.map((param) => param.nullable);
  const firstOptional = nullable.lastIndexOf(false) + 1;
  return fn.params
    .map((param, index) => {
      const type = tsType(param.type);
      if (!nullable[index]) return `${param.name}: ${type}`;
      return index >= firstOptional
        ? `${param.name}?: ${type}`
        : `${param.name}: ${type} | undefined`;
    })
    .join(", ");
}
